### ISSUE TITLE
v1.10-dpr-6-g3e4b685 (3e4b685) - advanced search - zombie queues, still alive in 1.10.1

### ISSUE THREAD

**Issue by ghost** [osTicket/osTicket#2073] opened 2015-05-15 19:00 UTC
I was wondering why some of my saved searches look weird and weren't usable or deleteable.
This occurs when you didn't name it before you save (had forgotten it). You can reproduce it when you do the following.
1. Create a Search without a name:
   ![screenshot 1](https://cloud.githubusercontent.com/assets/5539456/7659794/f48b9802-fb44-11e4-889c-9c1a356022e0.jpg)
2. Close the window:
   ![screenshot 2](https://cloud.githubusercontent.com/assets/5539456/7659804/0197258e-fb45-11e4-86ea-fc62f7cd9849.jpg)
3. Open the window again:
   ![screenshot 3](https://cloud.githubusercontent.com/assets/5539456/7659809/09507a6e-fb45-11e4-8c39-174c270353f0.jpg)

**Comment by ntozier** [comment] 2015-05-15 19:04
@greezybacon has FAILED!  ;)

**Comment by Chefkeks** [comment] 2015-05-15 19:24
@ntozier 
Are you sure @greezybacon really failed?...
I mean this could be a feature and not a bug - or aren't there any easter eggs in osTicket?! :D

**Comment by mfelber** [comment] 2015-05-15 19:39
@Chefkeks I have clicked on them very excessive, no pong or other easter eggs were offered ;-) I think we could classify it as a undocumented way to create a styling bar..

**Comment by Chefkeks** [comment] 2015-05-15 20:47
@mfelber :D :+1:

**Comment by greezybacon** [comment] 2015-05-16 14:41
You guys are cracking me up

**Comment by ntozier** [comment] 2015-05-18 13:16
hehehe. :)

**Comment by nickwright80** [comment] 2017-02-28 14:30
` DELETE FROM ost_queue WHERE title IS NULL; -- greezybacon has FAILED`

**Comment by mfelber** [comment] 2017-11-14 14:45
I have just noticed that the zombies (undeletable & unusable saved searches) are still alive, even in 1.10.1 ;-)

**Comment by mfelber** [comment] 2017-11-14 14:55
Please put him out of his suffering..and give him a head shot!

**Comment by ntozier** [comment] 2017-11-14 15:24
I was under the impression that it was slated to be fixed in the next release. 1.11.

**Comment by JediKev** [comment] 2017-11-14 16:39
Have you guys tried [this pull request](https://github.com/osTicket/osTicket/pull/3665)?  It'll still let you save with no name but it'll be `NULL` instead of blank. This way you can actually delete it later if it was an accident. Let me know how this goes! Cheers.

**Comment by mfelber** [comment] 2017-11-14 17:52
No I didn't tried it before. But I have just tested it and it behaves how you describe it:
![null search](https://user-images.githubusercontent.com/5539456/32795397-cdc6bf10-c96b-11e7-9a3b-c8e08d7f4580.png)

The saved search without a title isn't longer undeletable via the gui 👍 
Thanks for the hint! The zombie is healed..

Should I close the issue report or wait until it is merged?

**Comment by JediKev** [comment] 2017-11-14 17:53
I would wait just in case other people run across this. :+1:

**Comment by mfelber** [comment] 2017-11-14 18:04
Ok, make sense.

**Closed** 2020-02-26 22:32 UTC
Labels: Search, UI, bug, next
