### ISSUE TITLE
Custom form field not saving

### ISSUE THREAD

**Issue by bertaviader** [osTicket/osTicket#4545] opened 2018-10-09 10:10 UTC
### Prerequisites

* [N/A] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [N] Do you have any errors in the PHP error log, or JavaScript console?
* [Y] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [Y] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description
Added a new checkbox field in Contact Information form. 
When the user sign in, the field is displayed, but although the user click in the checkbox the information is not saved. 
If the user sign in and then the user go to the Profile and check the checkbox the information is saved.

### Steps to Reproduce

1. Add the checkbox field in the contact information form

![form](https://user-images.githubusercontent.com/18306366/46662859-d1443b00-cbbc-11e8-9429-9b08c63cd369.png)

2. Sig in
![signin](https://user-images.githubusercontent.com/18306366/46662730-84f8fb00-cbbc-11e8-8d0c-24172ef0d9e5.png)

3. Go to the user information in the Agent Panel. And the checkbox is not saved
![user_info](https://user-images.githubusercontent.com/18306366/46662335-6e9e6f80-cbbb-11e8-884e-747ef78ae0d4.png)

**Expected behavior:** 
Save the information of the user.

**Actual behavior:**
The information is not saved.

### Versions

![osticket_server_info](https://user-images.githubusercontent.com/18306366/46662465-c6d57180-cbbb-11e8-9f85-cba71050d327.png)

OS: Ubuntu 14.04 
Browser: Google Chrome Version 65

**Comment by JediKev** [comment] 2018-10-09 13:30
@bertaviader 

This will not update the User's profile. The User will have to go to their Profile in order to update the field. This is not a bug so please close this.

Cheers.

**Closed** 2018-10-10 11:44 UTC

**Comment by utl13** [comment] 2019-09-09 09:51
I've the same issue, and I'm confused, why this is not a bug. If a user selects (sets to true) a checkbox during account registration then they expect their action to be saved in the system, which is not happening. Checking the database shows that the value is saved as 0, but should be 1. This happens only with Checkbox type, other types of fields are working as expected.
