### ISSUE TITLE
Attachments in responses don't get attached

### ISSUE THREAD

**Issue by simonnzg** [osTicket/osTicket#2992] opened 2016-03-29 15:25 UTC
Running c2e81b8 and notice that if I respond to a User and attach a file to my response the response is sent without the attachment.  No mention of the attachment in the ticket timeline, either.

This is not a new "feature" as I have noticed it on 10.1RC2 on occasions for some time but never managed to get my finger on the cause.

Previously, I have not been able to reproduce the problem when I needed to test it, but at the moment it happens on everything I try to attach, even using Linux instead of Windows 10 (what my users use).

Files to be sent are usually on my/their local filesystem.
"e-mail attachments" to the user in default SMTP Handler is SET.
The mail.log logs the e-mail being sent, but no mention of an attachment.

**Comment by ntozier** [comment] 2016-03-29 15:37
Did you alter your templates to include the %{message.files} variable?

**Comment by simonnzg** [comment] 2016-03-29 15:51
Nope. Templates are essentially stock, although with wording changed to reflect local norms.
Is that required? Why would it work sometimes and not at others, even with two people working on the same ticket, one can't and maybe one can?

**Comment by simonnzg** [comment] 2016-03-29 15:56
I tried it: %{message.files}  is not a valid variable in the context of entering it into a response template.

**Comment by simonnzg** [comment] 2016-03-29 15:57
I wondered, as I can't see that the template should define whether I can send an attachment from the ticket timeline or not. That would define the format of the response and include the response, which includes the attachment (or should).

**Comment by ntozier** [comment] 2016-03-29 17:10
My mistake that variable is for agent templates.
Also your original post does not say that it is intermittent, but you clearly ask "Why would it work sometimes and not at others".  Is this intermittent or not?

**Comment by simonnzg** [comment] 2016-03-29 17:52
Well, it USED to be intermittent, but now I can't send attachments at all.  I have restarted the host Apache2 instance, even rebooted the server, but still not working.
I'm going to work my way through the process and see if I can find out exactly what is happening. I'm not absolutely sure that it is entirely an osTicket problem and may be a supporting infrastructure issue, perhaps PHP on the hosting server (Ubuntu 14.04 LTS). The mail log implies that no attachment has got to it, so may try stabbing in the dark to see if anything squeaks.

**Comment by ntozier** [comment] 2016-03-29 19:02
see https://github.com/osTicket/osTicket/pull/2995

**Comment by simonnzg** [comment] 2016-03-29 19:28
Does seem very similar, doesn't it? :)
My guess is that the previous intermittent problems are unrelated.

**Comment by greezybacon** [comment] 2016-03-30 17:12
@simonnzg there is a race condition that can cause missing files when uploading multiple files simultaneously. Some information in the session is thrashed and corrupted which causes the files not to "stick".

**Comment by simonnzg** [comment] 2016-03-30 18:14
Aha. Problem with us is that we always only send one file, usually no more than a 170k PDF. 

I'm using part of my osTicket installation as a managed mail queue for one particularly sloppy member of staff. A document comes in as a ticket from an automated system, he saves off the document, adds whatever notes he needs to add to the ticket history, changes the User to the person who needs to see the results and then responds to the new User, attaching the saved off copy of incoming file (saved to his PC) to the response. 
Long-winded, but the whole history is in one ticket and he can't hide his mess. :)
Worse still, I'm now getting problems with incoming attachments, see #3001 !

**Comment by cogitsa** [comment] 2016-11-24 07:14
I'm having pretty much the same problem. I googled to find this post.

Attachment issues in general. Attaching something when replying to a ticket looks like it works - but the other end doesn't receive it but does receive the email response. Canned responses that have attachments and a new one is added and saved or even just modified text, removes the previously saved attachments. Some tickets that have attachments included don't show in osticket but show fine in an email app. Worth noting it only happens to incoming tickets with a few images as/in their signature. Using php5.6 and mariadb 10.1 with current latest version. Nothing in error logs. How can I diagnose this?

**Comment by cogitsa** [comment] 2016-11-24 07:15
Sorry Simon, I don't know if this is hijacking your thread? I just feel it's related.

**Comment by simonnzg** [comment] 2016-11-24 07:43
Certainly seems to be, although my problem went away with an update (I forget which), and some patches suggested by Jared.
Worth seeing if it's #3001 again.

**Comment by simonnzg** [comment] 2016-11-24 07:54
I don't have access to an operational osTicket as I have changed companies, but I am currently running "Master" on a test system and attachments seem to be flowing properly.

**Comment by cogitsa** [comment] 2016-11-24 21:36
Thanks for the quick response, Simon. I have version 1.9.14. If I change the php version to 5.5 i get session errors. 5.4 works but just some of these issues with the attachments. I've uploaded 1.9.15 but the release notes don't seem to be anything related to the attachments. Still a little lost as to where to look.

**Comment by simonnzg** [comment] 2016-11-24 22:27
Try looking through #3035 to see if any of it makes sense.4
If you DON'T use PHP7, then the latest 1.10 will be worth testing.

**Comment by cogitsa** [comment] 2016-11-25 01:09
Thanks again Simon. I've been an idiot. It's my first time setting up OS ticket and when i downloaded it, i wanted the latest version 1.9 seemed later than 1.1... (deliberately leaving the 0 out there). I thought the 1.9 was later. I downloaded the latest 1.10 and updated to that and it seems to be working like a charm! Thank you again for the time and effort you spent on assisting me.

**Comment by simonnzg** [comment] 2016-11-25 08:09
I am sure you are not the only one.  In my mind, I consider them "Version 9 and 10".
I changed jobs recently and my new company is thinking of using osTicket. They have just installed 1.9, so I didn't think it strange that you were trying to get 1.9 running. Maybe I should ask them why they chose 1.9?

**Comment by cogitsa** [comment] 2016-11-26 08:12
From my understanding now, 1.9 is for php 5.3 and older. And 1.10 is for 5.3 and later.

I've had no issues at all since it's been upgraded to 1.10. I think they may of made the same mistake i did from the sounds of it.

**Comment by simonnzg** [comment] 2016-11-26 21:21
They say that they downloaded it in September before 1.10 was released, but didn't get around to installing it until recently.  An upgrade to 1.10 is certain!

**Comment by normdouglas** [comment] 2017-05-20 12:23
Forgive me for raising this again, however, I am using v1.10 (901e5ea) and I can confirm that %{message.files} does not work in AGENT emails.
I'm trying to use to to transfer to another agent and INCLUDE the original attachment in the email.
What I actually am trying to do is to transfer to a non manned agent which then goes to our accounting package (XERO) so the attachment (invoices etc) is sucked up into the XERO system.
Thanks

**Comment by normdouglas** [comment] 2018-04-01 21:07
I've tried the above fix and still no luck.
It would appear that what I am trying to do, goes against the logic of the system.
Essentially I need to be able to change the owner of a ticket and then respond to it whilst INCLUDING the attachment. Right now, our operators just download the attachment and then reattach... but they forget sometimes.
I say it's possibly a logic issue because i get the below response when I have %{message.files} in my reply template.

> "Some variables may not be a valid for this context. Please check for spelling errors and correct usage for this template. 
> %{message.files}"

**Comment by edimulyana** [comment] 2018-05-14 08:12
Hi @JediKev 

Any update for this?

**Comment by JediKev** [comment] 2018-05-14 18:55
@edimulyana 

Yes the official fix for this is here and is already merged into `develop` which means it will be available in the next release (v1.11rc-1; coming soon):
https://github.com/osTicket/osTicket/commit/24dbd3b3da1b48334abe881347cef1ef23c7d83f

Cheers.

**Comment by elvisvasc** [comment] 2018-06-11 19:13
I fixed this problem changing the line 3968 in the file include/class.forms.php:
`$allowed[$F->id] = 1;`
changed to:
`$allowed[$F->file_id] = `1;`

Cheers.

**Comment by madscientist159** [comment] 2018-06-12 07:40
@elvisvasc Thank you!  Saved me from the wrath of our sales team :smile:

**Closed** 2020-01-06 20:10 UTC
Labels: Attachments, cause unknown
