### ISSUE TITLE
New ticket alert not sent to department/group members

### ISSUE THREAD

**Issue by jack05ryan02** [osTicket/osTicket#2307] opened 2015-07-27 03:03 UTC
Hi,

We're having an issue receiving the new ticket when our customers created a ticket.  We have already set the alerts and notices to be sent to department/group members but everytime a new ticket is created, only the auto-assign person receive the ticket.
Version: 1.9.9.1

Please advise.

Thanks.

**Comment by protich** [comment] 2015-07-27 04:29
This is by design... only assigned agents get an alert when a ticket is auto-assigned. The rationale being – if a ticket is routed to a specific team or agent then there is no need to alert the entire department.

**Comment by jack05ryan02** [comment] 2015-07-27 06:45
thank you.  is there any way that this can be done(sending email alerts to department/group members even if it is auto-assigned by the system)?

**Comment by SolidK0RE** [comment] 2015-08-11 04:14
What you need is a Teams. Just setup osTicket to auto-assign tickets to the teams and it will automatically send email alert when new ticket is created and assigned to the team.

**Comment by jack05ryan02** [comment] 2015-08-11 04:29
we have already tried what you've suggested but it will only send alert to team members and not auto-assign the ticket to the person.  what we want is to auto-assign the ticket to a specific person and at the same time alert the team/group where the auto-assign person belongs.

**Comment by Hannibal226** [comment] 2015-08-11 08:16
@jack05ryan02 
Maybe I missunderstand the problem here, but can't u just set the Auto-Assign in a Help Topic and also set the Department correctly?
So then the Ticket will assigned to the person u set and the Department will be informed, too.

CHEERS

**Comment by jack05ryan02** [comment] 2015-08-11 08:40
we have tried that but osTicket seems to be not working as expected.  Even if set to auto-assign to a specific person and set the department correctly, on the auto-assign person can receive the alert.  as you can see in the thread above mentioned by @protich that is the design of osTicket.

**Comment by Hannibal226** [comment] 2015-08-11 08:48
@jack05ryan02 
Ah ok, now I understand the "problem" u mentioned, sorry then.

I see so much Mails as OS-Admin and thought this is also one of the reasons,
but it's always info-mails for admin + Department  (most no auto-assign).

Sorry my fold.

**Comment by jack05ryan02** [comment] 2015-08-11 08:53
Yes, that is what we are doing right now as of the moment while waiting for the feature that we want to be implemented.

Overall, osTicket is great!

**Closed** 2020-01-06 20:13 UTC
Labels: question
