### ISSUE TITLE
1.10-RC2, tickets sorting on agent view

### ISSUE THREAD

**Issue by gshtapani** [osTicket/osTicket#2488] opened 2015-08-28 09:52 UTC
Hi,

I have upgraded my company's OsTicket system from 1.9.12 to 1.10-RC2.

Now agents (our support team) is struggling with ticket sorting.
It seems that OsTicket 1.10-RC2 doesn't use whole query result set for sorting, only what is currently visible on list.

Is this really a bug in 1.10-RC2?

Regards,
Tapani

**Comment by rowlandan25** [comment] 2015-08-28 13:14
I am encountering the same issue here.

**Comment by OBenned** [comment] 2015-09-08 09:22
We experienced the same issue that the sorting is not correct.

When we sort the first page is showing up correctly but not the following pages

**Comment by febrile42** [comment] 2015-09-21 17:10
I am also seeing the same behavior. Newly created tickets are on page 2, no matter the chosen sorting.
![ost-sorting1](https://cloud.githubusercontent.com/assets/14597122/9999017/226dac74-6062-11e5-964d-cf95111e03fb.png)
![ost-sorting2](https://cloud.githubusercontent.com/assets/14597122/9999018/226e1d44-6062-11e5-8ccb-90355596c52e.png)

**Comment by greezybacon** [comment] 2015-09-22 13:08
This is a duplicate of #2499. There is a patch for it in e17a9124e7c59d6de7ae21a8e736740b837badec. It's in #2056 to be merged toward rc3

**Comment by rayfoss** [comment] 2016-12-06 20:56
Closing duplicate issue, please continue the conversation on the ne

**Closed** 2016-12-06 21:04 UTC
