### ISSUE TITLE
Issue when reply to ticket: Editor but maybe also Issue in the visitor side

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket#2851] opened 2016-01-10 13:57 UTC
Hi,
is not easy give a title to this topic also my English is little so try to understand me.

I am using Osticket version 1.9.12 and I am on the operator side. I AM writing a long reply to the customer. My browser is Firefox 43.0.4 who is the last available today.

The HTML editor text advance is active so i can customize text color, bold or not... if you try to write a long message there are issue as when a draft is saved you loose the position where you are writing so ... for example if I am writing this text message (here in github) into a ticket as reply, just now I continue to write here and the cursor are moved to the start of the text where i wrote (Hi, ....) so is very hard.. I have to stop to write and click again on the right place of the text.

Is not good. So maybe also if the visitor write a long ticket can have the same issue. Infact i have send a wrong reply to customer ticket for this issue. I have wrote my text and without i see it some text start to be written on the top of the message when is a end text.

Very wrong, hope this can be fixed soon in the new release and you can test and see this issue.

**Comment by PeopleInside** [comment] 2016-01-10 14:10
Also if i disable the editor with the button <> i have wrote a long message, press send and loosed all text because was replaced, removed. Is not good. Very bad. I can't manage ticket in this way.

**Comment by PeopleInside** [comment] 2016-01-10 15:08
OK so consider also today I loose a full reply in the ticket for switching from HTMl to not HTML with the button <> for this issue.

As you can see I have tried in demo online but is the same on my server.
Here is a video with the issue of write a ticket reply or message on OsTicket

http://screencast.com/t/AC9R7Z3464Wr

Very bad

**Comment by PeopleInside** [comment] 2016-01-10 15:20
Maybe this is Firefox issue and should fowarded to Firefox BUG.
Please let me know if we have to Foward this issue to Firefox.

**Comment by mfelber** [comment] 2016-01-10 15:39
I think this is a duplicate issue: https://github.com/osTicket/osTicket-1.8/issues/2373

The html editor of osticket called "redactor" from imperavi has problems with newer firefox versions. osTicket 1.10 will have implemented a newer version of redactor, this will solve this problems as far as I know..

**Comment by PeopleInside** [comment] 2016-01-10 15:42
Thank you, so sorry for this duplicate, I will close now. Very terrible issue, I have lost a ticket reply for this issue, all my text lost.

**Comment by PeopleInside** [comment] 2016-11-04 11:23
1.10 still be bugged with this issue.

**Comment by ntozier** [comment] 2016-11-04 13:59
Back in Jan it was determined that this was a dupe of https://github.com/osTicket/osTicket/issues/2373 and that you were going to close the dupe issue report.  So I'm not sure why you are updating it now.  I believe that this is a Redactor editor issue.

**Closed** 2020-01-06 20:11 UTC
