### ISSUE TITLE
Reset Dashboard Ticket Activity

### ISSUE THREAD

**Issue by josehizon** [osTicket/osTicket#5347] opened 2020-01-23 06:15 UTC
Hi guys,

I just tested osticket and I want to reset the dashboard and statistics back to zero. How can I do that? Thank you.

**Comment by ntozier** [comment] 2020-01-23 14:23
This is not a bug/issue report.  Please post general questions on the forums instead.

That being said please see:
https://forum.osticket.com/d/93048-reset-dashboard-stats
https://forum.osticket.com/d/94088-reset-dashboard-back-to-zero

Please close this issue report.

**Closed as completed** 2020-01-23 17:24 UTC
Labels: question
