### ISSUE TITLE
KB Sub-categories

### ISSUE THREAD

**Issue by drtomasso** [osTicket/osTicket#2756] opened 2015-11-26 20:30 UTC
Hi

Is there any plans to add sub-categories for the knowledge base? If not, how about it? It would be great to sort all FAQ's into smaller sub-categories.

**Comment by nfebuary** [comment] 2015-11-30 16:58
We are looking into doing a FAQ overhaul as well as the user side UI and function. It's possible it wont be in this release since we are working on things in order of importance.

**Comment by tmcnag** [comment] 2015-12-22 22:12
Likely duplicate of:  https://github.com/osTicket/osTicket-1.7/issues/544

I have to agree, I love OSTicket but find the lack of subcats fairly limiting.  Still a killer KB, but that would really step it up for me.

+1 for sure!

**Comment by nfebuary** [comment] 2015-12-22 22:48
We have discussed the FAQ becoming more integrated and customizable in osTicket and we want to make it fully featured. The current discussion is what is the best way to do this in the existing system? I'm taking notes on feature requests on github, as well as ideas the team comes up with, and random ideas that pop into my head while in the shower. :flushed: (I highly suggest investing in shower markers it's a life saver.) Anyway... We really want the FAQ to stand out and not be an after thought.

**Comment by rbukovansky** [comment] 2017-01-13 08:35
Hi, is this moving somewhere anyhow, please? Thanks.

**Closed** 2020-01-06 20:11 UTC
