### ISSUE TITLE
develop-next - new ticket cancel button

### ISSUE THREAD

**Issue by gmt-it** [osTicket/osTicket#2881] opened 2016-01-21 17:36 UTC
![cancel](https://cloud.githubusercontent.com/assets/10116166/12488861/e9e5f570-c06d-11e5-8ca5-328ac3e8bc74.png)
Cancel Button at new ticket has no function after choose of helptopic.

**Comment by JediKev** [comment] 2016-03-02 14:57
What version are you running?

**Comment by gmt-it** [comment] 2016-03-02 20:47
Latest develop-next.

**Comment by meinsteren** [comment] 2016-09-07 12:51
I have the same Problem (Osticket v1.10-rc.3 / Latest commit 55dc25a  on Jul 10 ).

any solution ???

mfg
Giano

**Comment by mattfive** [comment] 2017-09-20 06:53
The issue is at the very end of the file osticket/include/client/open.inc.php:
I deleted some code in the javascript part of the cancel-button and at least now the button has its function. The code looks like this now:

<p class="buttons" style="text-align:center;">
        <input type="submit" value="<?php echo __('Create Ticket');?>">
        <input type="reset" name="reset" value="<?php echo __('Reset');?>">
        <input type="button" name="cancel" value="<?php echo __('Cancel');?>" onclick="javascript:
            window.location.href='index.php';">
  </p>

**Comment by JediKev** [comment] 2017-09-20 13:45
This issue is fixed with [this pull request](https://github.com/osTicket/osTicket/pull/2924). Please make the changes, clear all cache/cookies, and test again. If you see an issue with it please let me know and I'll look into it. Thanks.

**Comment by jamesaepp** [comment] 2018-12-31 17:06
I had this issue as well on 1.10. I never tested on the develop branch. It looks like it is solved on the develop branch but I thought I'd make note that I also experienced this issue while using osTicket.

osTicket v1.10.4 (035fd0a)
Apache 2.4.29 (ubuntu)
MySQL 5.7.24
PHP 7.2.10-0ubuntu0.18.04.1
All php extensions enabled/checked on

timedatectl on the server reports:
Local Time CST (America/Winnipeg)
RTC Time = Universal Time (Zulu)
Time Zone set to America/Winnipeg

**Closed** 2020-01-06 20:11 UTC
