### ISSUE TITLE
Custom data form > Information field broken in Client Portal

### ISSUE THREAD

**Issue by stevland** [osTicket/osTicket#5506] opened 2020-05-19 04:03 UTC
Admin Panel > Manage > Forms > Custom Form

![Admin Panel > Manage > Forms > Custom Form](https://stevland.com/misc/i001.png)

Client Portal > Open a New Ticket

![Client Portal > Open a New Ticket](https://stevland.com/misc/i002.png)

The form field is not generated.

`<tr>
            <td colspan="2" style="padding-top:10px;">
            <div class="thread-body bleed">            <h3>Information Test</h3>        <div></div>
        </div>
                    </td>
        </tr>`

osTicket Version | v1.14.2 (cba6035) —  Up to date
Web Server Software | Apache
MySQL Version | 10.4.13
PHP Version | 7.3.18

**Comment by JediKev** [comment] 2020-05-19 04:10
@stevland 

For me it shows up just fine:
![E8B7D036-73BD-47C7-A556-18903B2631EF](https://user-images.githubusercontent.com/11823401/82283611-81af1f00-995c-11ea-9dab-3e59ade6cf2b.jpeg)

Please go the the Config for the Information Test field, copy the Content, and paste it here in a code block so I can attempt to debug.

**Note:**
This does _not_ generate a form field to input data. This is only an informational field meaning it only displays information.

Cheers.

**Comment by ntozier** [comment] 2020-05-19 13:03
The `Information` type field is not a form field.  It is block of [informational] text. It does not result in a fillable field for someone to fill out.

**Comment by stevland** [comment] 2020-05-19 14:11
I misunderstood the purpose of `Information`. I thought it was to elicit information. Thank you for the explanation guys.

**Comment by JediKev** [comment] 2020-05-19 14:30
@stevland 

No problem! I will close this since this is intended behavior.

Cheers.

**Closed as completed by JediKev** 2020-05-19 14:30 UTC
