### ISSUE TITLE
Add custom field to database in osticket

### ISSUE THREAD

**Issue by amet123** [osTicket/osTicket#4544] opened 2018-10-09 06:22 UTC
I am trying to learn osticket. I am adding a new custom field to be shown on frontend. I have changed the file open.inc.php with adding the following code 

<tr><td colspan="2"><hr />
    <div class="form-header" style="margin-bottom:0.5em">
    <b><?php echo __('Location'); ?></b>
    </div>
</td></tr>
<tr>
    <td colspan="2">
        <select id="location" name="location" onChange="fetch_select(this.value)">
            <option value="" selected="selected">&mdash; <?php echo __('Select a State');?> &mdash;</option>
            <option value='Jalandhar'>Jalandhar</option>
        </select>

    </td>
</tr>

But nowhere I am able to find the code to add this data to database.

Please guys help me in osticket how I can add this field to database ?

**Comment by JediKev** [comment] 2018-10-09 13:32
@amet123 

This is not a bug report, rather a post for help. Please close this issue and post on our [Forum](http://osticket.com/forum) for more assistance.

Also, you may add custom Forms & Fields via **Admin Panel > Manage > Forms**.

Cheers.

**Closed** 2020-01-06 19:59 UTC
