### ISSUE TITLE
Convert e-mail sent not to support address to new ticket

### ISSUE THREAD

**Issue by mvidelgauz** [osTicket/osTicket#3488] opened 2016-11-09 11:17 UTC
I have e-mail box "support@mycompany.com" monitored by osTicket and it works well.

The problem is when a customer sends an e-mail to "myname@mycompany.com". Until all customers will change their habit I want to be able to convert that mail to a new ticket. If I simply forward that mail to "support@mycompany.com" then the following happens:

1. Ticket is created for user "myname@mycompany.com", not "customer@customercopmpany.com"
2. Auto-response is sent to "myname@mycompany.com", not "customer@customercopmpany.com"
3. "Fw:" prefix stays in the ticket title

I understand that I can manually create new ticket on behalf of customer and copy/paste original mail content, but I expect a long transition period with a lot of mails sent by existing customers to "myname@mycompany.com" and many other "another_team_members@mycompany.com". Is there a way to [semi-]automate the process of converting those mails to new tickets?

**Comment by guidokuehler** [comment] 2016-11-09 11:26
1. Open the created Ticket in osticket 
2. Change the Owner with the Option-Button (The button is in the same height as the Ticketnumber at the right end of the line) 


Best Regards 
Guido 





Von: "mvidelgauz" <notifications@github.com> 
An: "osTicket/osTicket" <osTicket@noreply.github.com> 
Gesendet: Mittwoch, 9. November 2016 12:17:12 
Betreff: [osTicket/osTicket] Convert e-mail sent not to support address to new ticket (#3488) 



I have e-mail box " support@mycompany.com " monitored by osTicket and it works well. 

The problem is when a customer sends an e-mail to " myname@mycompany.com ". Until all customers will change their habit I want to be able to convert that mail to a new ticket. If I simply forward that mail to " support@mycompany.com " then the following happens: 

    1. Ticket is created for user " myname@mycompany.com ", not " customer@customercopmpany.com " 
    2. Auto-response is sent to " myname@mycompany.com ", not " customer@customercopmpany.com " 
    3. "Fw:" prefix stays in the ticket title 



I understand that I can manually create new ticket on behalf of customer and copy/paste original mail content, but I expect a long transition period with a lot of mails sent by existing customers to " myname@mycompany.com " and many other " another_team_members@mycompany.com ". Is there a way to [semi-]automate the process of converting those mails to new tickets?

**Comment by mvidelgauz** [comment] 2016-11-09 12:09
Thank you Guido for your comment. 
I understand that I can do that. But that means I'll need to do it for each and every mail sent to "myname@mycompany.com". Even more - all other members of our team will have to do manually for all mails sent to "another_team_member@mycompany.com" - including our CEO who claims that he has a lot of other things to do and is used to just forward mails sent to "ceo@mycompany.com" to "some_team_member@mycompany.com". Maximum that I can ask him is to change his habit and use "support@mycompany.com" while forwarding :)
I just thought that at least theoretically mail fetcher could work with original mail sender instead of last forwarder... Or maybe there are other  ways to resolve this problem. For example for redmine there is Outlook plugin that lets me convert any incoming mail to redmine issue - the operation that requires same time and effort as forwarding mail. It even allows to assigned owner of new issue right from Outlook - without the need to switch to redmine webapp and search for that new issue

**Comment by guidokuehler** [comment] 2016-11-09 12:19
Thank you for your Answer and Details! 

Right, i understand. 

Direct Communicatiions between Customers and Company-Peoples produce most any Problems. 
A Recipient have a holiday or others and read not the Emails an so. 
The best way is every when Customers send all to the Support-Email-Address and the ticketsystem assign this automatical to specified teams based on the customer-email or customer-company. 

Best Regards 
Guido 






Von: "mvidelgauz" <notifications@github.com> 
An: "osTicket/osTicket" <osTicket@noreply.github.com> 
CC: "guidokuehler" <guido.kuehler@it-power.biz>, "Comment" <comment@noreply.github.com> 
Gesendet: Mittwoch, 9. November 2016 13:09:23 
Betreff: Re: [osTicket/osTicket] Convert e-mail sent not to support address to new ticket (#3488) 



Thank you Guido for your comment. 
I understand that I can do that. But that means I'll need to do it for each and every mail sent to " myname@mycompany.com ". Even more - all other members of our team will have to do manually for all mails sent to " another_team_member@mycompany.com " - including our CEO who claims that he has a lot of other things to do and is used to just forward mails sent to " ceo@mycompany.com " to " some_team_member@mycompany.com ". Maximum that I can ask him is to change his habit and use " support@mycompany.com " while forwarding :) 
I just thought that at least theoretically mail fetcher could work with original mail sender instead of last forwarder... Or maybe there are other ways to resolve this problem. For example for redmine there is Outlook plugin that lets me convert any incoming mail to redmine issue - the operation that requires same time and effort as forwarding mail. It even allows to assigned owner of new issue right from Outlook - without the need to switch to redmine webapp and search for that new issue

**Comment by ntozier** [comment] 2016-11-09 14:43
One doesn't need a plugin to do this in Outlook.  You can use quick actions.  Directions on how to do this varies of course by version of Outlook but the basic is first add the email for your ticket system to your Outlook. 

In the Quick Step menu, click Create New
![quicksteps](https://cloud.githubusercontent.com/assets/1315768/20141879/60344a5a-a660-11e6-99e3-1ecefe7b4496.png)

This will result in a screen similar to the following:
![editquickstep](https://cloud.githubusercontent.com/assets/1315768/20141932/ab4d4b72-a660-11e6-9818-eec5045493ee.png)

In name Enter something short like “Email to Ticket”
Under Actions select “Copy to Folder”.
Select the “Inbox tickets@yourdomain.com"
Click Add Action
Select “Delete message”
Under Short Cut Key choose “CTRL+SHIFT+1”
In Tooltip text enter something like: 
Copy email to tickets@ INBOX for processing
Delete email afterwards

Click Save.

Now when you get an email that should have been sent to the ticket system or opened as a ticket select it in Outlook 2013 and either click the Email to Ticket button our key press CTRL+SHIFT+1 and the email will be moved to the tickets@yourdomain.com inbox and be picked up the next time support polls for emails.

**Comment by mvidelgauz** [comment] 2016-11-10 11:20
Thank you ntozier for your answer!
Yes I can move an e-mail from my inbox to another one in Outlook if I have delegate rights to that box "tickets@yourdomain.com". But when I access my mails via web app (outlook.office.com/owa) I don't see that "tickets@yourdomain.com" (even though I have delegation rights for that account - I do see it in Outlook)

But even in the Outlook environment, moving an e-mail to that box is only first step. I also want easily and quickly assign ticket to a member (yes I know there are mail filters  in osTicket), assign SLA, et. - this is where a plugin could help. redmine plugin opens a pane where I can make quick changes to the issue before submitting it.

But idea of using quick actions is very good, thank you! (currently while in Outlook I just drag and move mail to "support" inbox)

P.S. I was experimenting with osTicket's mail filters and mail aliases but osTicket mail fetcher seems to disregard mail alias where an e-mail was sent to...

**Comment by mvidelgauz** [comment] 2016-11-10 16:07
ok, Outlook web app also can give me access to another mailbox. But now there still is a scenario when a team member works with mails from their mobile phones. So an ability to just forward mails to a special addresses would help in all cases

**Comment by mvidelgauz** [comment] 2016-11-16 19:10
@ntozier I just tried moving an e-mail from my inbox to tickets@yourdomain.com manually. This mail is not being fetched by osTicket, it is stuck there. Other mails that are sent directly to tickets@yourdomain.com are processed as expected. Do you know what could be a problem? Is it possible that osTicket's fetcher verifies recipient address?
Thank you!

**Comment by ntozier** [comment] 2016-11-16 19:33
I do this all the time on my production machine, so I hope not. :)  Because that would mean when I upgrade I wouldn't be able to do that anymore.

**Closed** 2020-01-06 20:05 UTC
Labels: Email Fetching, Feature Request
