### ISSUE TITLE
[1.9.8.1] Invalid assignee. Must be department member

### ISSUE THREAD

**Issue by Chefkeks** [osTicket/osTicket#2143] opened 2015-06-08 11:32 UTC
Hi guys,

it seems like there is a bug / missing check in 1.9.8.1 when assigning a ticket to a team.

To reproduce:
- A new ticket is created by an user via email / web (shouldn't matter)
- The ticket is routed to the department Support, but not assigned to any agent
- The department manager Bob of dept. Support wants to (re-)assign the ticket to a team (Agents from Support + Sales dept.) and get then the error message "Invalid assignee. Must be department member".

Additional info:
- Department Support is NOT the default department (don't know if that's important, but shall be mentioned)
- The team consists out of all agents from the 2 departments (Support and Sales)
- Bob's primary dept. is Support
- Bob has only access to Support and is member in several teams to work on tickets together with other departments

osTicket info:
osTicket 1.9.8.1
MySQL 5.6.x
PHP 5.6.x
All PHP extensions are OK

Beside there is also a thread over at the forum since that bug was first discovered by another user, just verified it here with our installation and opened the issue report. See the discussion here:
http://osticket.com/forum/discussion/85732/ticket-assignment-to-a-agent-works-but-team-assignment-failing#latest

My guess is that because of the fact that Bob is the dept. manager of dept. Support and dept. Support is not the default dept. some kind of check is not done correctly and osTicket then gives back the error message. Looked at the code but it seems to be fine, but I hope you can reproduce it since "//YOU BREAK IT YOU FIX IT" ;)

Cheers,
Michael

**Comment by ntozier** [comment] 2015-06-08 13:12
Does this exist in 1.10?
If not then I don't know that it will get fixed since we're so close to the next version.

**Comment by Chefkeks** [comment] 2015-06-08 13:31
Hadn't the time yet to test this in 1.10

**Comment by Chefkeks** [comment] 2015-06-24 10:02
The user over at the forum took a quick look at the code and I guess that he's correct with his problem analysis:

First, the code:
Develop or Develop-Next does not seem to matter since it's identical, so here the code from dev-next:
https://github.com/osTicket/osTicket-1.8/blob/develop-next/scp/tickets.php#L176L181

````
elseif ($_POST['assignId'][0]!='s'
                         && $dept->assignMembersOnly()
                         && !$dept->isMember($id)) {
                     $errors['assignId'] = sprintf('%s. %s',
                             __('Invalid assignee'),
                             __('Must be department member'));
````

Second the analysis which seems to be correct I think:
> In the above code while assigning to a team, the code is checking the team ID with the entire staff ID of the department which doesn't match at all and hence giving that error.

@greezybacon 
If I am not mistaken, that's a bug / missing an additional check for team assignment where the agent assigning the ticket is not a department member.

**Comment by greezybacon** [comment] 2015-06-24 12:10
My guess is that `==` was intended

```php
elseif ($_POST['assignId'][0]=='s'
                         && $dept->assignMembersOnly()
                         && !$dept->isMember($id)) {
                     $errors['assignId'] = sprintf('%s. %s',
                             __('Invalid assignee'),
                             __('Must be department member'));
```

**Comment by Chefkeks** [comment] 2015-06-24 12:29
@greezybacon 
Just quickly tested it again with the clone of our live system and it work with ``==``.
So when it's not causing any other false positive matches for that ``elseif`` case (have not tested) I guess that ``==`` is the solution then.

**Comment by jobymathai** [comment] 2015-06-25 10:39
The solution mentioned above has not solved the issue. If you put "==" in the code, then team assignment works but the user can assign ticket to any team of any department. That is "Restrict ticket assignment to department members" check not works. I feel that there should be a separate check for this condition (restricting ticket assignment  strictly to a team whose members are from the same department itself) .

==========

elseif ($_POST['assignId'][0]=='s'
                         && $dept->assignMembersOnly()
                         && !$dept->isMember($id)) {
                     $errors['assignId'] = sprintf('%s. %s',
                             __('Invalid assignee'),
                             __('Must be department member'));
================

**Comment by jobymathai** [comment] 2015-06-25 10:41
Please re-open this issue as it is not fixed.

**Comment by ntozier** [comment] 2015-06-25 12:50
"(restricting ticket assignment strictly to a team whose members are from the same department"

That seems to me to go against the purpose of Teams.  Teams are specifically for crossing departmental lines.  If you wanted to restrict it to a Department of just a few people you could just add another Department.

**Comment by jobymathai** [comment] 2015-06-26 03:51
Our scenario is, we have two or three departments and we are creating teams whose members are specific to one particular department only (ie, creating teams within a department only. Team of one department should not see or  assign ticket to a team of another department). We want to assign tickets of a team of one department to another team of the same department only. It should restrict ticket assignment to a team of other department. In such a case these settings are not working. I know the concept of teams are for sharing tickets between departments but in this scenario, these settings wont work. If possible, could you please consider this scenario and make some provision in the ticketing system to manage these situations.

**Comment by greezybacon** [comment] 2015-06-28 02:56
@jobymathai that sounds like a separate feature request

**Comment by jobymathai** [comment] 2015-06-29 06:28
@greezybacon , Thanks for your updates.  Yes, I think many of us need such a grouping.  Could you please consider this request in your future releases? Anyway I love this application :-)

**Comment by Chefkeks** [comment] 2015-06-29 06:40
Maybe the upcoming sub-departments feature is already a step in that direction?!

**Comment by markus4000** [comment] 2015-06-29 11:24
Department-Transfer should have a optional checkbox: unassign team
Teamtransfer should have a optional checkbox: unassign assignee

**Comment by greezybacon** [comment] 2015-06-29 14:23
I like the suggestion by @markus4000. I think it would be rather elegant that way

**Comment by jobymathai** [comment] 2015-06-30 06:54
I  think, there shoud be a team-department mapping option just like agent -team  mapping option. So we can restrict team membership from the selected departments only.

**Comment by markus4000** [comment] 2015-07-01 20:16
I think the really good thing about teams is, that members dont have to be i  the same department.
So i woudn't map a team to a department.

**Comment by markus4000** [comment] 2015-07-01 20:19
@greezybacon won't you reopen this issue? I'd love to have the enhancement of the checkbox ;-)

**Comment by deon42** [comment] 2018-02-06 11:52
I'm still new with osTicket.

We are using osTicket v1.10.1.

I'm attempting to limit who tickets can be assigned to. 

I have help topics created at top level and assigned to departments.

The agents are created with expanded access to their department only.

When a new ticked to created and the topic and department selected, all the agents appear and not just the 1 or two agents how has been given access to that department.

Advice would be greatly appreciated.

**Closed** 2020-01-06 20:14 UTC
