### ISSUE TITLE
1.10RC3 Due date on tasks is lost after saving - 000 in table

### ISSUE THREAD

**Issue by jjjeroenski** [osTicket/osTicket#3324] opened 2016-08-26 08:00 UTC
While testing version 1.10RC3 found that due date for tasks is always empty.
If you finish the task form and saved it's empty.
Checked mysql table 'ost_task' there is always '0000-00-00 00:00:00'

Also, if you edit the task afterwards, you can't edit the due date, field not available.  (but this is already posted)

I also agree with the other task features in post 
https://github.com/osTicket/osTicket/issues/3287

**Comment by ntozier** [comment] 2016-08-26 14:14
This sounds like it might be a duplicate of:
https://github.com/osTicket/osTicket/issues/2799

**Comment by jjjeroenski** [comment] 2016-08-26 14:36
Damn, 
Indeed duplicate, sorry.

**Comment by ntozier** [comment] 2016-08-26 14:43
No worries.  Please close this and comment on the other one. :)

**Closed** 2016-08-29 07:02 UTC
