### ISSUE TITLE
Bootstrap missing

### ISSUE THREAD

**Issue by ccsalway** [osTicket/osTicket#4322] opened 2018-06-20 14:05 UTC
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [ ] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported? - bug exists but is still happening.

### Description
Fresh LAMP server. did a git clone and then ran php manage.php with the following error

php manage.php deploy --setup /opt/bitnami/apache2/htdocs/osticket
PHP Warning:  include(/opt/bitnami/apache2/htdocs/osticket//bootstrap.php): failed to open stream: No such file or directory in - on line 2
PHP Warning:  include(): Failed opening '/opt/bitnami/apache2/htdocs/osticket//bootstrap.php' for inclusion (include_path='.:/opt/bitnami/php/lib/php:/opt/bitnami/frameworks/smarty/libs') in - on line 2
PHP Notice:  Use of undefined constant INCLUDE_DIR - assumed 'INCLUDE_DIR' in - on line 3

Then when I try to run osTicket, in the apache error_log, I get

[Wed Jun 20 13:58:48.678249 2018] [proxy_fcgi:error] [pid 11358:tid 140454683076352] [client 148.252.225.26:38431] AH01071: Got error 'PHP message: PHP Fatal error:  Class 'Bootstrap' not found in /opt/bitnami/apache2/htdocs/main.inc.php on line 24\n'

**Comment by JediKev** [comment] 2018-07-09 21:00
@ccsalway 

This should address the issue:
https://github.com/osTicket/osTicket/pull/4332

Cheers.

**Comment by matt-gnu** [comment] 2018-07-23 13:49
sorry, this breaks `php manage.php deploy -v -f -C /path/to/existing/dest/` here.
manage.php tries to include /bootstrap.php, since $this->source seems to be undefined by some circumstances.

This leads to a directory named INCLUDE_DIR to be created.
btw: this seems to be related to #3741

**Comment by perryk** [comment] 2018-07-24 11:18
I can confirm I have the same troubles since this was merged, sorry I've been a little behind in testing everything myself and in reporting this.

I can reproduce this with the following workflow:

Create an empty directory for the deployed files to go such as /var/www/html/osticket
Change the owner & group of this directory to the user I'm running as.
Download latest code in my own users directory:  git clone https://github.com/osTicket/osTicket    (then cd into Osticket)
Change to v1.10.4 tag:  git checkout v1.10.4
Try to deploy into the empty directory: ./manage deploy /var/www/html/osticket

The first time the command is run, no errors are shown and the deploy happens perfectly.

The second time the command is run, it gives PHP errors:

PHP Warning:  include(/bootstrap.php): failed to open stream: No such file or directory in - on line 2
PHP Warning:  include(): Failed opening '/bootstrap.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in - on line 2
PHP Notice:  Use of undefined constant INCLUDE_DIR - assumed 'INCLUDE_DIR' in - on line 3

Additionally, it created a new directory called INCLUDE_DIR which has a copy of the "include" directory of the looks.

Also, this entirely breaks the website, just a blank page is shown, and the webserver logs a fatal PHP error:
PHP Fatal error:  require(): Failed opening required 'INCLUDE_DIR/class.osticket.php' (include_path='./:INCLUDE_DIR/:INCLUDE_DIR/pear/') in /var/www/html/osticket/bootstrap.php on line 331, referer: http://osticket-dev.qbi.uq.edu.au/index.php

If I compare a bootstrap.php file from a working install and one broken in this manner you can see the variable "INCLUDE_DIR" is defined to be that newly created directory. This is on line 306 from bootstrap.php for me.

When broken:
define('INCLUDE_DIR', 'INCLUDE_DIR/'); // Set by installer

When working:
define('INCLUDE_DIR', ROOT_DIR . 'include/'); // Set by installer

The third time a "manage deploy" is run, the extra created directory called "INCLUDE_DIR" is copied to the deployed directory.

Now the website is still broken however instead of a blank page it says: "Error loading settings. Contact admin."

I understand that directory isn't mean to exist, I thought I'd just give some of the different error messages incase someone runs into the problem at a different stage.

@matt-gnu The fix for me now is relatively easy, just revert the commit

git revert ee208fca8a72b437dcd392de2c463a459e83ccea --no-edit


I'm using Centos 7 and PHP 5.6 btw.

**Comment by JediKev** [comment] 2018-07-24 22:08
@perryk @matt-gnu 

Here you guys go 😁:
https://github.com/osTicket/osTicket/pull/4363

Cheers.

**Closed** 2020-01-06 20:00 UTC
