### ISSUE TITLE
DB Error #1062

### ISSUE THREAD

**Issue by danielc1234** [osTicket/osTicket#3193] opened 2016-06-09 17:11 UTC
So we are getting more and more of these errors. Trying to figure out what is going on. We have the latest version.
Any ideas would be greatly appreciated.

[INSERT INTO `ost_attachment` SET `type` = 'H', `file_id` = 446, `inline` = 1]

Duplicate entry '0-446-H' for key 'file-type'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3095): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(589): MySqlExecutor->execute()<br />
#3 (root)/include/class.thread.php(993): VerySimpleModel->save()<br />
#4 (root)/include/class.thread.php(1001): ThreadEntry->saveAttachment(Array, 0)<br />
#5 (root)/include/class.thread.php(1440): ThreadEntry->saveAttachments(Array)<br />
#6 (root)/include/class.thread.php(1448): ThreadEntry::create(Array)<br />
#7 (root)/include/class.thread.php(2299): ThreadEntry::add(Array)<br />
#8 (root)/include/class.thread.php(2516): MessageThreadEntry::add(Array, Array)<br />
#9 (root)/include/class.ticket.php(2297): ObjectThread->addMessage(Array, Array)<br />
#10 (root)/include/class.ticket.php(2665): Ticket->postMessage(Array, 'Email')<br />
#11 (root)/include/class.thread.php(408): Ticket->postThreadEntry('M', Array)<br />
#12 (root)/include/class.thread.php(648): Thread->postEmail(Array, Object(ThreadEntry))<br />
#13 (root)/include/class.mailfetch.php(775): ThreadEntry->postEmail(Array)<br />
#14 (root)/include/class.mailfetch.php(844): MailFetcher->createTicket(1)<br />
#15 (root)/include/class.mailfetch.php(924): MailFetcher->fetchEmails()<br />
#16 (root)/include/class.cron.php(25): MailFetcher::run()<br />
#17 (root)/include/class.cron.php(100): Cron::MailFetcher()<br />
#18 (root)/include/api.cron.php(19): Cron::run()<br />
#19 (root)/include/api.cron.php(12): CronApiController->run()<br />
#20 (root)/include/class.dispatcher.php(145): CronApiController->execute()<br />
#21 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('cron', Array)<br />
#22 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('cron', Array)<br />
#23 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/tasks/cron', NULL)<br />
#24 (root)/api/http.php(35): Dispatcher->resolve('/tasks/cron')<br />
#25 {main}

**Comment by greezybacon** [comment] 2016-06-20 20:31
@danielc1234 I've seen this before. What version of osTicket are you running?

**Comment by danielc1234** [comment] 2016-06-20 20:35
@greezybacon   

Hi, it is version osTicket (v1.10-rc.2-325-ge231550)

**Comment by greezybacon** [comment] 2016-06-20 20:57
@danielc1234 would you mind upgrading to the v1.10-rc.3 release and see if it addresses this issue? I believe this was fixed in 00a1371dcb52f72bfdaee946f298962274706398, which is after that version code (https://github.com/osTicket/osTicket/compare/e231550...develop)

**Comment by danielc1234** [comment] 2016-06-20 21:06
@greezybacon   Is there a way to tell me which files were updated in that release? I had a lot of work done for the software to work with PHP7, so I do not want to over write those files. And I don't think the modifications are causing the issue.

**Comment by greezybacon** [comment] 2016-06-20 21:14
@danielc1234 you can apply a patch of that [one commit](https://github.com/osTicket/osTicket/commit/00a1371dcb52f72bfdaee946f298962274706398.patch) or [everything in between](https://github.com/osTicket/osTicket/compare/e231550...develop.patch). However, the `develop` branch works on PHP7. You might try it out vanilla and report any issues you encounter.

**Comment by danielc1234** [comment] 2016-06-20 21:31
@greezybacon   Ahhh, you know we can no longer attach files to threads or send attachments. I wonder if that has something to do with the error?

**Comment by danielc1234** [comment] 2016-06-20 21:33
@greezybacon   Also, so if I downloaded the develop branch, I should not have an issue at all with PHP7? A little concerned I might blow something up. :)

**Comment by greezybacon** [comment] 2016-06-21 15:49
@danielc1234 it's really hard for me to assist if you're nervous about making any changes. I think you should make a copy of your osTicket installation and database. Apply some changes, whatever they are, to the copy, and retest your issues. If there are adverse effects, then you can raise them and we can work through your remaining issues. 

When your confident no adverse effects exist, then apply the same changes to your production system.

**Comment by danielc1234** [comment] 2016-06-21 18:15
@greezybacon 

Okay, so I'm on osTicket (v1.10-rc.3) now and osticket is throwing these errors when I try to send an email. You had mentioned that this version is compatible with PHP7?

The errors I am getting is this:
 Mailer Error
Unable to email via php mail function:"Customers Name" mail() returned failure
Log Date: 06/21/2016 02:11:13 PM IP Address: 75.149.###.###
 Mailer Error
Unable to email via SMTP:mail.oursite.com:25 [helpdesk@oursite.com] Failed to set sender: helpdesk@oursite.com [SMTP: Invalid response code received from server (code: -1, response: )]
Log Date: 06/21/2016 02:11:13 PM IP Address: 75.149.###.###

Please, do you have any ideas?

**Comment by greezybacon** [comment] 2016-06-21 18:28
Did you sanitize the `oursite.com` part of the messages?

**Comment by danielc1234** [comment] 2016-06-21 18:30
@greezybacon 
Yes I did, that is the server site that osticket is on. I just didnt want the site shown.

**Comment by danielc1234** [comment] 2016-06-21 18:30
Unless you need to see it.

**Comment by greezybacon** [comment] 2016-06-21 18:50
@danielc1234 all I can see from your message is that sending an email through your mail server failed. I have no idea why it would have. Is there more to the message? Did you mail server have a message. Looks like a TLS error. Do you need to check a box somewhere? Or use `ssl://mail.oursite.com` for the hostname?

**Comment by danielc1234** [comment] 2016-06-21 19:09
@greezybacon 
I seem to remember that this happened before on an earlier version, but one of our IT guys was able to fix it. I just asked him about it and this is what he said....

> I had to make it use some different ports for sending because their tls implementation is broken

I'm not sure if that gives you any more of a clue or not. I do not see anything in the mail logs, etc.

**Comment by danielc1234** [comment] 2016-06-21 19:13
This is in the site's apache log files. Not sure if it is related.

[Tue Jun 21 19:07:38.044927 2016] [:error] [pid 14319:tid 140535910078208] [client 75.149.###.###:51924] FastCGI: server "/usr/lib/cgi-bin/php7.0-fcgi" stderr: PHP message: PHP Warning:  Declaration of AssignmentForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/oursite.com/include/class.forms.php on line 4146, referer: http://helpdesk.oursite.com/scp/tickets.php?status=open
[Tue Jun 21 19:07:38.045004 2016] [:error] [pid 14319:tid 140535910078208] [client 75.149.###.###:51924] FastCGI: server "/usr/lib/cgi-bin/php7.0-fcgi" stderr: PHP message: PHP Warning:  Declaration of TransferForm::render($options) should be compatible with Form::render($staff = true, $title = false, $options = Array) in /var/www/oursite.com/include/class.forms.php on line 4266, referer: http://helpdesk.oursite.com/scp/tickets.php?status=open

**Comment by greezybacon** [comment] 2016-06-21 19:49
@danielc1234 yes, those are the two remaining issues for full PHP7 compatibility. Shouldn't prevent mail from sending though

**Comment by danielc1234** [comment] 2016-06-21 19:55
@greezybacon 
Is there any validity to what the IT guy was saying? Is there something I can look into or settings in osticket to test this?

> I had to make it use some different ports for sending because their tls implementation is broken

**Comment by greezybacon** [comment] 2016-06-21 19:57
Whose TLS implementation is broken? If you mean osTicket, we don't have a TLS implementation. We use PHP, which uses openssl. Perhaps you should upgrade? I really doubt the TLS implementation in PHP7 is broken.

**Comment by danielc1234** [comment] 2016-06-21 20:53
@greezybacon 

So you are saying it is a server issue not osticket? I tried to change to another SMTP email client in osticket and get this error when trying to save.

authentication failure [SMTP: STARTTLS failed (code: 220, response: 2.0.0 Ready to start TLS)]

I'm sorry I cannot be better at describing the issue, I have limited knowledge with servers.

**Comment by robintoy** [comment] 2016-06-21 20:59
If you are using a hosting provider they normally provide a local host SMTP server for emails, but if you are a little more advanced / split system like we have you will need to look at different ports for SMTP traffic.

If like us you are hosting witha third party company but want to send and receive emails via your Exchange server or something else you will need to look at enabling SMTP port 587 as host hosting providers block the standard SMTP port 25 leaving their networks from web servers due to spam and other protection reasons.

Hopefully this information is a little useful

**Comment by greezybacon** [comment] 2016-06-21 21:30
@danielc1234 maybe try SMTP on port 587, or 465? Using the other port number solves the issue often

**Comment by danielc1234** [comment] 2016-06-21 21:34
I found this solution on the internet that seems to work. The only issue now is when we attach an image or file, it will send a duplicate of the attachment to the customer.
http://vidagnu.blogspot.com/2016/02/osticket-error-smtp-starttls-failed.html
Beyond that, it seems to be working, but still testing.

**Comment by greezybacon** [comment] 2016-06-21 21:56
@danielc1234 so, about that. We upgraded the Net/SMTP.php shipped with osTicket v1.10-rc.3 so that this edit is no longer necessary. Are you still using some old version of osTicket? or manually keeping an edited file around? The `_socket_options` variable is not used anywhere in the current Net/SMTP.php script.

**Comment by danielc1234** [comment] 2016-06-21 22:22
@greezybacon I'm not sure. I thought I had downloaded the v1.10-rc.3 and ftp'd the files over to the server. It is showing that version number in the admin. How can I download the absolute latest version? When I ticked on the develop brand and hit download, it gave me the 1.8 version.
Do you have a link to the latest version that I can ftp over?
Thanks for all your help by the way.

**Comment by msigley** [comment] 2017-01-25 17:48
I tracked down this issue. It is caused by a difference in behavior in MariaDB vs MySQL.

It can be fixed by setting the "OLD_MODE" SQL system variable to "NO_DUP_KEY_WARNINGS_WITH_IGNORE" on the mysqli connection.

Changes to /include/mysqli.php (around line 71):
```php
//set desired encoding just in case mysql charset is not UTF-8 - Thanks to FreshMedia
    @db_set_all(array(
        'NAMES'                 => 'utf8',
        'CHARACTER SET'         => 'utf8',
        'COLLATION_CONNECTION'  => 'utf8_general_ci',
        'SQL_MODE'              => '',
		'OLD_MODE'				=> 'NO_DUP_KEY_WARNINGS_WITH_IGNORE'
    ), 'session');
```

**Comment by Chefkeks** [comment] 2017-01-25 18:15
@msigley
You should consider to make a pull request, so the devs can review and merge easily ;)

**Comment by msigley** [comment] 2017-01-25 18:32
@chefkeks I am stretched six ways from Sunday at the office here and don't have time to setup a proper PR unfortunately.

**Closed** 2020-01-06 20:07 UTC
