### ISSUE TITLE
Task Overdue

### ISSUE THREAD

**Issue by azebary** [osTicket/osTicket#3745] opened 2017-03-15 08:30 UTC
In Short

I'm NOT getting a notification on task overdue, i'm using OSTicket 1.10 & the checkbox in the Alerts & Notices are selected.

Thanks

![untitled](https://cloud.githubusercontent.com/assets/26429499/23939635/b7660c3a-0972-11e7-83c2-a8b42a171602.png)

**Comment by ntozier** [comment] 2017-03-15 14:31
All other emails are working?
version of PHP?
How are you sending mail (PHPMailer or SMTP)?

**Comment by azebary** [comment] 2017-03-16 06:16
Thank you ntozier for your reply,

All notifications are working & i'm receiving emails for NEW Ticket, Ticket Overdue & New Task only but when the task became overdue the system is not sending the notification, As for which PHP version i'm using, it's PHP v5.6 with phpMyAdmin & for the mail setup, i have an exchange mail server 2010 & i'm using the exchange setup instead of the SMTP & the POP3 ones, please see the attached

But for more details about how I am configuring the OSTicket system

01 - I'm using LDAP & HTTP plugins.
02 - Every user under my domain is able to login into the OSTicket as an agent.

I feel the problem in the Task module where something is missing in the coding, what do you think?

![email setup](https://cloud.githubusercontent.com/assets/26429499/23983938/e2424bf2-0a27-11e7-9962-2f71b2e6c579.png)

**Comment by azebary** [comment] 2017-03-19 06:24
Hi

Do you advise me to re-install the OSTicket? What are the recommended PHP & MYSQL version to use in this regard? Windows server as well?

**Comment by mfelber** [comment] 2017-03-19 18:34
This issue report seems to be a duplicate of this one: https://github.com/osTicket/osTicket/issues/3491

It was labelled as bug from the developers so I think they are aware of this issue..

**Comment by PeopleInside** [comment] 2017-06-09 13:41
I had the same issue. PHP 7.1 Osticket version: v1.10

**Comment by jnko** [comment] 2017-08-09 10:55
Well, digging into the code include/class.cron.php does have a "TicketMonitor" but nothing similar for Tasks.

`   function TicketMonitor() {
        require_once(INCLUDE_DIR.'class.ticket.php');
        Ticket::checkOverdue(); //Make stale tickets overdue
        // Cleanup any expired locks
        require_once(INCLUDE_DIR.'class.lock.php');
        Lock::cleanup();
    }
`

Looking a little bit deeper into class.ticket.php and class.task.php there's also nothing to be compared with checkOverdue function in class.task.php

Looks like it has just not been implemented unfortunately...

**Comment by ntozier** [comment] 2017-08-09 14:35
this appears to be a dupe of https://github.com/osTicket/osTicket/issues/3407

**Comment by zaphod13** [comment] 2018-05-11 23:29
digging a bit into the code and the database, I agree with @jnko as there are no functions in class.task.php for dealing with overdue tasks, and there is no field in the ost_task database table for the overdue status for tasks.  It appears that overdue task notification is not an implemented feature

**Comment by zaphod13** [comment] 2018-09-07 16:33
I am not much of a developer, but I managed to go into the code and added in functionality to do notification on past due tasks.  This relies on the scheduled cron job that runs periodically.  We also wanted the system to "nag" people of overdue tickets and tasks, so it is set to notify of any overdue tasks every night at 3am-ish.  Attached are the modified class files for tasks, tickets, and cron to accomplish this. They are based on the 1.10.1 version, and I make no guarantees about how it may work in your environment, but it is working well for us.

[updated-class-files.zip](https://github.com/osTicket/osTicket/files/2361789/updated-class-files.zip)

**Closed** 2020-01-06 20:04 UTC
