### ISSUE TITLE
1.10 Issue - System message for Transfer on Task

### ISSUE THREAD

**Issue by jdelhome3578** [osTicket/osTicket#2340] opened 2015-07-31 12:38 UTC
`Bob transferred this to None`

![image](https://cloud.githubusercontent.com/assets/5774055/9007461/7adaaa82-375f-11e5-83e5-e9e04c34c6bd.png)

**Comment by ntozier** [comment] 2015-07-31 13:48
I cannot reproduce this one.
Please provide steps on how you did this.

**Comment by jdelhome3578** [comment] 2015-07-31 13:50
This was produced on a task when transferring from one dept to another

**Comment by ntozier** [comment] 2015-07-31 14:03
Still unable to reproduce, but my tasks page doesn't look anything like your screen shot.
Was there a fix released for the css formating issue on task pages (that I obv missed)?

**Comment by jdelhome3578** [comment] 2015-07-31 15:27
I don't believe I added an mods from pull request. What does your screen look like?

**Comment by ntozier** [comment] 2015-07-31 16:01
It looks like there is no css formatting.

**Comment by greezybacon** [comment] 2015-08-03 02:33
Is the name of your department "None"?

**Comment by jdelhome3578** [comment] 2015-08-03 12:00
I have the three default Maintenance, Sales, Support

**Comment by jdelhome3578** [comment] 2015-08-12 16:27
Tested again from the tip of develop-next, still seeing the issue.

**Comment by greezybacon** [comment] 2015-08-12 16:56
Did you maybe delete the department it was transferred to?

Am Mittwoch, 12. August 2015 schrieb jdelhome3578 :

**Comment by jdelhome3578** [comment] 2015-08-12 17:39
With a clean install, I create a task under maintenance and transfer it to support I receive the message `transferred this to None`.

**Comment by jdelhome3578** [comment] 2015-08-19 13:09
@greezybacon database entry for transfer has all `0`

![image](https://cloud.githubusercontent.com/assets/5774055/9356847/97f63dce-4651-11e5-8535-9988bf322e52.png)

**Comment by jdelhome3578** [comment] 2016-01-20 13:56
@greezybacon @protich this is still an issue from tip develop-next

**Comment by jdelhome3578** [comment] 2016-02-09 16:50
@greezybacon @protich this is still an issue from tip develop-next

**Comment by jdelhome3578** [comment] 2016-02-09 17:05
@greezybacon @protich
Image from `_thread_event` table. Please note that the ticket transfer is fine but the task transfer has a `0` for `staff_id`, `dept_id`, `topic_id`.

![image](https://cloud.githubusercontent.com/assets/5774055/12923793/0be487f2-cf25-11e5-98ff-5b14dfa0debb.png)

**Closed** 2020-01-06 20:13 UTC
