### ISSUE TITLE
Validations on forms not permit "0" as value

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#1996] opened 2015-04-27 15:07 UTC
the vahabior of validation on custom forms does not permit input a value of "0" (zero) , in osticket 1.9.4 or 1.9.5..

the realproblem its that i choose no validate any in the input field that i added and when goes to the ticket system and create a ticket , fill all input fields (including the custon field created without validation) , so then when click to create and save the ticket still marks that the fields that i already made custom and put "0" (zero) as value said required and cannot create any ticket

the custom input fiel has size 40 and max ling 50, validation none.. with those parameters when i input "0" raised a error, but for any other value does work..  
i thin this its incorrect due 1 or 0 are both values that i marked to do not validate

**Comment by mckaygerhard** [comment] 2015-04-27 15:08
attached screenshot error:

![validation-error](https://cloud.githubusercontent.com/assets/1571724/7350495/6fcbc1ca-ecc9-11e4-9896-898b96a69d55.png)

**Comment by greezybacon** [comment] 2015-04-28 20:41
I will add that this only shows up if the field is required. For optional fields, the data is correctly saved in the database.

**Comment by mckaygerhard** [comment] 2015-04-29 13:58
currently its happened for optional filed also, the input field "validacion_generica" has the value of O uppercase and with that i workaround in my production deploy

**Comment by mckaygerhard** [comment] 2015-05-18 17:41
ping? how's the progress?

**Comment by mckaygerhard** [comment] 2015-08-31 16:07
again , ping? can i help if gimme a tip! i search at the class.ticket.php and i cannot find nothing related

I clarify: i reported this on 1.9 series not in 1.10 "featured" due this its a bug not a feature request ..

**Comment by mckaygerhard** [comment] 2015-09-09 13:17
again ping? forms still in 1.9.12 has this bug! put 0 in numeric validation with 0 permited and get and error!

**Comment by mckaygerhard** [comment] 2016-05-28 16:26
still i cannot put zero values in fields, only numbers >0 or aphabeticall chars!

again i got ping and real problems are not solved seems.... this bug also still happened IN STABLE VERSIN, where are the support collaboration..

and if i produce a pull request, sure will not be commitd due are not good or not follow code standars, i made some contributions and still are not inludeds!

**Comment by greezybacon** [comment] 2016-06-25 13:46
@mckaygerhard could you try the patch in the second commit of #3239 to see if it addresses this issue?

**Comment by mckaygerhard** [comment] 2016-06-26 00:27
i'll try it in the night at monday, and post feedback here! as i posted in another i'm very busy at my job, i'll promise i'll ried and post feedback here

**Comment by mckaygerhard** [comment] 2017-11-22 00:10
i forgot to comment here, the pull commit #3239 in the commits 698197f58d306ccf3f014ef3c61ef8e68d459084#r152437551 solves the situation, but i'll not close this due i not confirmed are merged the pull

**Comment by mckaygerhard** [comment] 2018-05-08 12:25
Wow! osticket now are in 1.10 and this BUG! never was resolved in 1.9 among 4 years! 
i imagine that those bugs in 1.10 will not be fixed too until 1.11 are in unstable! interesting support team!

thanks in any case!

**Comment by mckaygerhard** [comment] 2020-01-06 20:25
wow lot of tickets closed but no references of solution.. great!

**Comment by robintoy** [comment] 2020-01-06 20:27
And not a single one fixed, just closing to make themselves look good and piss people off with mass crap and high load on spam filters

**Comment by JediKev** [comment] 2020-01-06 20:31
@robintoy @mckaygerhard
 
These were closed due to them being older than 2019 and not updated since 2019. If this is still an issue please reopen.

Cheers.

**Comment by mckaygerhard** [comment] 2020-01-06 20:32
@JediKev  obviously this are still an issue! but seems osticket are in a running "upgrades and updates" plan.. with no fixeds, so reopened, i'm using 1.10 due i cannot upgraded due how nany "holes" will introduced 1.11 ? or 1.12?

**Comment by robintoy** [comment] 2020-01-06 20:37
Loving how my comments are being deleted!!

Why not stop wasting all our time and fix the issues and implement promised features like the time tracking mod I wrote which gets 1000's of download a month

**Comment by mckaygerhard** [comment] 2020-01-06 20:38
@robintoy  has right .. @JediKev  .. a comment deleted only demostrated a hint!

**Comment by JediKev** [comment] 2020-01-06 20:39
@mckaygerhard @robintoy 

I deleted a comment because it was very rude and should not have been posted.

Cheers.

**Comment by mckaygerhard** [comment] 2020-01-06 20:40
but @JediKev  what do you xpected if lot of people only see new versions and no fixeds! puff

**Comment by JediKev** [comment] 2020-01-06 20:41
@mckaygerhard 

There are fixes....read the release notes. We can't cover every issue in every release mate.

Cheers.

**Comment by mckaygerhard** [comment] 2020-01-06 20:42
do you mean that "0" it's not valid value!!!! @JediKev °!!!! AH! HOWLY CRAP! @robintoy ! that's something new X-D

**Comment by protich** [comment] 2020-01-06 20:42
@mckaygerhard - What have you fixed lately?

**Comment by mckaygerhard** [comment] 2020-01-06 20:43
hello @protich  due we are all busy we only not used some validations.. and so we cannot use those in forms.. that's the problem.. do you read carefully the issue history? i have paste images of deleted coments since 2010

**Comment by protich** [comment] 2020-01-06 20:44
We made a decision to close old issues as some were outdated - if the issue is still valid then simply reopen it and stop being an arse. No one works for you!

**Comment by robintoy** [comment] 2020-01-06 20:45
> @robintoy has right .. @JediKev .. a comment deleted only demostrated a hint!

I did write three rude ones in anger via my phone before our server gave up receiving which has now caused other issues!

Stop this mass close with no reason rubbish, delete and do not spam!

**Comment by mckaygerhard** [comment] 2020-01-06 20:46
> We made a decision to close old issues as some were outdated - if the issue is still valid then simply reopen it and stop being an arse. No one works for you!

@protich  seems you not know that i cannot reopen issued closed by developers.. as via dictatorshid way!

**Comment by JediKev** [comment] 2020-01-06 20:47
@robintoy 

You cannot batch close with a response unless you use a bot which I'm not willing to do.

@mckaygerhard 

That's not how it works man. I'll re-open for you.

Cheers.

**Comment by protich** [comment] 2020-01-06 20:48
@robintoy - You subscribed to notifications - you can mute them or simply unfollow the repo.

@mckaygerhard - polite request to reopen it helps both parties. Once again, what have you contributed lately to osTicket?

**Comment by mckaygerhard** [comment] 2020-01-06 20:52
i postedin many other repos about that problems.. specially in https://github.com/clonemeagain/attachment_preview due here was impossible.. so @protich   i suggest be more open to issues and less open to "new versioned features"

**Comment by robintoy** [comment] 2020-01-06 20:52
Hi @protich 

being honest not sure why I'm on so many.
I have fed back a bit and wrote a time mod which was said by your team they would take on and make official but never did (extreme shame as we have 1000's of download a month) and a reason I have left the project and keep dipping in on here now and then to keep up with it.

I'm looking at my settings and hopefully will get it sorted but still I have looked at it is nearly 1000 emails I have received from this in the space of 20 minutes at best

**Comment by JediKev** [comment] 2020-01-06 20:53
> I'm looking at my settings and hopefully will get it sorted but still I have looked at it is nearly 1000 emails I have received from this in the space of 20 minutes at best

Because I batch closed over 1,000 issues in under 20 minutes..

**Comment by mckaygerhard** [comment] 2020-01-06 20:54
oh.. for sure as @robintoy said..  +1

> @mckaygerhard - polite request to reopen it helps both parties. Once again, what have you contributed lately to osTicket?

i forced to contributed in forks and other repos  about that problems.. specially in https://github.com/clonemeagain/attachment_preview due here in oficial repo was impossible.. **so @protich i suggest be more open to issues and less open to "new versioned features"**

**Comment by protich** [comment] 2020-01-06 21:06
The shame here is we are doing cleanup **because** we want to stay engaged with the community in 2020 - review issues & PR and also publicly post our roadmap.

**Comment by mckaygerhard** [comment] 2020-01-06 21:52
now @protich commented in pull - #5311 for this.. currently sorry for you guys but i'm using php 5.3 and 1.9.X -- the 1.10 to 1.12 only has some setups with few tests.. not production ready

**Comment by ntozier** [comment] 2020-01-06 22:02
@mckaygerhard 
PHP 5.3 is end of life, and has been for over 5 years.
osTicket 1.9 is end of life, and has been for almost a year.

**Comment by JediKev** [comment] 2020-01-06 22:06
@mckaygerhard 

>the 1.10 to 1.12 only has some setups with few tests.. not production ready

This statement is entirely incorrect. Any release not labeled with `-rcX` (or Release Candidate) is production ready and has been tested countless times. Many MANY people use v1.12 and above in production with no issues (not v1.10 as that has reached EOL as well). Sounds like your particular setup has a few issues which could be in part due to your PHP version and setup.

Cheers.

**Comment by vegnuli** [comment] 2020-01-07 19:33
sorry for my comment guys but... interesting.. 10 years later @protich  sais "we want to stay engaged with the community in 2020 - review issues & PR and also publicly post our roadmap" .. pufff so so late right? now how many years we must waith for results? in that momento 1.9 was stable! now are 1.14.. so..

**Comment by mckaygerhard** [comment] 2020-01-07 19:44
> Sounds like your particular setup has a few issues which could be in part due to your PHP version and setup.

my "particular setup" are fine! but well that demostrates that there's no dessire to receive code from community, i have a already patched and working perfectly osticket.. normal setup are not working!.. i was commented as collaboration to the HUGE request on forums

**Comment by JediKev** [comment] 2020-02-26 22:27
Addressed with:
- #5311

**Closed by JediKev** 2020-02-26 22:27 UTC
Labels: Forms - Customer, bug
