### ISSUE TITLE
after ticket assign to agent if we transfer ticket to other department, ticket transfer alert mail are not getting by that department.

### ISSUE THREAD

**Issue by bdharmesh3** [osTicket/osTicket#5115] opened 2019-10-18 13:15 UTC
Hi All,

We have recently install Osticket v1.12.2, it is working fine, but when we assign the ticket to an agent and that agent transfer that ticket to another department. that department member not get transferred alert. 

Eg: suppose 001 ticket assign to agent X, and Agent X transferred that to Department A, but all members of Department A not getting mail alert. 

kindly find os ticket version detail below.

![2019-10-18 18_36_35-Window](https://user-images.githubusercontent.com/42741889/67097200-3f134180-f1d7-11e9-8333-0dd49f93e383.png)

**Comment by ntozier** [comment] 2019-10-18 13:23
Please upgrade to current and try again.

IS the Ticket Transfer Alert enabled? Admin panel -> Settings -> Tickets -> Alerts and Notices.
How is your email configured? Admin panel -> Emails -> Emails -> your email.
What is your Default MTA set to? Admin panel -> Emails -> Settings.

**Comment by bdharmesh3** [comment] 2019-10-21 10:03
Hi ntozier,

kindly find your question answer below.
1) IS the Ticket Transfer Alert enabled? Admin panel -> Settings -> Tickets -> Alerts and Notices.
ans : Yes 

2) How is your email configured? Admin panel -> Emails -> Emails -> your email.
ans: Email configuration is working fine as when we create ticket will get alert to all team members if the ticket is not assigned to anyone and transfer to other department at that time all department members get the transfer alert mail.

3) What is your Default MTA set to? Admin panel -> Emails -> Settings.
ans: yes its configured and default one is the same as we set up for mail fetching. 

Kindly find below snap for your reference. 

![2019-10-21 15_29_04-](https://user-images.githubusercontent.com/42741889/67196247-0f9f4780-f418-11e9-9744-f03e8a2162b5.png)

**Comment by JediKev** [comment] 2019-10-21 13:50
@bdharmesh3 

This is by design...if a ticket is Assigned and you have `Assigned Agent / Team` Enabled for the Transfer alert (which you do), then the alert will go to the Assignee and not the Department Members. See here:
- https://github.com/osTicket/osTicket/blob/develop-next/include/class.ticket.php#L2651-L2665

Cheers.

**Comment by JediKev** [comment] 2019-10-21 13:51
@bdharmesh3 

Since this is not actually an issue, rather is as designed, I will close this report.

Cheers.

**Closed as completed by JediKev** 2019-10-21 13:51 UTC
