### ISSUE TITLE
Errors in log after upgrade

### ISSUE THREAD

**Issue by mehargags** [osTicket/osTicket#5314] opened 2020-01-04 10:31 UTC
I recently upgraded a 6-7 years old OS Ticket install to version  v1.14.1 Released November 21, 2019 so as to run it on PHP to v7.3.

Everything seems fine...however I see this nasty "warning" in log every few seconds and the apache log grows to about 500MB per day. 

`PHP Warning:  file_exists(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/home/acaws.georgiatc.com:/home/admin/tmp) in /home/acaws.georgiatc.com/public_html/include/mpdf/vendor/mpdf/mpdf/src/Cache.php on line 26, referer: https://xxxx/scp/tickets.php?id=17227`

so as the error suggests... something is trying to access in"/" which obviously is not alllowed in my basedir settings. I see in the in `/include/ost-config.php` root path setting which is commented, should i just set it as below:

`define('ROOT_PATH', '/home/acaws.georgiatc.com/public_html/');`
which is the absolute path of my site root ?

I'm a sysadmin and not a dev... so if someone can point me how to clear up this dreaded warning from occurring in the log.

Many thanks

**Comment by ntozier** [comment] 2020-01-06 14:48
This is your webserver telling you that your php.ini has the open_basedir directive enabled.  Go look at the php.ini that your webserver is using.  This is also not a bug or issue with osTicket so please close this issue report and post your question on the forums if you need more assistance.  Thanks.

**Comment by JediKev** [comment] 2020-03-09 21:07
Closing due to inactivity. Please reopen if this is still an issue.

**Closed as completed by JediKev** 2020-03-09 21:07 UTC
