### ISSUE TITLE
Print issue with customs forms

### ISSUE THREAD

**Issue by quentin69** [osTicket/osTicket#1878] opened 2015-03-19 15:55 UTC
Hi,

I have a problem to print ticket with customs forms.

When I print a ticket with custom forms, these forms are superimposed on tp and bottom.

You can see on the picture, the bottom of the form "Information sur l'ENR" is superimposed over the top of the form "Formulaire MANAGER"

![screenshot_1](https://cloud.githubusercontent.com/assets/11558676/6734488/ae2dcd08-ce58-11e4-88a5-548123989e73.png)

My version of osTicket is 1.9.6

Thanks !

**Comment by greezybacon** [comment] 2015-03-19 18:11
We've addressed this issue in the `develop-next` branch by rendering the entire PDF as html

**Comment by quentin69** [comment] 2015-03-19 18:53
I'm sorry but I'm French and I don't understand what do you mean ?

You mean this issue is already known and fixed or will be fixed later ?

Thanks !

**Comment by Chefkeks** [comment] 2015-03-19 19:27
The issue is already fixed and will be included in a future release.

Just as an important note, since a lot of folks misunderstand that little difference:
"A" future release is not automatically "the next published" release!

**Comment by quentin69** [comment] 2015-03-19 19:49
Hi,

Thanks for your response.

I understand that this does not mean necessarily resolved in the next release but is it possible to set this manually in the current version ?

If not do you have any idea when it will be built ?

Or maybe can you give me an alternative solution to print my ticket correctly ?

Thanks a lot !

**Comment by greezybacon** [comment] 2015-03-19 21:40
@quentin69 you could upgrade to `develop-next`; however it is still relatively unstable. You could also look at just back-porting changes made to `include/class.pdf.php` and `include/staff/templates/ticket-print.tmpl.php`. And then there's always the option to just put up with the shortcoming and await the next major release

**Closed** 2020-01-06 20:14 UTC
