### ISSUE TITLE
bug: history ticket does not show help topics changes, only said "updated ticket"

### ISSUE THREAD

**Issue by mckaygerhard** [osTicket/osTicket#2228] opened 2015-07-07 16:45 UTC
in the history of each ticket, if an agent change the help topic or the ticket status, the history only shows "ticket updated" but the previous state does not are reflects in the history!

**Comment by Rankgel** [comment] 2015-07-07 16:52
we have same problem, with our system, previous status  history is lost when status is update.

**Comment by greezybacon** [comment] 2015-07-07 20:47
We've added edit events to the ticket thread in v1.10; however, after a quick test, I see that help topic changes are not logged yet.

**Comment by mckaygerhard** [comment] 2015-07-07 20:54
but i talking about 1.8/1.9 releases.. that its used in my production environment
(in 1.10 i noted that but stability are still a doubt)

**Comment by balojs** [comment] 2015-07-09 21:12
+1

**Comment by Rankgel** [comment] 2015-07-10 15:58
My system running at 1.9.6, is stable and we don't have plans for updgrade, if you could solve this problem it would be very helpfull.

**Comment by ntozier** [comment] 2015-07-10 16:29
@Rankgel The devs don't generally back port new features to old versions.  The only way to get new features is to upgrade, or implement the changes yourself.

**Comment by mckaygerhard** [comment] 2015-07-10 16:41
@ntozier do u said that a missing history its a new feature!!!!! its suppost to be that history register all activities and we noted dont doit in those cases (ticket change topic)

**Comment by ntozier** [comment] 2015-07-10 16:54
![capture](https://cloud.githubusercontent.com/assets/1315768/8623977/be9adc8c-2702-11e5-8144-537bcc2126f1.PNG)

I repeat: "The devs don't generally back port new features to old versions. The only way to get new features is to upgrade, or implement the changes yourself."

**Comment by mckaygerhard** [comment] 2015-07-10 16:56
i added a fact to u'r reply, with this link:

https://github.com/osTicket/osTicket-1.8/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+1.9.9

seems that an upgrade are not very safe in a production environment! right guys? what do u think @Rankgel or @infectormp ? i see a lof of bug and annoying in 1.9.9 and 1.10

**Comment by infectormp** [comment] 2015-07-10 19:16
@mckaygerhard too much emotion :)

1.10 - it's major update and this version have a lot very awaiting futures (for me) and this is still a preview release (not for production) so he can\must have a lot of bugs that we all try catch at our test environment.

1.9.9 - we start using this version 8 days ago in production, we migrate from spiceworks. When i made decision start using osTicket i know about some bugs and annoying things. This sad but we can live with this, this is not fatal. For me not very important log help topic changes. It is not possible to implement all from first try and not make any errors in the code.

I don't know about devs experience with other helpdesk software (my about 12 years) but in general they create a very good product with some exclusive features that i not saw in commercial product. osTicket have great potential for grow and development.

Personal for me osTicket have some features that i don't understand, one of this future i describe here https://github.com/osTicket/osTicket-1.8/issues/1798

**Comment by mckaygerhard** [comment] 2015-07-10 20:05
i used osticket for a year ago, from 1.9.2 and up only to 1.9.5, and its great, but my data are huge, VERY HUGE and its importante for us.. so its not easy to me upgrade somethig that have less "details" (to not said bugs) to another that are more newer just for "new features"..

i discovered this issue and i guess that its helpfull that bring support to see history changes that are missing.. 

my dissapointing are that this its a missing thing that its suppost to be..

**Comment by infectormp** [comment] 2015-07-11 05:04
we all must say thank you to @greezybacon for his commit 14f6902 that fixes this problem :)

**Comment by mckaygerhard** [comment] 2015-07-17 20:18
thanks @greezybacon , umm there's no plans to backported that to 1.9.X series? i cannot updated to 1.10 too many huge data  (i'm too busy to make track of errors)

also the change status of the ticket does not track in the history! must i open a new ticket for that also?

i currently updated only the code and use alwasy same sql data (with reapir tables), and in some cases track of  changes (so far more easy) on the code fixeds.. 

if i paid support of 1.10, i'll be in same condition when made 1.11?

**Comment by mckaygerhard** [comment] 2015-07-17 20:19
and i not still close due the problem that i reported are in 1.9.9

**Comment by greezybacon** [comment] 2015-07-31 22:54
@mckaygerhard the new thread eventing system will not be backported to v1.9.x

**Comment by mckaygerhard** [comment] 2015-08-01 14:15
ok ok there's so changes, can u tell me what commits may i backport to 1.9.X i really need that, i can made a backport but the code of osticket are poorly documented !

**Comment by mckaygerhard** [comment] 2015-08-31 15:50
@greezybacon in the name of the comcepts of opensouce and collaboration where are the commits realted tho this ticket, i can made a single patch and show here how other can implement
***i cannot update production env to 1.10 due i can see obviously that 1.10 still have many issues!***
due i still use 1.9 series of osticket in production and i really need ***this MISSING functionallity***

**Comment by mckaygerhard** [comment] 2016-05-28 15:14
A YEAR WAS END; AND STILL 1.10 NOW START TO MAKE OFICIAL RELEASE; ONLY RC RELEASE CANDIDATES....

and suppose to i must install 1.10 in my production system!?!?

and @greezybacon i stll waiting how to backport this feature commit to 1.9 brand!!

**Comment by ntozier** [comment] 2016-05-31 19:56
![capture](https://cloud.githubusercontent.com/assets/1315768/15688466/3ea8121e-2748-11e6-81a0-358c3e13e94c.PNG)

**Comment by mckaygerhard** [comment] 2016-06-02 13:17
so then when coume out 1.10? yeah, osticket now its a primary system used in my job! oh men osticket gorw up so many and now i depend on it!

i made some contributions and still that contribnutions not yet included in 1.9.X like the open attachments in new window! in every download i mus change code pieces to tune .. and i not developer!

**Comment by mckaygerhard** [comment] 2016-06-02 13:18
and @ntozier i'm not taking about new threat system, i'm taking about that **a bug its present! history are not reflected! in ticket history in any 1.9 relesas**

**Comment by ntozier** [comment] 2016-06-02 14:44
> so then when coume out 1.10?
As you have been told many times in many threads, 1.10 will be released when it is ready to be released.  I'm not sure what part of that you aren't getting.

**Comment by novat0** [comment] 2016-06-07 18:16
do mean that this clarelly bug its not supported and confirmed are present in 1.9, but will be correctly only in 1.10 that will not come today?

**Comment by greezybacon** [comment] 2016-06-25 15:17
I can confirm that changes to the help topic are properly logged in the events in the ticket thread in v1.10-rc.3

**Comment by mckaygerhard** [comment] 2016-06-26 00:24
but v1.10 are not stable and not official released yet! 

please gime a break! do u suggest me to put in production a stil not stable/property completed software?

i report this ITS A BUG IN v 1.9 that are not happened, v1.9.11 does not logged changes to help topic in history threat! please!

**Comment by Rankgel** [comment] 2016-06-26 01:43
mckaygerhard is right, the bug is presente in stable release, i have v1.9.11 and does not logged changes to help topic, i try ti fix it but unsuccessfully. some help here would be good

**Comment by greezybacon** [comment] 2016-06-26 03:30
Sorry. It's not a bug. Nothing breaks when you update the help topic. It's a feature request, and it's been implemented.

**Closed** 2020-01-06 20:13 UTC
Labels: next
