### ISSUE TITLE
When closing ticket, it does clear overdue flag on the database

### ISSUE THREAD

**Issue by maarguello** [osTicket/osTicket#6346] opened 2022-11-03 23:11 UTC
osTicket Version v1.17
Web Server Software Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.0.18
10.4.24-MariaDB
Chrome Versión 98.0.4758.102
Windows 11.

I was creating an overdue report since mysql, but I was noticing that when ticket is overdue and then is closed, overdue is detele on the database.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/57649178/199851609-925f9310-10a9-4852-9b6d-9e57f0abc21d.png">

<img width="394" alt="image" src="https://user-images.githubusercontent.com/57649178/199851746-349c8823-67ec-4f39-93b5-3446505658ab.png">

<img width="358" alt="image" src="https://user-images.githubusercontent.com/57649178/199851941-2322c92c-4218-4d22-8c0b-2f8d83da2746.png">

did you heard this before?

**Comment by JediKev** [comment] 2022-11-03 23:13
@maarguello 

When a Ticket is closed it is considered resolved which means the overdue flag is cleared. This is intended behavior.

Of course, you can change this to your liking by customizing the code.

Cheers.

**Closed as completed** 2022-11-03 23:13 UTC

**Comment by maarguello** [comment] 2022-11-03 23:26
thanks @JediKev for your reply.

probably take me a while find the file what I need to change, I appreciate if can tell me what are the principals files we need need to take a look.

**Comment by maarguello** [comment] 2022-11-04 23:09
I'm found the way to get avg overdue.

select (sum(case when t.created + interval s.grace_period hour <= now() then 1 else 0 end) / count(*)) * 100 pct_sla_vencido
  from ost_ticket t
  left join ost_sla s
    on s.id = t.sla_id
 where closed is not null and $__timeFilter(closed)
