### ISSUE TITLE
New Message mail failing

### ISSUE THREAD

**Issue by JoshBeans** [osTicket/osTicket#4352] opened 2018-07-20 08:56 UTC
Hi,

I've recently upgraded from 1.10.0 to 1.11.0-rc1 and noticed that agents no longer receive new message alerts.

apart from this all mail functionality seems to be working fine.

when the the messages fail to send to agents I'm getting no errors anywhere so I'm kind of at a loss.

my install

ubuntu 16.04 LTS
PHP 7.0
mysql 5.7

**Comment by JediKev** [comment] 2018-07-20 14:30
@JoshBeans 

Works just fine for me on my install of 1.11.0rc-1. Do you have the Alerts enabled? Do the agents have alerts enable for each of their departments/teams? It appears your issue is a simple configuration issue.

Cheers.

**Comment by JoshBeans** [comment] 2018-07-20 14:43
I was hoping it was a simple mis-configuration too but I'm struggling to find where.  By the looks of things it's kept the same configuration from 1.10.0 but is no longer working:

![image](https://user-images.githubusercontent.com/17124935/43008495-26c2a824-8c33-11e8-8b39-97a533234d24.png)

![image](https://user-images.githubusercontent.com/17124935/43008538-4653b296-8c33-11e8-8079-62c6726d7efd.png)

![image](https://user-images.githubusercontent.com/17124935/43008587-66241a5c-8c33-11e8-8609-583450ddd3ec.png)

@JediKev does it look like I'm missing something?

It's sending and receiving email fine but whenever an end user appends a message to a ticket either in the portal or via mail we get no alerts

**Comment by JediKev** [comment] 2018-07-20 14:58
@JoshBeans 

So for your settings, the New Message Alert will only be sent to all agents apart of the assigned Team, an Agent who is assigned to the ticket, or the Last Respondent to the ticket. Please make sure you have an Agent/Team assigned to the ticket or make sure an agent has responded to the ticket. If you have a Team assigned to the ticket and no one in the Team is getting the alerts then you need to check **Admin Panel > Agents > Teams > click team name > Members** and make sure they all have the **Alerts** box Enabled.

One more thing to check (just in case) is each agents' Alert setting for their departments. Please go to **Admin Panel > Agents > Agents > click agent name > Access** and make sure all of their **Alerts** box is Enabled.

Cheers.

**Comment by JoshBeans** [comment] 2018-07-20 15:08
@JediKev 

Thanks for the reply.  I do have agents in these teams and the assignment alert is working fine for these agents.

here is one of the teams with alerts enabled for the members:
![image](https://user-images.githubusercontent.com/17124935/43009699-465d850c-8c36-11e8-8255-b9c4b3d40a36.png)

Heres a list of all department members with alerts, I'm noticing that the tick box is greyed out though, would that matter?

![image](https://user-images.githubusercontent.com/17124935/43009972-144b1ede-8c37-11e8-9590-8ee3069f96b5.png)

**Comment by JediKev** [comment] 2018-07-20 17:41
@JoshBeans 

Greyed out just means you are unable to change the setting from that page (you would have to go to each agent's account to change that setting). I'm really unsure at this point as it's working just fine for me and but not for you...have they checked their spam for the alerts? Maybe they are going to spam? Is the New Message Alert Template okay? Like are there any variables that might break the template (should be a warning at the top of the page when you click on a template under Admin Panel > Emails > Templates > click template set > click New Message Template)?

There is just so much to go through here...

Cheers.

**Comment by Shadow00Caster** [comment] 2018-07-20 19:04
I am experiencing the same issue after going from 1.10.4 to 1.11.0-rc1.  Everything was working normally and as intended before the upgrade to 1.11.0-rc1.

Settings:
![image](https://user-images.githubusercontent.com/13611109/43020491-f931e9d8-8c14-11e8-9750-c7afdbcb1da8.png)

![image](https://user-images.githubusercontent.com/13611109/43020502-02f06bac-8c15-11e8-904f-d0ab00a75d12.png)

![image](https://user-images.githubusercontent.com/13611109/43020514-0fb300a2-8c15-11e8-9bf0-525ac56f56cd.png)

**Comment by JediKev** [comment] 2018-07-20 19:21
@Shadow00Caster

You have the new message disabled for that department.

Cheers.

**Comment by JediKev** [comment] 2018-07-20 19:35
@JoshBeans

It looks like everything is fine and it’s so weird because it works for me..

Could you try cloning the default templates and use them to test? Maybe it’s some of those variables?

Cheers.

**Comment by Shadow00Caster** [comment] 2018-07-20 19:36
@JediKev @JoshBeans I unticked and the problem still persists (note that it was ticket prior to the upgrade).

**Comment by Shadow00Caster** [comment] 2018-07-20 19:44
So all unticking the "New Message - Disable for this department." does is send message confirmations to the person who is submitting a response to the thread.  What is not working for me is the assigned agent is not getting e-mails that a new response has been added to the ticket, this was working normally before.

Further, examining mail server logs, when I unticked the new message box, I could see the ticket system receiving the mail to be sent to my mailbox which was the confirmation of response submission, however there was no email sent from the ticket system to the agent assigned to the ticket notifying them of the new response.  If I go back further in logs to before the upgrade, I can clearly see these email messages flowing as intended.

**Comment by JediKev** [comment] 2018-07-20 19:46
@Shadow00Caster

Do you see any errors in your Apache/PHP error logs?

Cheers.

**Comment by mikshepard** [comment] 2018-07-20 19:58
I am having the same issue.  I found this error from the cron job:

> PHP Fatal error:  Call to a member function getEmail() on null in /var/www/osTicket/include/class.ticket.php on line 1681

> Fatal error: Call to a member function getEmail() on null in /var/www/osTicket/include/class.ticket.php on line 1681

The user message gets posted but no email notifications sent out to the agent.  I did a git pull today and this error start.  The last pull from 7/4 did not have this issue.

Hope this helps

**Comment by JediKev** [comment] 2018-07-20 20:05
@mikshepard

What does that line look like for you? My line 1681 is not getEmail().

Cheers.

**Comment by JoshBeans** [comment] 2018-07-20 20:11
I'm confident it must be something to do with the New Messaage function specifically.  Everything in regards to mail worked perfectly pre-upgrade.  All settings are unchanged and alerts are enabled all the way through, mail obviously still sends and receives without issue and all other alerts including assignment and internal note alerts work without issue.

maybe something doesn't apply properly during the upgrade during certain circumstances?

**Comment by mikshepard** [comment] 2018-07-20 20:18
@JediKev :  I'm running the latest git pull from today, on the "1.11.x" branch.  That line looks like this for me:

        //the ticket user is a recipient
        if ($owner->getEmail()->address != $poster->getEmail()->address && !in_array($owner->getEmail()->address, $skip))
          $owner_recip = $owner->getEmail()->address;

**Comment by JediKev** [comment] 2018-07-20 20:20
@mikshepard

Ah, perfect. Thank you. Let me look into this.

Cheers.

**Comment by JoshBeans** [comment] 2018-07-23 10:48
Hi @JediKev 

do you think you know what the problem is with this one?

**Comment by JediKev** [comment] 2018-07-23 13:53
@JoshBeans 

Yes, actually. I found out that I was testing on my in-house version of `1.11.0rc-1` and this has other fixes that haven't been released yet (explains why it works for me and not you guys). We will release either an updated version of `1.11.0rc-1` or a new version `1.11.0rc-2` soon that will include the fix for this.

Cheers.

**Comment by JoshBeans** [comment] 2018-07-23 14:50
@JediKev 

Cool, thanks for your help with this one

**Comment by Shadow00Caster** [comment] 2018-07-23 15:48
@JediKev Any ETA on rc2 or are fixes in a branch that I can pull down?

**Comment by JediKev** [comment] 2018-07-23 15:49
@Shadow00Caster 

Nope and nope.

Cheers.

**Comment by Shadow00Caster** [comment] 2018-07-24 22:58
@JediKev 

Alright, thanks.  Looking forward to the fixes coming, 1.11.0 has some awesome changes!

**Comment by JediKev** [comment] 2018-07-31 20:34
@Shadow00Caster 

Now, `develop-next` is the most up-to-date branch for all things 1.11.0rc-1! Feel free to pull this and use this!

Cheers.

**Comment by Shadow00Caster** [comment] 2018-07-31 23:57
@JediKev 

Awesome, thanks!  FYI looks like the mail issue I was experiencing is no longer happening.

**Comment by JediKev** [comment] 2018-07-31 23:58
@Shadow00Caster

That’s great! Thanks for the feedback!!

Cheers.

**Comment by JoshBeans** [comment] 2018-08-01 13:09
@JediKev  Thanks for the update

Is there some specific code i can overwrite to fix the mail problem or do i need to overwrite everything?

**Comment by JediKev** [comment] 2018-08-01 13:56
@JoshBeans 

I would recommend downloading the latest `develop-next` branch as it has all the recent fixes already merged, _plus_, I don't know what exact commit fixed the issue. lol

Cheers.

**Comment by JoshBeans** [comment] 2018-08-01 15:16
@JediKev  ok no problem.

I was asking because I tried downloading this branch on my ubuntu server and just copying all the contents to my osticket install directory.  afterwards I got a load of errors on the staff login screen.

I've reverted the changes but not sure what I did wrong, should I grab a screenshot?

**Comment by JediKev** [comment] 2018-08-01 16:18
@JoshBeans

Most likely because you’re using PHP 7 which is not supported. Try PHP 5.6.

Cheers.

**Comment by JediKev** [comment] 2018-08-01 20:36
@JoshBeans 

That's because it's not packaged, it's from Github. The official package will contain the correct version number!

Cheers.

**Comment by JoshBeans** [comment] 2018-08-02 08:36
@JediKev 
only one small problem I've seen so far with this branch is the priority variable doesn't seem to work in mail.  rather than pulling the actual priority it just says 'Array' any ideas?

![image](https://user-images.githubusercontent.com/17124935/43572476-90a9cd7c-9637-11e8-9e2c-aa188e2d0a51.png)

**Comment by JediKev** [comment] 2018-08-02 13:44
@JoshBeans 

As you can see I have already addressed this issue here and it was merged yesterday:
https://github.com/osTicket/osTicket/pull/4390

Cheers.

**Comment by xWyatt** [comment] 2018-08-07 15:51
I am also having this issue, however it is also happening on the latest pull from `develop-next`.

New Message alerts we're working a-ok prior to the 1.11 upgrade and moving to the `develop-next` branch hasn't resolved the issue.

Any ideas?

**Comment by vpetre** [comment] 2018-08-28 14:05
Hello,

I also have the same issue on v1.11.0-rc1, the agent don`t receive any notification when someone answer to ticket.

Does anyone have fix for it ? To not update the whole system. 

Regards.

**Comment by JediKev** [comment] 2018-08-28 14:07
@vpetre 

Please read the comments before posting... the fix has already been merged to the `develop-next` branch.

Cheers.

**Closed** 2020-01-06 20:00 UTC
