### ISSUE TITLE
Bug with language pack

### ISSUE THREAD

**Issue by sfonteneau** [osTicket/osTicket#1852] opened 2015-03-17 16:45 UTC
Hello

With language package french, cith osticket 1.9.6.
Only the open or closed status appears. No resolved

The fonction "Ticket will be reopened on message post \* "  no works.

I'm on a fresh install

This works in English but not in French.

**Comment by mckaygerhard** [comment] 2015-03-17 17:19
I confirm same problem with surrent two lasted stable brand and also for developer-next brand.. with languaje package spanish and russian.

**Comment by mckaygerhard** [comment] 2015-03-17 17:20
This issue its critical due make unusable the system as expected!

**Comment by infectormp** [comment] 2015-03-17 19:19
Can't reproduce with russain langauge. Can you give some screenshots and steps to reproduce this error.

**Comment by infectormp** [comment] 2015-03-17 19:24
Resolved tickets showed in Closed menu. This looks normal because Resolved status have State:Closed.

**Comment by sfonteneau** [comment] 2015-03-17 20:01
Image for Only the open or closed status appears.

![capture du 2015-03-17 20 49 55](https://cloud.githubusercontent.com/assets/5419492/6696275/64cc32ba-cce8-11e4-93b1-3a70bfd5a4d6.png)

![capture du 2015-03-17 20 28 29](https://cloud.githubusercontent.com/assets/5419492/6696276/64d45f3a-cce8-11e4-80f4-82afdda90ee8.png)

and fo  fonction "Ticket will be reopened on message post * " no works:

a exemple ici :
http://aide.stemarie-aizenay.fr/view.php?auth=o1xaiaaaaacaaaaag0iekok9Y%2Bcj7g%3D%3D

**Comment by greezybacon** [comment] 2015-03-17 20:07
> and fo fonction "Ticket will be reopened on message post * " no works:

What are your settings for the Closed and Resolved states?

**Comment by sfonteneau** [comment] 2015-03-17 20:13
where can I find these parameters ?           English I have nothing configured differently.

**Comment by greezybacon** [comment] 2015-03-17 20:18
Admin Panel -> Manage -> Lists -> Ticket Statuses. Then edit the Closed and Resolved statuses

**Comment by greezybacon** [comment] 2015-03-17 20:20
> With language package french, cith osticket 1.9.6.

Did you download the most recent language pack?

**Comment by sfonteneau** [comment] 2015-03-17 20:25
The last language package, download today. 

The différent screenshoot:

![Uploading Capture du 2015-03-17 21:21:19.png . . .]()
![capture du 2015-03-17 21 21 10](https://cloud.githubusercontent.com/assets/5419492/6696762/f89a42e0-cceb-11e4-9a96-be804af31212.png)
![capture du 2015-03-17 21 21 00](https://cloud.githubusercontent.com/assets/5419492/6696763/f8b7ab96-cceb-11e4-8b74-41a81addda0f.png)

**Comment by infectormp** [comment] 2015-03-17 20:30
i not confirm this issue with russian. 
![close_open](https://cloud.githubusercontent.com/assets/9958813/6696872/875e62f2-ccfd-11e4-8286-c52face031a3.png)

**Comment by sfonteneau** [comment] 2015-03-17 20:32
I can not put a ticket resolved, so it can not be reopened .This is my problem.


I will try to install the Russian version for testing .

**Comment by greezybacon** [comment] 2015-03-17 20:34
@sfonteneau if you click on the [Properties] button to the right of the ticket status names, then you will get a popup dialog where you can configured if a ticket can be reopened or not in each state

**Comment by infectormp** [comment] 2015-03-17 20:38
If i understand right, ticket statuses not placed in language pack. I rename statuses from English to Russian in Admin Panel -> Manage -> Lists -> Ticket Statuses.

With French language pack i still have statuses in russian.

**Comment by sfonteneau** [comment] 2015-03-17 20:49
With russian is good
![capture du 2015-03-17 21 47 52](https://cloud.githubusercontent.com/assets/5419492/6697196/55bd6c9c-ccef-11e4-8e05-d895c65777d2.png)

I try again with French

**Comment by sfonteneau** [comment] 2015-03-17 20:51
oops !!  in ticket (not  in list ticket)

![capture du 2015-03-17 21 50 29](https://cloud.githubusercontent.com/assets/5419492/6697261/b6987a5c-ccef-11e4-813e-499c001ae5d6.png)

**Comment by infectormp** [comment] 2015-03-17 20:55
can you look web server log for error?

**Comment by sfonteneau** [comment] 2015-03-17 21:12
No Error in apache serveur.  

Does not work in French and Russian.

But work with @infectormp,  strange

**Comment by infectormp** [comment] 2015-03-17 21:21
with French language pack
![close_open](https://cloud.githubusercontent.com/assets/9958813/6697852/8d618b32-cd04-11e4-922c-88b83cab88ee.png)

**Comment by sfonteneau** [comment] 2015-03-17 21:27
Ok, this is a problème with me,

**Comment by sfonteneau** [comment] 2015-03-17 21:29
@greezybacon    yes  Good idea but it does not work .

![capture du 2015-03-17 22 22 36](https://cloud.githubusercontent.com/assets/5419492/6698006/f8b65bc0-ccf4-11e4-9511-0a04cf41e917.png)

**Comment by mckaygerhard** [comment] 2015-03-17 22:27
doesn not work in my setup too, paste pic:

![status-error-1](https://cloud.githubusercontent.com/assets/1571724/6698881/14d4c5a6-cccf-11e4-9d87-41c0139dcfda.png)

![status-error-2](https://cloud.githubusercontent.com/assets/1571724/6698890/1dfdd500-cccf-11e4-81a5-808174828199.png)

**Comment by sfonteneau** [comment] 2015-03-17 22:44
I found this:

![capture du 2015-03-17 23 16 15](https://cloud.githubusercontent.com/assets/5419492/6699139/767a5412-ccff-11e4-9fdb-42306c362fd2.png)

This may be related ?

**Comment by mckaygerhard** [comment] 2015-03-17 23:22
its not related, i have complete good setup and still happened!

**Comment by sfonteneau** [comment] 2015-03-18 09:02
I found the solution !!!

during installation , you have the choice of language copied in include / i18n / and English . Do not choose your language! Select English. Your osTicket will be well in your language .

This is a bug ? no ?

**Comment by sfonteneau** [comment] 2015-03-18 09:12
But, in this mode, osTicket is a half- translated...

**Comment by sfonteneau** [comment] 2015-03-18 11:05
My problem is solved. However, this method requires retranslate forms, email , lists, etc ...

Thank you all for your help

**Comment by greezybacon** [comment] 2015-03-18 15:43
I'll try to look into the file built in the language packs for the new statuses

**Comment by vrowdy** [comment] 2015-10-13 09:19
Sorry for resurrecting an old issue.
This problem is also occuring with the Dutch language pack.

During installation, I chose to install everything in Dutch. I do get the correct ticket statuses (in Dutch) in the right place in the Admin-panel.
However, I am unable to change any ticket to any other status than 'open'. Also, the 'default status for new tickets'-setting also only shows 'open'.

When I install osTicket in English, this problem doesn't occur. But as stated before, this requires a lot of translation afterwards because a lot of strings are setup in the database during installation.

I'm using osTicket 1.9.12. This seems to be a critical bug in the language-pack support. Perhaps something should be change in the translation file, but something should definately be change in osTicket installation as well, so that even when the translation file is missing some info, the installation still is performed correctly.
Currenty, it is impossible to use osTicket in Dutch.

I hope this issue can be resolved soon.

**Comment by vrowdy** [comment] 2015-10-13 11:04
I managed to fix it by myself.
The problem is as follows:
In the database table ticket_status there is a field 'state'. That filed contains certain descriptions in English, for example 'closed'. These fields should never be translated - they are internal fields referenced by PHP code. They are the keys by which osTicket knows which state is actually closed, because the text shown to the user is translated.

Solution is resetting the values in the field 'state' back to their original English values.

So there a are two problems: the translators shouldn't have translated this field, but more importantly, during the creation of the database (during setup), osTicket should not use these translated values even if they are provided by the language pack.

Also, checks should be made to make sure this doesn't happen as well for other tables / values.

**Comment by mckaygerhard** [comment] 2015-10-13 23:18
@vrowdy this issue its not old or dead, stil lhappened and deveopers not rsolved. 

about your problem, seem that status must be redefined as copy's in te interface and does are a workaroud, but let dirty status in the interface too!

developers start new develop version event resolved the bugs in STABLE VERSION i dont understant that, many users have stable 1.9.X in setup production environment

**Comment by ntozier** [comment] 2015-10-14 13:29
@vrowdy it's not closed so its not old or dead.  Thank you for posting your fix, I'm sure that it will help other people and the devs to fix the problem.

**Comment by greezybacon** [comment] 2015-10-20 13:50
@vrowdy @mckaygerhard did you download the new language pack from the osticket.com download page? I made my best effort to clean these translated names up in the Crowdin software (which is used to facilitate translation and build the language packs). I wasn't aware it was still broken in the latest language packs

**Comment by vrowdy** [comment] 2015-10-21 07:14
Yes, I downloaded the latest language pack (about a week before I posted my first message about this subject here).


Van: Jared Hancock [mailto:notifications@github.com]
Verzonden: dinsdag 20 oktober 2015 15:51
Aan: osTicket/osTicket-1.8 <osTicket-1.8@noreply.github.com>
CC: Rowdy van der Veen <rowdy@noord-computers.nl>
Onderwerp: Re: [osTicket-1.8] Bug with language pack (#1852)


@vrowdy<https://github.com/vrowdy> @mckaygerhard<https://github.com/mckaygerhard> did you download the new language pack from the osticket.com download page? I made my best effort to clean these translated names up in the Crowdin software (which is used to facilitate translation and build the language packs). I wasn't aware it was still broken in the latest language packs

**Comment by mckaygerhard** [comment] 2015-10-21 14:55
the new languaje packs are for v 1.9.X ? and have all lowercases the uri's ?

**Comment by mckaygerhard** [comment] 2016-05-28 15:39
i download lasted language packs (greek, spanish and russian) and this problem persist, also dates format are totally wrong

**many links still (and seem now more) break!**

i want and try to collaborate, but the translation web inteface are a limit barrier! need a more avanced and comsole like tool, not a windoze click and point limited interface to solve this!

**Comment by ntozier** [comment] 2016-05-31 20:04
We cordially invite you to find and implement a better solution than the interface provided.  You can let us know when you have completed it and where it is here in this thread.

**Comment by mckaygerhard** [comment] 2016-06-02 13:09
use gettext (https://en.wikipedia.org/wiki/Gettext) and/or Toolkit (https://en.wikipedia.org/wiki/Translate_Toolkit) as any other linux developer does! of course make it your po templates! by own scripts

**Comment by ntozier** [comment] 2016-06-02 14:36
Once you have completed this code change please issue a PR (Pull request) with the changes.  Please keep the PR limited to just the changes required to implement this feature.

**Comment by mckaygerhard** [comment] 2016-06-02 14:40
i already discuted oinly for 1.9 brand if i doit!

**Comment by ntozier** [comment] 2016-06-02 14:47
The devs have already stated that they will not be back porting any or adding any features to the 1.9 branch.

**Comment by novat0** [comment] 2016-06-07 18:13
i have this bug in THE ONLY STABLE VERSION i can download, so if this will be included as correction feature in next version (i mean 1.10) so when will be out? due this bug was reported agains 1.9 release and its imnportant for production sites support agains the today in use! right!?

**Comment by ntozier** [comment] 2016-06-07 19:17
@novat0 it will be released when it is ready.  You will not get a better answer than that.

**Comment by greezybacon** [comment] 2016-06-21 21:58
Have we deviated from an original problem statement? What bug is still in existence?

**Comment by mckaygerhard** [comment] 2016-06-22 14:02
the problem its that the i18n files must be corrected but the translation tool interface only able to edit the string refers to language and not the original whole file source, due the problem its inside the tranlation files itselft and not in the translated strings!

this problem its so easy to solve (only edit the files) but stil in two years are not solved!

this affect at least 3 languajes: russian, greek and spanish! in my case!

**Closed** 2018-12-22 14:40 UTC
Labels: Language i18n, bug
