### ISSUE TITLE
Fatal error  Call to a member function sort() on array

### ISSUE THREAD

**Issue by bastienho** [osTicket/osTicket#3147] opened 2016-05-24 08:51 UTC
On **develop**, the page https://example.com/scp/kb.php gives
`Fatal error: Call to a member function sort() on array in /root_path/include/staff/faq-categories.inc.php on line 148`

I use a workaround like this:

```
- $categories->sort(function($a) { return $a->getLocalName(); });
```

```
+ sort($categories);
```

but I don't think it is the better way

Here is the config:
- osticket develop
- Debian Jessie
- Nginx

**Comment by balojs** [comment] 2016-05-24 14:49
@bastienho try to use this class
https://github.com/osTicket/osTicket/blob/develop-next/include/class.orm.php

**Comment by balojs** [comment] 2016-06-06 17:47
+1

**Comment by zguithues** [comment] 2016-06-15 19:52
I also had this issue once i upgraded 1.9.12 -> 1.10 rc3.

@balojs i tried your suggestion, it had no effect.

@bastienho Your method works for me.

Hopefully this gets fixed on future versions.

**Comment by balojs** [comment] 2016-06-15 20:50
thanks @zguithues  check this path #3186

**Comment by greezybacon** [comment] 2016-06-20 16:41
Could you also try this patch. I would like to use sorting in the ORM elsewhere and be consistent...
```patch
diff --git a/include/staff/faq-categories.inc.php b/include/staff/faq-categories.inc.php
index e90f06c..18ef634 100644
--- a/include/staff/faq-categories.inc.php
+++ b/include/staff/faq-categories.inc.php
@@ -141,7 +141,7 @@ if($_REQUEST['q'] || $_REQUEST['cid'] || $_REQUEST['topicId']) { //Search.
 } else { //Category Listing.
     $categories = Category::objects()
         ->annotate(array('faq_count'=>SqlAggregate::COUNT('faqs')))
-        ->all();
+        ->getIterator();

     if (count($categories)) {
         $categories->sort(function($a) { return $a->getLocalName(); });
```

**Comment by kest874** [comment] 2016-06-20 17:45
@greezybacon Confirmed that patch works.

**Comment by greezybacon** [comment] 2016-06-20 19:10
I created #3216 to address the issue

**Comment by zguithues** [comment] 2016-06-22 16:41
Patch #3216 works for me @greezybacon 
Thanks for the quick fix! :)

**Closed** 2016-12-06 22:02 UTC
Labels: bug, fix-available
