### ISSUE TITLE
Filter action - Send email - Unable to click on Message box

### ISSUE THREAD

**Issue by GodOfWarWeed** [osTicket/osTicket#3732] opened 2017-03-08 05:17 UTC
Admin Panel > Ticket Filters > >Add new Filters > Filter Action > Select an action dropdown > Send an email. 

I am unable to select the message field of the email template. 

Expected behavior: It should be selectable via mouse click

Actual behavior: Unable to select it, instead can only select it by clicking on subject then hitting the tab key

Osticket Version 1.10 latest. 

Browser, : Both latest firefox and Chrome.

Its just a UI bug more than anything.

**Comment by Chefkeks** [comment] 2017-03-08 06:28
Confirmed! Already reported that issue when 1.10 was under development, seems it never got fixed :(

**Comment by ntozier** [comment] 2017-03-08 14:58
@Chefkeks can you link the original issue report?

**Comment by Chefkeks** [comment] 2017-03-08 15:39
@ntozier 
I can't find it, but there was no separate issue report for this. It was included somewhere on the way to 1.10 in some of the large threads here at github or in mails between me and Jared - I can't remember and can't find it, but I thought it was fixed, but seems like it wasn't or the fixed code had been reverted (accidentally)?!

**Comment by mfelber** [comment] 2017-03-08 16:59
There is another one: https://github.com/osTicket/osTicket/issues/2740

**Comment by ntozier** [comment] 2017-03-08 19:00
So then this can be closed as a dupe.

**Closed** 2017-03-08 19:01 UTC
