### ISSUE TITLE
Help Topic from other department in ticket 

### ISSUE THREAD

**Issue by infectormp** [osTicket/osTicket#1798] opened 2015-03-03 08:31 UTC
1.Add 2 department = testd1 (default) and testd2
2.Add agent to department  testd1 
2.Create topic topictest1, set department = testd1
3.Create topic topictest2, set department = testd2

create new ticket, in Help Topic list you will see topictest1 and topictest2

department testd2
user = 0, Departament Mfnager not set, Group Access set only for department testd2.

**Comment by infectormp** [comment] 2015-03-03 08:33
and i create new ticket with topic from other department. after create i not see ticket in my list and that true because ticket have topic from other department.

**Comment by ntozier** [comment] 2015-03-03 14:35
Sorry I'm not sure I follow you.
Given your scenario above If you create a ticket picking topictest2 it has a department of testd2.
The agent in testd1 will not see it, as you assigned them to department testd1.
Unless you give the agent access to department:testd2 (through their group or department setting) they will never see the ticket unless it is explicitly assigned to them.

**Comment by infectormp** [comment] 2015-03-03 14:48
why user from testd1 see topic from testd2?

**Comment by ntozier** [comment] 2015-03-03 14:56
I cannot answer your question as you have not provided group configuration or teams they might be on.

**Comment by infectormp** [comment] 2015-03-03 16:27
user1 set to testd1 department, groups and teams not set
help topic set to testd2 department

**Comment by infectormp** [comment] 2015-03-03 16:28
under user1 i see help topic where department set to testd2

**Comment by ntozier** [comment] 2015-03-03 16:37
I am unable to replicate what you are reporting (in 1.9.5.1), unless the ticket is also being assigned to user1.

**Comment by infectormp** [comment] 2015-03-03 18:15
help topic
![2015-03-03 21_09_51-osticket __ admin control panel](https://cloud.githubusercontent.com/assets/9958813/6468963/e5d908e2-c1e9-11e4-8faf-8dcba830b40b.png)


agent
![2015-03-03 20_21_28-osticket __ admin control panel](https://cloud.githubusercontent.com/assets/9958813/6468847/185bd4a8-c1e9-11e4-90a9-c0cc258effbf.png)

department 
![2015-03-03 20_21_50-osticket __ admin control panel](https://cloud.githubusercontent.com/assets/9958813/6468848/20e788f6-c1e9-11e4-8490-e5ce37788896.png)

new ticket - **must be visible only testtopic1**
![untitled](https://cloud.githubusercontent.com/assets/9958813/6469035/5d5df8a0-c1ea-11e4-83a5-2c194fb897db.png)

**Comment by ntozier** [comment] 2015-03-03 18:20
So if I understand your images correctly.
You want to make it so that users can only see specific Help Topics.
This is not currently a feature in the ui, and I am not aware of any plans to make it work that way.
Help Topics are about a ticket... and assign tickets departments.
When opening a ticket, users or agents can choose from any Help Topic.  This is by design, and intentional.

**Comment by infectormp** [comment] 2015-03-03 19:11
Strange. Why user by default can't see tickets from other departament but can use help topics from  other departament?  

osTicket will have a more users if will support separation by departament not only in tickets queue but in topics and faqs too. With this future osTicket can really compete with most of the expensive (and complex) support ticket systems on the market.

**Comment by infectormp** [comment] 2015-03-03 19:15
@greezybacon can you say your opinion about this?

**Comment by ntozier** [comment] 2015-03-03 19:20
Work flow is designed to route the ticket utilizing the Help Topic.
If you can't see all the help topics then you wouldn't be able to route the ticket where it needs to go.
It's transparent to the user, who unless they know how osTicket actually works doesn't know that picking a Help Topic could be routing their ticket to a specific department.

**Comment by infectormp** [comment] 2015-03-03 19:37
Simple situation. A have 10 departments, every department have 30 topics. In topic list i will see 300  entry. You really think that will help agents find right topic quick?

For assign tickets to departments better use Ticket Filters.
This can be done by this rule: **IF Ticket ID=XXX then Department=YYY**.

**Comment by infectormp** [comment] 2015-03-03 19:45
You must understand agent from one department 	may not know how to categorize ticket for other department. He know only how to categorize ticket for his department.

**Comment by ntozier** [comment] 2015-03-03 19:46
I don't feel that that solves the real problem.  
The real problem is that a large number of Help Topics is unwieldy.

A few solutions to this would be:
* Redesigned the system to have a challenge response type of system where a root Help Topic is picked and then a second box opens that allows the User/Agent to drill down into the sub category that they want.
* Some sort of responsive drill down that only displays sub categories after the user picks the top level Help Topic and allows them to then pick a sub category.

Hiding Help Topics means that Users/Agents can't pick the right Help Topic on the chance that someone gets transferred to the wrong place, or emails the wrong address. Also Help Topics can always be changed after the fact.

**Comment by infectormp** [comment] 2015-03-03 19:55
Sorry but i not agree with you. As i say before agent from one department may not know how to categorize ticket for other department. He know only how to categorize ticket for his department and must see topics only for his department.

If emails was to wrong address i can transfer ticket to other department without help topic. And then in other department agent set right topic from list that will available for his department.

**Comment by ntozier** [comment] 2015-03-03 20:04
I think that we are going to have to agree to disagree then.

The two production instances I run have 3 and 16 Help Topics respectively.  The first one supports the state of NH, and the second the company that I work for (@600 employees).  You obviously have much larger and different use cases that I do.

**Comment by infectormp** [comment] 2015-03-03 20:17
Over the years, I have used in production many different helpdesk and similar systems (hp openview service desk, manageengine servicedesk plus, spiceworks, otrs, redmine, mantis, jira) and all systems is always something missing. osTicket in the current state of its closest to the ideal. One of the functions is missing for the ideal state is that we are discussing here. And of course more agent frendly interface.

Now i try setup osTicket to work with 8 department (about 50 agents) and every department have very different task. Every department use from 10 to 50 help topics and mix help topics it's a suicide.

**Comment by ntozier** [comment] 2015-03-03 20:31
It sounds like it!

As s work around until something else is done... code wise could you simplify the Help Topics to having the same name as the Department?  And then add a custom list to each Help Topic (that's for that department only) which lists out the "help topics" that you want each department to have and sorta cheat the system?

simple example:

Help Topic: 
-- one
-- two
-- three

list one
-- alpha
-- beta
-- gamma

list two
-- foo
-- bar
-- fu

list three
-- melenkurion
-- abatha
-- duroc
-- minas
-- mil

Would that work?

**Comment by protich** [comment] 2015-03-03 20:33
@infectormp -- while I get your use case, it's important to note that osTicket is not developed for a specific workflow. In your case, you assume agents will *only* be opening tickets in their own department -- which is not the case in > 90% of use-cases, especially when tickets are opened on behalf of end users.

We've tried to make the system flexible and adaptable while keeping it simple. Thanks for the feedback.

**Comment by infectormp** [comment] 2015-03-03 20:49
@ntozier ss work around is the best solution. 

@protich yes this my case. i understand that you want keeping it simple but my suggestion does not make it more difficult. You alway can do option like "Allow choice help topics from other department"

When tickets are opened on behalf of end user, user not need categorize a problem. User have a problem and want get quick solution, end user don't want think how to categorize problem. Categorization is on agent side.

**Comment by infectormp** [comment] 2015-03-03 20:58
Implement separation between departments which I described osTicket able to compete with ManageEngine Servicedesk Plus. 

And again, assign tickets to departments alredy work in Ticket Filters. That why departments in Help Topics can be used for separation by departament.

**Closed** 2020-01-06 20:15 UTC
Labels: Feature Request
