### ISSUE TITLE
1.9.12 File upload error undefined400 with Google Chrome

### ISSUE THREAD

**Issue by jround** [osTicket/osTicket#2797] opened 2015-12-15 18:05 UTC
Recently I am getting a lot of complaints regarding users of Google Chrome when trying to upload files.  The error that comes up is File upload error 'undefined400'.  When I try the same file (A small PDF document as an example) in Internet Explorer 11 it uploads virtually straight away without the same issue.

Now it gets even more strange I tried an older version of Chrome on a colleagues machine and it worked without the undefined400 message, then I updated their Chrome and straight away 'undefined400'

My Chrome version is Version 47.0.2526.80 m (64-bit)

osTicket 1.9.12 is running on Windows Server 2008 R2 IIS7 with PHP 5.3.28 (I did try updating PHP but to no effect, still the same issue).

**Comment by greezybacon** [comment] 2015-12-21 21:22
The `400` part represents the HTTP status from the backend. It should mean a poorly formatted request, oversize file, or file type not allowed. Could you send the response from the server (perhaps via the Chrome developer tools?

**Comment by jwheel12** [comment] 2015-12-29 14:13
I'm experiencing the same issue and here is the console errors from the developer tools in Chrome:

![image](https://cloud.githubusercontent.com/assets/4257360/12035609/f1dfc444-ae03-11e5-8de3-3e19b0673d88.png)

**Comment by greezybacon** [comment] 2016-01-03 22:43
@jwheel12 can you post the text response from the server?

**Comment by jwheel12** [comment] 2016-01-03 23:55
@greezybacon I'm unsure how to do that.

**Comment by greezybacon** [comment] 2016-01-04 19:45
Usually in Chrome, you can click on the link (.../form/upload/attach) in the dialog you snapped. It should take you to a detailed view of the request including the request and response headers. There should also be a tab for the response body as text or a preview. Any information from those sections would be helpful in identifying what is happening on your end

**Comment by jround** [comment] 2016-01-06 12:05
Request URL:http://trackit/supportdesk/ajax.php/form/upload/34
Request Method:POST
Status Code:400 Bad Request
Remote Address:10.201.98.9:80
Response Headers
view source
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection:close
Content-Length:23
Content-Type:text/html; charset=UTF-8
Date:Wed, 06 Jan 2016 12:02:07 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Persistent-Auth:false
Pragma:no-cache
Server:Microsoft-IIS/7.5
WWW-Authenticate:Negotiate oYG2MIGzoAMKAQChCwYJKoZIgvcSAQICooGeBIGbYIGYBgkqhkiG9xIBAgICAG+BiDCBhaADAgEFoQMCAQ+ieTB3oAMCARKicARuDCrg6EX2Tgy+v8W/3ObK+fTNvuTaCZmZ3wJOKxz+TSSqF3PNCWer7bY19byMhvgeyvo5J7tAzIN5U8BOxY7vSE/zNAs2/JgcY5PHyLBVAomSwmGEtxBhc5gIRl39hUwAZXzXJ0Ggl+fSR0J8+ew=
X-Powered-By:ASP.NET
X-Powered-By:PHP/5.3.28
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8
Authorization:Negotiate YIIHVQYGKwYBBQUCoIIHSTCCB0WgMDAuBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHgYKKwYBBAGCNwICCqKCBw8EggcLYIIHBwYJKoZIhvcSAQICAQBuggb2MIIG8qADAgEFoQMCAQ6iBwMFACAAAACjggWAYYIFfDCCBXigAwIBBaEPGw1TSElQTEVZLkFDLlVLoigwJqADAgECoR8wHRsESFRUUBsVdHJhY2tpdC5zaGlwbGV5LmFjLnVro4IFNDCCBTCgAwIBEqEDAgEyooIFIgSCBR6O81riS5GrBAfU/uwrlcYgY81blQqL/RFyabS/OWX760ic6SmWqE/PU+M3s5JYiYpumFn+65VwDNlCrv+VIUMSoBaxqph4J8TFyd3DpghfagIwtGw9EBJu2KkyzoBxPgwdi7nn3RPsiLIZphlYcfoUoK0ocSz/bQf9Xnv+JKnaxR8dB2/fvpKKUH/1gndgdje224Amb2z5sb+T3u+ThBeR/jgSyxoszd5PCCGRa2hPFUoAbIanVRbLKFuu1DcCyAl2AAVKPFT44qX439Ut/4SPOMrcrgdF1u9dkRQMpB36nUiqwMZIADOJhznF8ceYKuPEPcBIErpswxYRvdQNDs1YhxkH3K0XNST04hdlRE7ajeXh1rfv+tkBOF2ve97ef4GChuY1Vcdx01Uco0JkLor6tCNwzNvE54IUpXBBxKYP/fud3lAImGYO720SrZVBPwXonmNIG8SQT+eNchfIVfukdjbko+URFjKLjXDLMomDsOhvTXwzILyRz1FxZ3U97ihv3sQB3ftQyLsJYVm/IXjx4r6JmLgdqqJwZeeCfFAVtAzbgWi9i7s9kFozOP/13YyL7MUSnfbQ4jH+WvcqMTzXNM1ktnrP1XhPY1fDyEfI4JJeDihE2Ey0EeAImLMm+TCmmjz1EED8voCGPXNfgoogGTDI3pHXdiLfVCxLTqHD2OT1474hNbS16HFvj7RUjrOMHsWqIYugK33mNupvLdmhMcFlhmyTwT2O5CS0uardMZ+Iqb3ue5fAwjbZ3QGkGVWMJCDI/9TTxIM+8zzXc3wkW5kr7HDJtWMxA26HC/eXrOtqNHtdI0vkGwvh45S25dyGpLBWsWpC8azgzfn8D71KeyrDPzNfIsU4Engoz8LzuWez4oitN3T/0ByT3lclf6Rh2HE7A3TR5DqfLr2myuVeSuApfoDRxQx4Vy2/gd2kgghQ4acjC5/dAcyvkx7hI6ukbGFji0dz11zSEeF3G+d/no+2qKMOsRjsFDQYOnl1PsEwdLysbJurJpkSm4LN1WBpliA1kgN21uqePfNltYuz7kbwbKVOg7AjAT+fZL3+AS9XbTSPntcmoQa2I2O0XMshjChvcCASgqO3XaA7zy5lU+EVV7le0Ses5B5b+QHTnsOECkenVaR7ApbJGrxn6rED8MMvz9cRw515YnpnJWm67eFtwzR8HfReL9iAhPIYnbnrqmuQCvi36we6dyZPbynLaUeHyMfG05/V7GsbWecxTGfzi56xQeM+/zQGPUfd93hPljaSmkk6T1YVIbZvhfDP1d2JDJ9A3LacB4M5cHxSgPXnEZsFdgZ2OA3xipPQju48cDIgR6vQg1YCrL4jVvnZHXWF4dpd0qcfque12dZPLJMDzG6zW8M6GqVi/JQCUEHLURPmrzuVmB9HAWYplp0D7WoWoHipVdXVpqz8SEwANuJTWRm9OSM8Hju820wvfLMaTpgg6E1oe7U4YUn+nIjUMmOUyVDcbKUTM2J6K8LVgWXkmQzvXecFauwMO8A8Pe8112qY+cmmG3uSUOnvq17x/mm7PhI0JpcodQ21bh5OxEbjL8sKjv0EcXhBGx7L0H+ZLFbUy44yQAe08kRbxH4xgv20NKQZhw4LfNQG/au6xxjT5aTr43WGhEjPtjcwhasXJL5n2fT8NF7mn1ahwXbW6L3dnX9eDoNe5KMMGlk1Z9iDQ5EVEDNsmBvAO6n4e3u3hsmreeIV8e2x6A1vsbv8p4ngKf9XmusNEJP8GKSCAVcwggFToAMCARKiggFKBIIBRqr9j8n03Nu53nO9MwQeI5VPDW04GIaE+I+6+Ri54cT+Br79l58PMbtm5aYpI6sdYnnfVtDMmT1vD2i2Y97AI+H22jRy5++eoSyKV6otCSycohZ9HqYMrDLOacp6aQrvOf8Pfuz7yPKUIYaVksqP0gDqwNw4UzAtggwIdQAs15owRKcZwdC1QiCApXD8byU/f1HW6d9zhJyqwsNXBwQWUqWoRbu40WMAetsBykcYsQN72YZamzL8deQg64TW1IF43wB6AV4iP8B1b0DpdxGJWZJU6fnQE9cW0GbyjAi4Hh3jcdFWECTvWx+kRTHmDMKgfRlVChrbDpEKipu658P3kWpefFQ6g95dcibal0JxTBQK3QmtwvCnlz4YJUS8QitdjvCsz04mt/iEGfHlGEg5dgAkelVL3X4I4/gl4xAPHMElwG8/k8Z3
Connection:keep-alive
Content-Length:707866
content-type:multipart/form-data; boundary=------multipartformboundary1452081727134
Cookie:OSTSESSID=hu2t60h0nuhivcd5eukj6deep5
Host:trackit
Origin:http://trackit
Referer:http://trackit/supportdesk/open.php
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
X-Requested-With:XMLHttpRequest

Response is : Send one file at a time

Hope this helps

**Comment by jround** [comment] 2016-01-06 12:12
Also in open.php  xhr.send(builder); got highlighted for some reason when I clicked something but not sure is this is related to the issue or not.

**Comment by twjenn2** [comment] 2016-01-06 16:04
I have the exact same problem.  Most of our Chrome users are reporting that they suddenly can no longer upload files in Chrome.  However, I am running osticket 1.9.11 on Server 2008R2, IIS7.5.  I have also tested this with the latest RC of 1.10 with the same results.  Firefox, Safari, and IE are unaffected.  

The Text Response for that attach operation is just: "Send one file at a time"
The response headers from the Chrome Inspect Element view for this attach operation:
```
HTTP/1.1 400 Bad Request
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 23
Content-Type: text/html; charset=UTF-8
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Server: Microsoft-IIS/7.5
X-Powered-By: PHP/5.6.0
Set-Cookie: OSTSESSID=0j1lhpu6hjisf1kaceaegvh8e6; expires=Thu, 07-Jan-2016 15:48:56 GMT; Max-Age=86350; path=/; domain=helpdesk
Persistent-Auth: false
X-Powered-By: ASP.NET
WWW-Authenticate: Negotiate oYG2MIGzoAMKAQChCwYJKoZIgvcSAQICooGeBIGbYIGYBgkqhkiG9xIBAgICAG+BiDCBhaADAgEFoQMCAQ+ieTB3oAMCARKicARuh9SHdv0HqPPFQuKJ/ZspdSUAWx1cO3VgjB2z9stLqvB3jvTdcjC5R9LPOusk4nFp49Kmku69uRfJaf3YyTlRB3FbP+dIUVYdDpngRtLEbbDZgTjQI+bTqyzDRZgwefMs/DDLxdUf9maLw4WMM7U=
Date: Wed, 06 Jan 2016 15:49:46 GMT
Connection: close
```

The request headers:
```
POST /scp/ajax.php/form/upload/attach HTTP/1.1
Host: helpdesk
Connection: keep-alive
Content-Length: 120470
Authorization: Negotiate YIIOHQYGKwYBBQUCoIIOETCCDg2gMDAuBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHgYKKwYBBAGCNwICCqKCDdcEgg3TYIINzwYJKoZIhvcSAQICAQBugg2+MIINuqADAgEFoQMCAQ6iBwMFACAAAACjggxOYYIMSjCCDEagAwIBBaEMGwpNQy5VS1kuRURVoicwJaADAgECoR4wHBsESFRUUBsUcHJkY3Bod3MxLm1jLnVreS5lZHWjggwGMIIMAqADAgESoQMCAQaiggv0BIIL8Gjj7bVofbID7jPBNql+X6HA4WA6/L1QWn7XyiielJdLCFHAeaNweeYwhV65kH8INFNLevFW4arUXraM4Wg3T4BXPjr6J1svAjeFiTXQY5sWkhV7xTbVJ+DMnp3ci2Q6OGZHuLd3ol3pAkM9lfTIpD0zirTv6loUXD3Mdz9WdkTpXNIBNgJzQY+4ZOpq4w5B7wGZcUcMYw/SM50WQlpZmk56bWxQrxEOpY2AnguKP3xp+m41hQiOustL4ElM/sycurATi7pTiBhWUJdVP31IchC1Wa+kFXjQNiN1QW1JmHscTrswj5kor61rtDMX4jPOaeo1uhXItd8bvC+sHOrO6lBjJR7DaklQbVi68Z2RsSCgPKq6+JnjpOrnNI1jGJHFJXIhUieO1rJSJBhyRouME9MHzHiGQh2N7tAZZr0bSM5jCOdE/6kK65iTIeFQ0wjDGKloP1osgGC3PoLho7PY6n/EKETrjlaSoLebWV29kzhqoHV/b9dlI3EyHLFtFT0pfEN4/PnQETVMb7UB4l0cMKBl5xSCKaQX8F2KccBdLmbKspepOZ3dyK6Go3Vux0BuC1pBU1uCAV4FLbf3oCGALOrreOzl0YhgMAxA6O/cNF7d4FEz4yhCNnkzAq70bA1GNyOuA7JsTcLqzNFZ1/3ofUADDtMXC2wwLhkB+8w6t5Z4ZPxrHXsPuS/vq+tjtAzM5Dwso1g79oqi5W+46an6XZzJeWq3B3CKWcq0wloeE76hIOSxrn2K77OHLecA//5x+xKRPiYF+lJEcVicSxa2/tJLr7bir6F4b2z1jHzT7jNHnT3r/Lz0SZoYcvr8cDSaDAQm1ieTSj77vZ0+YD0tE/L9SXgURC6w++6u5ESHr+onjnMOs6dJUTtlEqE16l3RCraA/nNUhk1eCYO0NN44HDpxOVnc578rf0M+01akU/aWAR6Wp4b/RWNjTISpSIY+bN40Sysj1NV8aCo0/VpPtaAd+moRszmKKzTAhh3pgRtwcP9S/PY3lwC0mMxnFXfKdZT83s67GYKeVTQXe2LlFpao4tey5pGseU8PWi45gqtDXvFhzv44cCvqW0BUr3tWQ+lFAOFa6IV+mylp98oMaPMBMqou0XJ3T5wQObYwx1xCvFuGEpnKAVBGUbRS9oghuaP7I4VCkIKDnryYkY6S4Evi6eEnKBqpENO3rxawLBDGSG42aiFRpoJjsJdEY1ES5wwQEliFPlKUvRgx2EEV3QIWZmmWNjclM4UKnkLd9AUi6T+EYmteovauDSCCcORY/c4HyDkEKmtN7SKPd39akZH/+Praip7/6RbospMhuuS7Q2MZCS9SpzM5ztxtocICto7hyLSjb5UUIvQbaiNejOwDjzhfRE/DVlJqrUmm+pjWOUWChWyv7UyEbPLRNAF6LexbzTQbFbu/2P4CnifpFxOm+bKMJGoyeLMafx+KP9/tlfF9ypLg9bNedvziAEGkgtIJwDXZqJrNcJQtkw9rGczwQyhm0ZI3X1Vkcbf48CFs3oOik2MBn32LUclYQ1tlcu5/l3NxcxVto+rK0j0T+gsxL/WwWQylUVnRiD7LBzcqx5sdXjpxi/xT5cF7rjSSzClXxdAvfc0uHKS+1iEv+DU/Dc4wZYAh8H7IUCPeJuMfk1eWqAwYnTbxg7163WbKu5tdWpfUVhGwvat7aiaPz6Q/BAT9qhsgUAJXA+Dj+MBeNC/ooMjvQjczyIAiiB/PgaqwG4EuRb25aoBI1BiMOE/2uD/gHluMnGzpFJbLGBJFfFz+q5o7Tk4997/P1E3ffWAPKBzuXTlzr/0BCpKHlKpACepyf5TpX/JdPUbllOsloBWA7BilnPnVpYeQMkEytFA+GDyUFLBlh3ovmGsyXnTsay+sG5d4+ZtPHoegE8KeYF5N25wbcHIqB97NnRdXlj2Q0s4JN+n6JIISjaw7lHdCjVTsvucwoUxqTtRe6FJPHCFFvtK+ZdLVXuSY8S2h+/goSI3KBcccycwwhpWu1hocoJYNc+Td51HFMOQ+KQuc7LoKYOg9zUH+MFWaVUolvqu9H29tWd4/Ilwz7vghdba4OBsUSTvHx0AMpvasLleVGvDATzxmrtBHnbpZXY78dgGJ31A/xgNPGbzMkrfGxU5+MXV/EHl8XllBkpNDUBsDdL4capZV7C2kRGN5wvJBwnenBsoo4WBnMzQbg66ubxRlILzD1Um0lpn/1qU6HBb7tC67J6AaWkaxG/Izug34x6OyVDMKetme5+H/thDAlf/lwqPY6yZXm9tQ7EoEIHim0B5VI/+zEMJOWvPwtPGWg74XNVCRnFvI2b9lIPQYGBqxdh1DSB7YIZ6Qx/6MZyoBgGtnx/CuM3yFuVmvuT20YOBD4BNnQJ/dLNe3Fit5Y2sGRc5U0m4PN/ggcUSO3zFBGUlxVermrTPtnMSNOvoqYiZcfrPUReyXKtqNAOLl9y+jLjk4O7ZH1bAgrsSrkUpo7itxBkpH7B3mq2+xepHGfcljCTlRAZuyZGWYP256eA2CdZ3uRKxmkvOH68xoQHLgTpZ7n+LpY0tfh0v2KcskydTxHNaFMVTgBd7bfp6qGGrb2wONxtThGc0EWed48GYzh9MkGMd+7JuDMHCP6HYU7v1AALXiiEo1PcMUk3DKeKAYpFWzvrpMXImaHZrArA0xQsmW7zcDGlphnfjs3KmBGoG0UFBkEKB2A1szbOlRAnAbC8YMqVjig40/9XHt0y5zA9TOHWobdHs/OvAddw7/CN/5ThFvKgD4DXQnYScv2KSKPg44iOmPpXdulVQsWtjLqSa+A3T855nxFuWFJrM6eGzqnCwtYoeLr5JJDDvN79LlBc81ZBHL+ZeG9W+R0k4BfwsOcJxSlQnnCc/NqFlo97HytU6uoTpYBeIM+3SpxleVZ9dZbQnIaTfkm8uTtwfrdezsinVNI3ORd+JIWKgGwNFB3ebuxfmN9JuphygIt68jxamky0XUq9eAz6u5t6/UVtI7KE+btO9X/MK3mZseh4G1Bijhv+vrMqNWODjO1hvJ7PMY7758pRhP2sPckOlyHbQcdmM4QFJwrgHmOEi6n23riovQM51btdUys0bJCF3FtZJ0Aj9AMDR8EqaDDsVC45lYlLU13N2Aq4PegDdXmK/gxC6Xr6eiI90BKA4WGomDdAOXTpybisKVc3heyA+NpCdrvzHIwbxErltJpxJYL5RWKlsbBhSrbppWVdLJn8jhFV4l3Hse6h/MfQUcOALp6FD73B/WHhR98KApsHU7Thf7JLmlKrBJgtotoZlEsQ+9O+nhsHQK1arVkpDwY5kH3kRwQ8jdBdnFFg8bBxJqMKflgJI0kgkSqWatuNd6nLsM7L4Gpl9AHyz/TLF2qkLtZO9eaNRRXGLpi5IYWIywDod84+lQ78d3vBIo1VnAXskOg4lQjm6LPA3eHZo96mznu8RcJRbVoHcl7ySbp1gevWwtAHakxRRlckRqTt/+wa+xoTI2QiaK/+QsQYBR6sD40CdobP0q3Qe2nCa+5mjCN6dBIz7LaILwmDulh38v08KEk4akd9xEk9eFevNu6bTLlb7bleYb62OXCssKWFOQ3rwNoBN9vZSD3KKzNIp2Y2JhCu+j2faNwS4VTwIXi5Wb2Wz4na5CWrVUfDLwrmAvCFK6Yz/LacRQtcBqf/qLVNl9fAPLqoKcBLfQu+H3VfD8UKwS40IEdeT5g1AJgQSSda3m5qpQg7Ugjlsd4AkrJB7Sc37W+nT3YnuftDDUhDh0q78GhkO4SpwHcc9NJiomg4/EcuZQTP/b0ADLxhrVGkdIkSWDfozzO5TRqC9PavZik88JVdcUjbWFB7bEkcJHtXBD+g0/Q2Af8aFjC71IWOGIDXNuuh80fqMkhBov1IyKlC3zszOG1tzi1rFzWmiEg5MkxCL8r44KkTlPsgEK35aFG9NkfCTXwu/Uf2njoJyFlgC3qyyLantElXgG2SI+WsjkKUpTF+Oj2NHtfpWzEZCJaVgeUqqqW59tvJRXf70RmvMCCRxlhO+z6HfTBk+vJ5GBLz6r7wnS1yzdGaWuBB4nMHlyrI8YA4YdSY/0BxyQpIIBUTCCAU2gAwIBEqKCAUQEggFA3c/h912myE7gNfeGkhZO7M3wxwjRntNhRWwzP0Z15t/11jUWZ22gggkNhct4IbNR902eI8nEGfSZwiHdKAp78JkDWNh6wCzVaurdrfdmpXl04LGalz6m2NGnF4KRiHoj42gn+WhJp3GR6g0uofLEW7GvR48rdknbB79ZIJ761Qs08/EymHZ5iph5Wfl5xantYJWhsH7z7/Iib+AZQn+dUihMkO/9RoZTt778y/sIXRgRAzZkKTaTuzmHJTxOe5DafW2oRqQ9BAUWryuA99uM3k/Uv0G/Hk2MAV5Z38B0VVtz7HDsn9Tk8hQsPNYiv2NPpU4ErYybsWiW/SLSuk8kdk/9Eh2WMS/dQsKwk9kph34VfLpG0cpyKAMJ7JCwIicN2xh4EhDrzQjY5mPx+crSp7AH7WSZytg7w26bWs1r70w=
Origin: http://helpdesk
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
content-type: multipart/form-data; boundary=------multipartformboundary1452094914429
Accept: */*
Referer: http://helpdesk/scp/tickets.php?id=6240
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
Cookie: __utma=44521701.816203928.1415654462.1418652656.1418668361.12; __utma=114299931.816203928.1415654462.1433265854.1433265854.1; __utma=43166241.816203928.1415654462.1441289049.1444140990.11; __utmz=43166241.1444140990.11.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); AMCV_774C31DD5342CAF40A490D44%40AdobeOrg=793872103%7CMCIDTS%7C16725%7CMCMID%7C46140873415794192773181877669542201920%7CMCAAMLH-1445620433%7C7%7CMCAAMB-1445620434%7CNRX38WO0n5BH8Th-nqAG_A%7CMCAID%7C2B10982705078697-40000107A001292E; s_fid=3EF5D888E3167B3A-2F0E736D25473DBD; _ga=GA1.2.816203928.1415654462; __unam=730c264-14abb27af44-2db8bdff-59; SESS455fa24d46601a50c55b1e4d094fa904=3JhuaS7WQBbh6FRUC_GJDP1zfoBu3xXIjIEPy2XJxME; OSTSESSID=0j1lhpu6hjisf1kaceaegvh8e6
```

**Comment by jround** [comment] 2016-01-12 16:55
I have just installed the latest Google Chrome beta (Version 48.0.2564.71 beta-m (64-bit)) which seems to resolve the issue.  Could someone else try and post their results?

It would be easier if an osTicket fix could be found however as I find pushing out Chrome updates to all our PC estate can be a little flaky at the best of times!

**Comment by twjenn2** [comment] 2016-01-12 18:10
I just downloaded the Chrome Beta as well and tested file uploads.  Everything is working as it should with this beta version.  I'm running Version 48.0.2564.71 beta-m (64-bit).

Thanks for the update, jround!  I can't push the Chrome update since it is unreliable, but I will hold out hope that the next update or two for Chrome will fix the issue.

**Comment by infectormp** [comment] 2016-01-14 07:59
I have the exact same problem with Chrome 48.0.2564.79 beta-m (64-bit) and FF 45

**Comment by infectormp** [comment] 2016-01-14 08:10
IE give me same error

**Comment by flaviohayashi** [comment] 2016-07-08 13:13
I was facing same error message using nginx.

added the following part to osticket.conf for nginx and solved the problem

if ($request_uri ~ "^/.*\.php(/[^\?]+)") {
    set $path_info $1;
}

**Comment by komodin** [comment] 2016-08-24 09:45
Same problem here, using Apache 2.4.23 (cPanel version) with PHP 5.4.45 (PHP-FPM via socket, cgi-fcgi using mod_proxy_fcgi).

To enable PATH_INFO with Apache 2.4 using FastCGI to connect to PHP-FPM sock, I have to set the EnvVar proxy-fcgi-pathinfo.

On the VHost, into the IfModule mod_proxy_fcgi.c, I put the SetEnvIf for the support subdir (where I have the osTicket):

SetEnvIf Request_URI "support/.*" proxy-fcgi-pathinfo=1

The test URL is like: test.com/support/setup/test.php/asd/
The problem is, if I have PATH_INFO unset, the PHP_SELF variable is correctly set: /support/setup/test.php/asd/ and PATH_INFO empty.

And, when I have PATH_INFO set (with the SetEnvIf on the httpd.conf VHost), the PATH_INFO is correctly set: /asd/ , but, the PHP_SELF is broken: /home/testcom/public_html//support/setup/test.php/asd/

And the expected result has to be like this:
PHP_SELF: /support/setup/test.php/asd/
PATH_INFO: /asd/

Anyone are running the same environment and has the same problem?

**Comment by komodin** [comment] 2016-08-24 10:16
I've made this workaround for the get_path_info function, based on this solution for another framework made by @nadavkav https://github.com/simplesamlphp/simplesamlphp/issues/5#issuecomment-135205300

```
if (preg_match("/^(.+\/.*\.php)(\?)?(\/.+)$/", $_SERVER['REQUEST_URI'], $possible_pathinfo)) {
	$pathinfo = $possible_pathinfo[3];

	if (preg_match("/(.*)\?(.*)/", $pathinfo)) {
		$pathinfo = substr($pathinfo, 0, strripos($pathinfo, "?"));
	}

	return $pathinfo;
}
```

You have to put it on the include/class.osticket.php file, behind this:
```
        if(isset($_SERVER['ORIG_PATH_INFO']))
            return $_SERVER['ORIG_PATH_INFO'];

        //TODO: conruct possible path info.
```

**Comment by nadavkav** [comment] 2016-08-24 11:39
@komodin , thanks! very interesting. I will check it out.
@AviMoto, I think this will be interesting to you too.

**Closed** 2020-01-06 20:11 UTC
Labels: Attachments, cause unknown
