### ISSUE TITLE
Attachment removed after edit thread

### ISSUE THREAD

**Issue by luiizfenix** [osTicket/osTicket#4155] opened 2018-02-09 21:05 UTC
Description

Attachment lost while editing ticket. 
This a a duplicated issue since no one seems to care about this issue calling it a duplicate from a fix that is no longer working. 

When editing a ticket the attachments are lost/removed.
i've already tried stable v1.10.1 clean install, upgrade from 1.10 stable, linux server, windows server, no modifying anything from the code. The actual code has the fix in #2888 so it might work properly but it doesnt. 

i see #3836 and #3921 open issues but both have only @ntozier comment about being a dup from #2888 even when they said issue is not fixed.  

### Steps to Reproduce

1- Created Ticket : Add attachments
2- Edit Ticket : add more info and updated
3- Result : remove all attachment from custom form. remains as a database entry

**Expected behavior:** [What you expected to happen]
attachments not being removed. 

**Actual behavior:** [What actually happened]
attachments are on database but not in the ticket. 

Production server with the issue:
![image](https://user-images.githubusercontent.com/32772585/36050051-f447d76a-0db2-11e8-81cb-c537e27aad67.png)

**Comment by ntozier** [comment] 2018-02-12 15:50
If this is a dupe then please close it.  Update the existing thread.

**Comment by cbiere** [comment] 2018-03-29 13:19
This bug is NOT fixed. I'm using the Knowledge Base as central point for all documentation. If the attached documents are not safe there, this feature is complete and utter useless. This should be disabled until it is fixed.

**Comment by JediKev** [comment] 2018-03-29 14:21
@cbiere 

By going to the database, looking for the `ost_file` record by the `name`, getting the `key` value for that record, and grepping for that key in your attachment directories.

Cheers.

**Comment by rockmanchile** [comment] 2018-06-07 18:17
i have moved a large amount of information and upload manually a hundred files and after a week i start getting complains about the missing ones...its a critical failure for osticket!....i been searching for a solution deep in the code but im about to give up and rollback to 1.9....its probabley something hard to fix because this issue have been reported over a year ago but still no ost guru have been able to give a feasable solution...im a little worried.

**Comment by JediKev** [comment] 2018-06-07 18:18
@rockmanchile 

I've said this in a similar thread but I'll say it here again. This is a session issue and I think we have addressed this in the upcoming `v1.11.0rc-1` release. There is no set release date so please stay tuned.

Cheers.

**Comment by rockmanchile** [comment] 2018-06-07 20:40
thank you JediKev

**Comment by rockmanchile** [comment] 2018-06-19 18:56
this is by far the biggest bug in osticket that i have seen so far. I been using OST since the 1.8 version and never had a failure this big. I really hope that somebody can at least find a workaround solution, if not many IT admins are going to start looking for other alternatives. Its unthinkable to just sit and calmly wait for the 1.11.0rc-1 release.
Right know im trying to put an external form inside the ticket details so i can grab the files and store them in a dropbox or google drive account and still be able to access them quickly.

**Comment by alexdjachenko** [comment] 2018-07-20 18:59
We have found and fix this bug: it connect with fileid's linking.

пт, 20 июля 2018 г., 20:26 SimonOfHamburg <notifications@github.com>:

**Comment by rockmanchile** [comment] 2018-07-20 22:12
,,,,share the secret !!

**Comment by alexdjachenko** [comment] 2018-07-24 09:01
Send you a patch.
[osticket_attachments.zip](https://github.com/osTicket/osTicket/files/2222810/osticket_attachments.zip)

**Comment by luiizfenix** [comment] 2018-07-24 16:53
tried the above patch, same result. attachments gets removed after edit.

**Comment by alexdjachenko** [comment] 2018-07-25 09:13
It work at our osTicket 1.10.1, I've tested it just now: create comment for ticket with file, save and edit comment. Attachment stil here.
Brief notice of the error and patch:

- When you edit message, every next edition linked with first edition. Files linked only to first edition.
- (error) When you edit it, you don't attach new files, but osTicket try to attach it.
- (fix) Using previus editions as source of files.

**Comment by SimonOfHamburg** [comment] 2018-07-25 18:37
@alexdjachenko I think that we are not on the same page, yet. We are talking about *custom forms*. For testing, you need to create a custom form first (Admin panel -> Manage -> Forms -> Add new custom form). There, add a field with type "file upload". Once you have done that, you need to include this custom form into a help topic. Only then can you reproduce this bug (submit ticket for new help topic).

Attachments from standard ticket form (field 'Issue Details') don't get lost. Those attachments don't show up in edit mode either. But this is not what this bug is about.

Could you test again with custom form, please?

**Comment by SimonOfHamburg** [comment] 2018-08-01 16:54
@alexdjachenko , @JediKev quick feedback, anyone? Could you reproduce this bug with custom forms, field type "file upload"? Thanks a lot!

**Comment by gitsnow** [comment] 2018-09-29 05:14
I've tested JediKev's changes [issue: Custom File Upload Dropping #4406](https://github.com/osTicket/osTicket/commit/417f9d38a8123c38193371926f4cfed1d8566490) by manually editing include/class.forms.php on both 1.10.4 & 1.11.0-rc1 and this seems to fix the issue where attachments become un-associated when using custom forms with file uploads.

This only happens to me if there are previously uploaded attachments in the form and I login with a new session and attempt to upload a second attachment.

For 1.10.4 the relevant code starts on line 3986
For 1.11.0-rc1 the relevant code starts on line 4460

**Comment by geo782** [comment] 2018-10-15 12:08
Hi,
I have the same problem also after manually editing class.forms.php with 4406. 
In Default ticket's form, i have added a file field. If i edit ticket and add file, save and reedit ticket, save does not remove file. If i logout and login again and edit ticket, file is lost on save. In ticket history it says "File xxxxx removed". Also if file field is required for agents and edit ticket, ticket is not saved because file required although the file name is visible.
Version 1.10.2

George

**Comment by JediKev** [comment] 2018-10-15 13:49
@geo782 

This _should_ be addressed in the latest pull from `develop`.

Cheers.

**Closed** 2019-08-08 17:45 UTC
