### ISSUE TITLE
osticket task due date issue

### ISSUE THREAD

**Issue by edukondalugorla** [osTicket/osTicket#3431] opened 2016-10-28 06:20 UTC
Hi,
created tasks, due date is not displaying what i entered at creation time. task is creating duedate with db time zone. how to set due date what user entered.

**Comment by ntozier** [comment] 2016-10-28 13:48
Did you search the existing issues?
This sounds like it might be a duplicate of: https://github.com/osTicket/osTicket/issues/2799 
and https://github.com/osTicket/osTicket/issues/3429

**Comment by edukondalugorla** [comment] 2016-11-02 09:32
Due date is displaying. but wrong due date displaying.

**Closed** 2016-11-10 12:29 UTC
