### ISSUE TITLE
v1.10-RC.2  Installation error 500

### ISSUE THREAD

**Issue by d003232** [osTicket/osTicket#3144] opened 2016-05-20 19:14 UTC
I try to install a test system with v1.10-RC.2 

During the installation I get after 5-6 seconds a 500 error.

After modifying the display error value in /bootstrap.php from 0 to 1
`#Don't display errors`
`ini_set('display_errors',1);`
`ini_set('display_startup_errors',1);`

I get the error message:
`Fatal error: Class name must be a valid object or a string in /mnt/web4/c0/00/51140000/htdocs/scheuermatthof_de/osticket-test/include/class.i18n.php on line 161`

Any help?

**Comment by mfelber** [comment] 2016-05-20 19:30
v1.10-rc2 is really old (last year august). 1.10 isn't still ready for productive use because the development has not finished.
When you wan't to try 1.10 I would recommend to use the latest version of the develop-branch, this is actual the 1.10 branch. 

You can get it for example via the green button (Clone or download->Download ZIP).
Installing with a language pack doesn't work yet. You only could add the language after the installation.

**Comment by d003232** [comment] 2016-05-20 19:39
OK. I just installed again the develop branch ... 

... and get exactly the same error message.

**Comment by mfelber** [comment] 2016-05-20 20:30
I can run this installation without problems (using no language pack).
What PHP Version do you use? I have tested it using PHP 5.5.27 or 5.6.12..

The error occurs in the class.18n.php which is used for the language packs.
Do you really made a fresh install (new or clean db) without language pack?

**Comment by d003232** [comment] 2016-05-20 20:41
I deleted all tables. And just installed the develop-branch. No language pack. In the installation script there is only the language selection 'English - US (English)'.

I'm using PHP 5.5.35

AND in the right top corner of the installation page I see the text 'Installing osTicket 1.8-git' ???

**Comment by d003232** [comment] 2016-05-20 20:41
I deleted all tables. And just installed the develop-branch. No language
pack. In the installation script there is only the language selection
'English - US (English)'.

I'm using PHP 5.5.35

AND in the right top corner of the installation page I see the text
'Installing osTicket 1.8-git' ???

2016-05-20 22:30 GMT+02:00 mfelber <notifications@github.com>:

**Comment by mfelber** [comment] 2016-05-20 21:05
All versions from github are marked as osticket 1.8-git, this is normal.
I can't imagine why the install should fail. 

Sometimes it is a browser issue,  clearing the browser cache should help then.
Reusing the config file from the last install could also be a problem (ost-config.php).

**Comment by d003232** [comment] 2016-05-21 11:43
Now I get it! 

I reuse a new ost-config.php from the sample (but I'm also sure I did that before because I deleted all and installed it completely new)

And I called the install script from Intenet Explorer instead of Google Chrome (I couldn't understand what could be a browser issue?)

Anyway. Now it works. Thx for your great and enduring help @mfelber

**Closed** 2016-05-21 11:44 UTC

**Comment by maurium36** [comment] 2017-04-27 17:45
Hi!
Having the same problem. Which ost-config.php did you finally used?  Not finding it on the sample.
Thank you!

**Comment by ntozier** [comment] 2017-04-27 17:58
This is a closed issue report.  I'm not sure what you are asking.

**Comment by jorgeomarmh** [comment] 2018-05-03 18:53
If you used a language pack that is probably the cause, you can install osticket with the default language and then change the language.
Greetings.
