### ISSUE TITLE
osTicket Core, v1.10-rc.2 TimeZone issue

### ISSUE THREAD

**Issue by philbertphotos** [osTicket/osTicket#2513] opened 2015-09-02 05:24 UTC
I having a problem with getting the proper time on tickets and cant see why its caculating it that way when as far as I can tell every thing is correctly set.
Current Time on Ubuntu 14 server TimeZone America/St_Thomas
## Wed Sep  2 01:18:30 AST 2015

php.ini
[Date]
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
## date.timezone = America/St_Thomas

TimeZone Settings
## ![09022015-010912](https://cloud.githubusercontent.com/assets/2892474/9623584/d9a8f576-5110-11e5-8bff-c5f82c067f82.png)

Ticket created moments after 

![09022015-010954](https://cloud.githubusercontent.com/assets/2892474/9623612/33d8215c-5111-11e5-9baa-3f923bc759c8.png)

**Comment by jdelhome3578** [comment] 2015-09-02 11:54
Check the agent timezone

**Comment by philbertphotos** [comment] 2015-09-02 15:49
Agent time zone is the same

**Comment by jdelhome3578** [comment] 2015-09-02 16:10
Can you show a screenshot of the system information for osTicket?

**Comment by philbertphotos** [comment] 2015-09-02 16:47
Ask and you shall receive :)
![screenshottimezone](https://cloud.githubusercontent.com/assets/2892474/9637770/af7492c8-5170-11e5-9698-985d036aa92d.png)

**Comment by philbertphotos** [comment] 2015-09-09 17:43
I will do some debugging in the code and see if I can provide anymore info.

**Comment by mckaygerhard** [comment] 2015-09-09 18:57
i thinks th eproblem are in the date definitions on the i18n files, i dont know why the date definitions are set as that way!

here another problem related due that #1347

**Comment by philbertphotos** [comment] 2015-09-12 02:33
include/class.misc.php I change the minus to a plus and if FIXED my issue I will look at it later to see if it will work with other timezones...

    /* misc date helpers...this will go away once we move to php 5 */
    function db2gmtime($var){
        static $dbtz;
        global $cfg;

        if (!$var || !$cfg)
            return;

        if (!isset($dbtz))
            $dbtz = new DateTimeZone($cfg->getDbTimezone());

        $dbtime = is_int($var) ? $var : strtotime($var);
        $D = DateTime::createFromFormat('U', $dbtime);
        if (!$D)
            // This happens e.g. from negative timestamps
            return $var;

        return $dbtime + $dbtz->getOffset($D);
    }

**Comment by greezybacon** [comment] 2015-09-18 21:00
This is a duplicate of #2440

**Comment by rayfoss** [comment] 2016-12-06 20:56
Closing duplicate issue, please continue the conversation on the ne

**Closed** 2016-12-06 21:04 UTC
