### ISSUE TITLE
can fetchEmails  function  fetch all email in box？

### ISSUE THREAD

**Issue by iamMarkchu** [osTicket/osTicket#5400] opened 2020-03-10 06:10 UTC
can fetchEmails  function  fetch all email in box？

**Comment by JediKev** [comment] 2020-03-10 13:55
@iamMarkchu 

Of course. Configure your email in the Emails tab, set it to fetch say 20 emails at a time, and then configure the system to move mail to a different folder post-fetch (this is important). Once you do this the system will fetch 20 emails, move them to a different folder, then fetch another 20 emails, move them, and this repeats until all emails in the Inbox have been fetched/moved.

**Edit:**
I'm closing this as this is more of a question and not a Bug Report/Feature Request. If you would like to ask questions, Github is not the place. Instead, you should ask on our [Forum here](https://forum.osticket.com).

Cheers.

**Closed as completed** 2020-03-10 13:56 UTC

**Comment by iamMarkchu** [comment] 2020-03-10 14:07
ok， thx！ 
last question，how to configure the system to move mail to a different folder，if i don't move, osticket will only read the latest 20 email in mailbox?  it's right?

**Comment by JediKev** [comment] 2020-03-10 14:54
@iamMarkchu 

>last question，how to configure the system to move mail to a different folder, 

Via the Fetched Emails section (**Note:** 90% of the time the folder has to exist in the mailbox first before attempting to save in osTicket):
<img width="518" alt="Screen Shot 2020-03-10 at 09 50 47" src="https://user-images.githubusercontent.com/11823401/76325099-ed1da600-62b4-11ea-8043-f874f7f95eb1.png">


>if i don't move, osticket will only read the latest 20 email in mailbox? it's right?

Correct.

Cheers.
