### ISSUE TITLE
Installer chokes in PHP>=8.1 with display_errors = On

### ISSUE THREAD

**Issue by mike-matera** [osTicket/osTicket#6574] opened 2023-06-29 19:03 UTC
### Prerequisites

* [ x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [ x] Do you have any errors in the PHP error log, or javascript console?
* [ x] Did you check the [osTicket forums](https://forum.osticket.com/)?
* [ x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

If PHP has `display_errors = On` then running the following results in a broken installation:

```console
$ php manage.php deploy --setup /var/www/htdocs/osticket/
```

The current directory also contains a big nasty directory that seems to have been named after the deprecation warning.

### Steps to Reproduce

1. Follow the installation procedure in `README.md` with `display_errors = On`

**Expected behavior:** A working installation 

**Actual behavior:** A broken installation 

### Versions

I have seen this problem with `v1.17.3` and `v1.18` with PHP >= 8.1

The problem can be seen when building with the official [PHP container](https://hub.docker.com/_/php) if you have not selected the production mode.

**Comment by JediKev** [comment] 2023-06-29 19:05
@mike-matera 

Probably because of the deprecation warnings. Can you configure your PHP to suppress Notices and Deprecations and retest?

Cheers.

**Comment by nikosch86** [comment] 2023-07-02 06:09
I can confirm this bug and can confirm that suppressing Notices and Deprecations solves the issue.
Since the install guide suggests using php 8.1 and the install breaks because of the messages, this is kind of important I would say ;)

**Comment by JediKev** [comment] 2024-11-20 22:21
@mike-matera

Thanks for the report! This has been addressed with the following:
- https://github.com/osTicket/osTicket/pull/6767

To note, this will be included in the next set of releases.

Cheers.

**Closed as completed by JediKev** 2024-11-20 22:21 UTC
