### ISSUE TITLE
[Feature Request] SLA

### ISSUE THREAD

**Issue by justfor-it** [osTicket/osTicket#6524] opened 2023-04-20 09:50 UTC
Good morning,

Is it possible in the future to create an additional status on which the SLA does not continue. Like when waiting for a customer.

Thanks a lot

**Comment by JediKev** [comment] 2023-04-20 13:15
@justfor-it 

This is a duplicate of [this issue](https://github.com/osTicket/osTicket/issues/3034). Please do a recursive search before creating an issue to avoid duplicates.

Cheers.

**Closed as completed by JediKev** 2023-04-20 13:15 UTC
