### ISSUE TITLE
v1.10 - Image PASTE not working - from filesystem

### ISSUE THREAD

**Issue by mlipok** [osTicket/osTicket#3481] opened 2016-11-08 09:23 UTC
I took a screenshot from an app and I wanted to paste the screenshot to the ticket.
There is a small "progress bar" rather than a spinning wheel - which means data is being uploaded....
but the image does not appear on the edited ticket's content :(

**Comment by ntozier** [comment] 2016-11-08 14:54
This is a redactor feature and should be addressed upstream with them (@jedikev @protich).  In the meanwhile if you simply click the insert image icon and drag and drop the image you should have better luck.

**Comment by mlipok** [comment] 2016-11-08 20:19
Thanks for answer 
I will try your solution soon.

**Comment by mlipok** [comment] 2016-11-21 11:58
Of course it works but I hope this will be fixed soon, as COPY PASTE images was one of the best feature in this HTML Editor.

**Comment by mlipok** [comment] 2016-11-21 12:17
I notice that I get this kind of error:

```

[INSERT INTO `ost_attachment` SET `file_id` = 6093, `type` = 'D', `object_id` = 15488, `name` = 'screenshot-NG9O']

Duplicate entry '15488-6093-D' for key 'file-type'<br />
<br />
---- Wsteczne śledzenie ----<br />
#0 (główny katalog)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (główny katalog)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
#2 (główny katalog)/include/class.orm.php(597): MySqlExecutor->execute()<br />
#3 (główny katalog)/include/class.attachment.php(161): VerySimpleModel->save()<br />
#4 (główny katalog)/include/ajax.draft.php(101): GenericAttachments->upload(Array)<br />
#5 (główny katalog)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
#6 [internal function]: DraftAjaxAPI->uploadInlineImage('15488')<br />
#7 (główny katalog)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#8 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('15488/attach', Array)<br />
#9 (główny katalog)/include/class.dispatcher.php(120): Dispatcher->resolve('15488/attach', Array)<br />
#10 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/15488/at...', NULL)<br />
#11 (główny katalog)/scp/ajax.php(262): Dispatcher->resolve('/draft/15488/at...')<br />
#12 {main}


```

But now this PASTE Image appears in editor.

**Comment by vieckzand** [comment] 2016-12-07 10:30
I have the same error when copy paste image from clipboard (DB Error #1062). Can anyone solve for this?
Thank you

**Comment by sjaakverhoog** [comment] 2016-12-08 08:42
Me to:
` DB Error #1062
[INSERT INTO `ost_attachment` SET `file_id` = 112, `type` = 'D', `object_id` = 184, `name` = 'screenshot-FfHO'] Duplicate entry '184-112-D' for key 'file-type'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')
 #1 (root)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)
 #2 (root)/include/class.orm.php(597): MySqlExecutor->execute()
 #3 (root)/include/class.attachment.php(161): VerySimpleModel->save()
 #4 (root)/include/ajax.draft.php(101): GenericAttachments->upload(Array)
 #5 (root)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))
 #6 (root)/include/class.dispatcher.php(145): DraftAjaxAPI->uploadInlineImage('184')
 #7 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('184/attach', Array)
 #8 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('184/attach', Array)
 #9 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/184/atta...', NULL)
 #10 (root)/scp/ajax.php(262): Dispatcher->resolve('/draft/184/atta...')
 #11 {main}`

**Comment by JediKev** [comment] 2016-12-08 16:57
Could you please describe your environment and osTicket version as I can not reproduce this issue.

**Comment by sjaakverhoog** [comment] 2016-12-08 17:23
![screenshot_2016-12-08-18-20-39](https://cloud.githubusercontent.com/assets/9580505/21020112/5a31d1f2-bd73-11e6-8f58-97c5b8ecd40f.png)

**Comment by JediKev** [comment] 2016-12-08 17:49
Are you trying to copy and paste on that tablet/phone or on a computer?

**Comment by sjaakverhoog** [comment] 2016-12-08 18:48
No on a PC.. But i wasn't close tot my PC when your asked for more info. I want tot paste a received email from outlook with images inside the text. When i paste everything i see dubble "enter" lines and no images.

**Comment by JediKev** [comment] 2016-12-08 21:57
Ok, firstly I'm running CentOS 7 with Apache and osTicket v1.10(latest) and I'm able to paste images all day long with no errors. You need to explain your environment in more detail so we can further try to replicate that issue.
Secondly, we do not support pasting from a Word Document and keeping its format and attachments.

**Comment by sjaakverhoog** [comment] 2016-12-09 08:02
Ok i think it's an Office issue. It only happens when i try to paste an e-mail from outlook. It is possible to paste images from other sources. [https://www.youtube.com/watch?v=0cHITSkZ72s](url)
This is what happens (see video).
Is there a workaround for this? Maybe with another WYSIWYG editor?

**Comment by ntozier** [comment] 2016-12-09 14:13
more reports here: 
http://osticket.com/forum/discussion/89263/db-error-inserting-picture-in-topic

**Comment by thinkfuture** [comment] 2017-01-31 14:52
Is there an update on this issue? Find it hard to believe that such a key element is lacking in the editor for a support application. Please advise.

**Comment by jane-t** [comment] 2017-03-30 11:18
I am also getting this error.   I am trying to paste images from the clipboard (screen grabs) they do not exist as files on my Windows PC,  I just grab them with a screen grabber, copy the image to the clipboard and try and paste into the Editor  (this worked fine with 1.8 which we were running previously to updating to 1.10)

**Comment by mlipok** [comment] 2017-04-07 17:33
Try to paste them several times.
This should works sometimes, at least it works in this way for my case.
Could you confirm that this works in this way ?

**Comment by jane-t** [comment] 2017-04-09 08:57
Thanks pasting twice does work.

**Comment by 2ge** [comment] 2017-05-05 04:34
I got same problem with v1.10-47-gb9f0937 (b9f0937), is there some fix ? - I have English pack installed only (default)

```
[INSERT INTO `ost_attachment` SET `file_id` = 331, `type` = 'D', `object_id` = 142, `name` = 'screenshot-lgbA']

Duplicate entry '142-331-D' for key 'file-type'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(597): MySqlExecutor->execute()<br />
#3 (root)/include/class.attachment.php(161): VerySimpleModel->save()<br />
#4 (root)/include/ajax.draft.php(101): GenericAttachments->upload(Array)<br />
#5 (root)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
#6 [internal function]: DraftAjaxAPI->uploadInlineImage('142')<br />
#7 (root)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#8 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('142/attach', Array)<br />
#9 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('142/attach', Array)<br />
#10 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/142/atta...', NULL)<br />
#11 (root)/scp/ajax.php(262): Dispatcher->resolve('/draft/142/atta...')<br />
#12 {main}
```

**Comment by kest874** [comment] 2017-05-05 12:10
Have noticed, if you past first then add your text it works every time.

**Comment by pespi123** [comment] 2017-05-11 06:50
It also works, if you past on the same line as the text you previously wrote. The editor automatically adds a break before the image (tested in Chrome and Firefox).

This doesn't work, if you already tried to spam the image into the editor before...

**Comment by mlipok** [comment] 2017-05-11 07:19
Big thanks this is just:
Eureka !!

**Comment by balojs** [comment] 2017-05-11 15:02
Same problem

**Comment by mlipok** [comment] 2017-05-11 17:20
@balojs could you also confirm that @pespi123 solution works for you ?

**Comment by eptiliom** [comment] 2017-05-17 13:11
@mlipok The above solution does not work for me.

![image](https://cloud.githubusercontent.com/assets/487265/26155357/78abe8ce-3ad8-11e7-8c21-8ec6a3fc83d6.png)

**Comment by eptiliom** [comment] 2017-05-17 18:41
Alright I think I see why this is happening.

In class.attachment.php in the upload function there is no checking to see if the image was already saved. So every time it tries to save it tries to insert the image again with the same file name that it generated before.

I added the following below line 157:
```
$existing = AttachmentFile::lookup($fileId);
if($existing != null) {
    $i[] = $fileId;
    continue;
}
```

Im certain that this isnt the best way to fix it but I dont know php.

This still doesnt help firefox but I think that is a javascript problem.

**Comment by rjkunde** [comment] 2017-06-19 19:09
Also observing this behavior, has anyone identified a fix yet?

**Comment by mlipok** [comment] 2017-06-19 19:37
For me works @pespi123  solution.

**Comment by dbummy** [comment] 2017-08-22 22:27
I don't think that this is the true proper solution but it does work for me and I think it would point anyone who knows anything about Javascript to the true solution for this problem.  Hope this helps.
![image](https://user-images.githubusercontent.com/24436109/29590357-0587b61a-875f-11e7-9c24-46dbdc8b8dca.png)

**Comment by mlipok** [comment] 2017-08-23 08:38
Hope @JediKev  will look here soon.

**Comment by JediKev** [comment] 2017-08-23 18:58
@mlipok, does @dbummy's solution work for you? I'm unable to replicate this issue so I need someone else to test this!

**Comment by mlipok** [comment] 2017-08-23 19:32
On first glance:
Yes it fix the issue - but no entirly.
I mean this is very useful fix which make it more user friendly as this starts to work.
But after quick testing there are situation when I still get errors like this:
[INSERT INTO `ost_attachment` SET `file_id` = 8493, `type` = 'D', `object_id` = 90]

> 
> Duplicate entry '90-8493-D' for key 'file-type'<br />
> <br />
> ---- Wsteczne śledzenie ----<br />
> #0 (główny katalog)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
> #1 (główny katalog)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
> #2 (główny katalog)/include/class.orm.php(597): MySqlExecutor->execute()<br />
> #3 (główny katalog)/include/class.attachment.php(161): VerySimpleModel->save()<br />
> #4 (główny katalog)/include/ajax.draft.php(101): GenericAttachments->upload(Array)<br />
> #5 (główny katalog)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
> #6 [internal function]: DraftAjaxAPI->uploadInlineImage('90')<br />
> #7 (główny katalog)/include/class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
> #8 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('90/attach', Array)<br />
> #9 (główny katalog)/include/class.dispatcher.php(120): Dispatcher->resolve('90/attach', Array)<br />
> #10 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/90/attac...', NULL)<br />
> #11 (główny katalog)/scp/ajax.php(262): Dispatcher->resolve('/draft/90/attac...')<br />
> #12 {main}
> 

But I can confirm that this qucik fix help me a lot and is very helpfull.
Thanks @dbummy

**Comment by mlipok** [comment] 2017-08-23 19:47
@pespi123 said:

> This doesn't work, if you already tried to spam the image into the editor before...

I can confirm that in @dbummy fix , the problem with multiple insterting the same Image is also fixed but, only if you paste it quickly multiple times.

**Comment by mlipok** [comment] 2017-08-23 20:54
Thanks for your involvment @dbummy .

**Comment by dbummy** [comment] 2017-08-23 20:55
No problem.  Glad I can help!

**Comment by dbummy** [comment] 2017-08-23 21:53
I'm using MariaDB (I've mushed osTicket with Snipe-IT to handle asset management) so I don't know if that has any influence on the error 1062 or not.  I did add 

'OLD_MODE'		=> 'NO_DUP_KEY_WARNINGS_WITH_IGNORE'

to /include/mysqli.php (around line 77) as described here: https://github.com/osTicket/osTicket/issues/3193

and I have not gotten any more 1062 errors (as of yet) and I have been paste happy all over testing.  Seems like this has suppressed the error on my system but like I said, I am using MariaDB.

![image](https://user-images.githubusercontent.com/24436109/29640153-2953dece-8823-11e7-94d8-4f55e179ab76.png)

**Comment by fredricj** [comment] 2017-08-24 07:49
As I read the mariaDB manual NO_DUP_KEY_WARNINGS_WITH_IGNORE shouldn't help since it's not an INSERT IGNORE which causes the 1062 error

**Comment by dbummy** [comment] 2017-08-24 13:30
Interesting.  I will continue to test.  I still have not received any more with the change whereas yesterday by now I already had ~5-8 by this time.  I will continue to test and see if I can further pick apart the redactor-plugins.js file (this is where I believe that the errors and weird issues are coming from)  Thanks @fredricj !

**Comment by dbummy** [comment] 2017-08-24 15:28
Ok,  I was going off of my emails and not off the logs for the 1062 errors and they are still showing up (guess my email got tired of sending them).  I think that the pasting issue stems from Redactor trying to pick up where it left off after pasting the image.  I have tried at a few different installations of 1.10 running on different OSs hitting "Enter" 10 times and then try to paste it messes up every time.  Can someone verify that this is not true for all instances?
If anyone has any type of JS skills can you please look at redactor-plugins.js Lines 948 - 1072 and see if you can figure out what is going on before/after/during pasting an image from clipboard?  Thanks!

**Comment by vieckzand** [comment] 2017-08-25 04:56
I think the problem is when paste image after hit "Enter", if i type some character and paste image from clipboard without "Enter" i'm not get error DB Error #1062

**Comment by mmcgrath** [comment] 2017-11-07 23:59
I'm getting this too: fresh install (this morning!) 
![screen shot 2017-11-07 at 4 55 48 pm](https://user-images.githubusercontent.com/170995/32524423-d29aa554-c3dc-11e7-9642-16341f93d62e.png)

```
DB Error #1062
[INSERT INTO `ost_attachment` SET `file_id` = 14, `type` = 'D', `object_id` = 7] Duplicate entry '7-14-D' for key 'file-type'

 ---- Backtrace ----
 #0 (root)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')
 #1 (root)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)
 #2 (root)/include/class.orm.php(597): MySqlExecutor->execute()
 #3 (root)/include/class.attachment.php(161): VerySimpleModel->save()
 #4 (root)/include/ajax.draft.php(101): GenericAttachments->upload(Array)
 #5 (root)/include/ajax.draft.php(229): DraftAjaxAPI->_uploadInlineImage(Object(Draft))
 #6 (root)/include/class.dispatcher.php(145): DraftAjaxAPI->uploadInlineImageClient('7')
 #7 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('7/attach', Array)
 #8 (root)/include/class.dispatcher.php(120): Dispatcher->resolve('7/attach', Array)
 #9 (root)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/7/attach', NULL)
 #10 (root)/ajax.php(50): Dispatcher->resolve('/draft/7/attach')
 #11 {main}


```

Sorry - I don't have the necessary JS skills to even understand the problem, let alone fix it....

**Comment by Aka4Code** [comment] 2017-11-30 10:04
I can confirm this error - migrated from 1.9.8.1 to 1.10.1 and when I paste image from clipboard after I hit "Enter" then I get "DB Error #1062" - can't paste image:

```
[INSERT INTO `ost_attachment` SET `file_id` = 6930, `type` = 'D', `object_id` = 46194]

Duplicate entry '46194-6930-D' for key 'file-type'<br /> <br />
---- Wsteczne śledzenie ----<br />
#0 (główny katalog)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (główny katalog)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
#2 (główny katalog)/include/class.orm.php(597): MySqlExecutor->execute()<br />
#3 (główny katalog)/include/class.attachment.php(161): VerySimpleModel->save()<br />
#4 (główny katalog)/include/ajax.draft.php(101): GenericAttachments->upload(Array)<br />
#5 (główny katalog)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
#6 (główny katalog)/include/class.dispatcher.php(145): DraftAjaxAPI->uploadInlineImage('46194')<br />
#7 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('46194/attach', Array)<br />
#8 (główny katalog)/include/class.dispatcher.php(120): Dispatcher->resolve('46194/attach', Array)<br />
#9 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/46194/at...', NULL)<br />
#10 (główny katalog)/scp/ajax.php(262): Dispatcher->resolve('/draft/46194/at...')<br />
#11 {main}
```
![image](https://user-images.githubusercontent.com/11789024/33425098-01f193d8-d5be-11e7-8425-123b51e583fc.png)

Temporary solution is to type some character after I hit Enter, and before I paste image.

**Comment by CashDesk** [comment] 2017-12-03 15:11
Is there allready a solution for this issue? I have installed the latest version but still have this problem

**Comment by JediKev** [comment] 2017-12-08 20:14
Everyone, try this pull request and get back to me: https://github.com/osTicket/osTicket/pull/4113

Cheers.

**Comment by Stoolbend** [comment] 2017-12-11 12:10
Applied the new Redactor version from #4113 and image paste is now working on v1.10

When pasting images in one after another from Snipping Tool, it was pasting the image every other time but it was still pasting images in.

**Comment by Aka4Code** [comment] 2017-12-22 08:58
Installed changes from #4113 and problem with image pasting **DB Error #1062** still exists:

```
[INSERT INTO `ost_attachment` SET `file_id` = 7073, `type` = 'D', `object_id` = 46325]

Duplicate entry '46325-7073-D' for key 'file-type'<br /> <br />
---- Wsteczne śledzenie ----<br />
#0 (główny katalog)/include/mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (główny katalog)/include/class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
#2 (główny katalog)/include/class.orm.php(597): MySqlExecutor->execute()<br />
#3 (główny katalog)/include/class.attachment.php(161): VerySimpleModel->save()<br />
#4 (główny katalog)/include/ajax.draft.php(101): GenericAttachments->upload(Array)<br />
#5 (główny katalog)/include/ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
#6 (główny katalog)/include/class.dispatcher.php(145): DraftAjaxAPI->uploadInlineImage('46325')<br />
#7 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('46325/attach', Array)<br />
#8 (główny katalog)/include/class.dispatcher.php(120): Dispatcher->resolve('46325/attach', Array)<br />
#9 (główny katalog)/include/class.dispatcher.php(38): UrlMatcher->dispatch('/draft/46325/at...', NULL)<br />
#10 (główny katalog)/scp/ajax.php(262): Dispatcher->resolve('/draft/46325/at...')<br />
#11 {main}
```

**Comment by rjkunde** [comment] 2018-01-11 17:31
Sorry if I'm beating a dead horse here, but I've been trying to find a solution for quite a while.  My configuration is shown below. I've tried the two fixes mentioned in this thread: upgrading redactor to 10.2.5, and changing Line 964 in redactor-plugins.js.  When I upgrade redactor, the DB errors stop, but paste still doesn't function.  When I change line 964 in redactor-plugins.js, the first paste works, but subsequent pastes do not, followed by a string of DB errors.  Database errors shown below too.

Anyone have any other suggestions?  It seems like [redactor has been abandoned](https://github.com/html5cat/redactor-js): 

![image](https://user-images.githubusercontent.com/10871915/34837825-a339cf70-f6c1-11e7-9156-a46650f9cac8.png)

`INSERT INTO `ost_attachment` SET `file_id` = 2257, `type` = 'D', `object_id` = 10]

Duplicate entry '10-2257-D' for key 'file-type'<br /> <br />
---- Backtrace ----<br />
#0 PATH-TO-MY-OSTICKET-DIRECTORY\include\mysqli.php(204): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 PATH-TO-MY-OSTICKET-DIRECTORY\include\class.orm.php(3133): db_query('INSERT INTO `os...', true, true)<br />
#2 PATH-TO-MY-OSTICKET-DIRECTORY\include\class.orm.php(597): MySqlExecutor->execute()<br />
#3 PATH-TO-MY-OSTICKET-DIRECTORY\include\class.attachment.php(161): VerySimpleModel->save()<br />
#4 PATH-TO-MY-OSTICKET-DIRECTORY\include\ajax.draft.php(101): GenericAttachments->upload(Array)<br />
#5 PATH-TO-MY-OSTICKET-DIRECTORY\include\ajax.draft.php(300): DraftAjaxAPI->_uploadInlineImage(Object(Draft))<br />
#6 [internal function]: DraftAjaxAPI->uploadInlineImage('10')<br />
#7 PATH-TO-MY-OSTICKET-DIRECTORY\include\class.dispatcher.php(145): call_user_func_array(Array, Array)<br />
#8 PATH-TO-MY-OSTICKET-DIRECTORY\include\class.dispatcher.php(38): UrlMatcher->dispatch('10/attach', Array)<br />
#9 PATH-TO-MY-OSTICKET-DIRECTORY\include\class.dispatcher.php(120): Dispatcher->resolve('10/attach', Array)<br />
#10 PATH-TO-MY-OSTICKET-DIRECTORY\include\class.dispatcher.php(38): UrlMatcher->dispatch('/draft/10/attac...', NULL)<br />
#11 PATH-TO-MY-OSTICKET-DIRECTORY\scp\ajax.php(262): Dispatcher->resolve('/draft/10/attac...')<br />
#12 {main}
`

**Comment by Aka4Code** [comment] 2018-01-12 08:58
@JediKev Are you considering switching to another WYSIWYG editor? (https://summernote.org  /  
 https://quilljs.com  /  https://www.tinymce.com/  /   https://ckeditor.com )

**Comment by vieckzand** [comment] 2018-01-15 02:39
@Aka4Code if you want use tinymce, you can read this article http://osticket.com/forum/discussion/91133/plugin-tinymce. 
Now, i use that and so far solve copy paste image problem

**Comment by Aka4Code** [comment] 2018-01-23 08:57
@JediKev so why you don't wont to replace Redactor with TinyMCE? Someone already made plugin and as @vieckzand said it's working with osTicket....

**Comment by vieckzand** [comment] 2018-01-23 09:56
@Aka4Code I think the problem is size data in database when use TinyMCE as text editor to save image in text (image result from copy paste image). You can test what is different TinyMCE and Redactor. 
I already test for the same text with same image if i use redactor i get small size rather than TinyMCE.
Thanks

**Comment by JediKev** [comment] 2018-01-23 15:20
@Aka4Code because we have totally different plans ahead for the text editor. I can't reveal these plans just yet but know changes are coming soon for the text editor. Cheers.

**Comment by mlipok** [comment] 2018-01-24 07:22
I hope this editor will stay.
Or at least new new version will have editor with the same feature - "easy" image/screenshot paste .
On each forum/helpdes which I know the main problem is that I must ATTACH image and can not just PASTE them, and this is non efective way to work with computers "messaging/communication" systems.

**Comment by JediKev** [comment] 2018-01-24 14:49
@mlipok 

Trust me, attaching/pasting images will stay as easy as it is. The editor will just be way better, possibly have more features, and will _hopefully_ fix all the pasting issues seen recently. I'm glad most everyone is staying hopeful as we are putting a lot of work into the next few releases.

Cheers.

**Comment by mlipok** [comment] 2018-01-24 15:10
Thanks for your answer.

**Comment by davidegiunchidiennea** [comment] 2018-02-20 08:49
@JediKev your patch #4113 does fix the problem, thank you

**Comment by mlipok** [comment] 2018-02-21 12:35
@davidegiunchidiennea as you can read from last @JediKev response the DevTeam has taken a decision to change editor at all (as far as I understand @JediKev statement).
So be patient in waiting for new version.

**Comment by Aka4Code** [comment] 2018-10-25 09:34
@JediKev What's the status of this issue? Do you have any roadmap when you plan to release these changes in text editor?

**Comment by JediKev** [comment] 2018-10-25 13:42
@Aka4Code 

We never have/promise timelines for anything as we are always working on 1,000 things at a time, but it's coming. New/replacement text editor will be added in/after version `2.0`. No set release date or development date for this version as we are still trying to release `1.11.x`. Please stay tuned.

Cheers.

**Comment by Aka4Code** [comment] 2018-10-26 09:29
@JediKev I'm sorry, I misunderstood your previous message:
> I can't reveal these plans just yet but know **changes are coming soon for the text editor**.

-  This was back in January, ten months ago... 

I suppose if `1.11` is not yet ready, then version `2.0` and these changes in text editor will not come soon, at least not in next 2-3 years i predict :/ We have different understanding `coming soon` statement I'm afraid.

Thank you for detailing, and that you prove me wrong, so I know whats real status of this issue.

Cheers.

**Comment by JediKev** [comment] 2018-10-26 13:31
@Aka4Code

Well we do not have set release or development dates so all I can ever say is soon so...yea.

Cheers.

**Comment by osTicketRocks** [comment] 2018-11-05 14:51
I also do have the issues with copy+pasting a screenshot into the WYSIWYG editor.
However, I only experience the problem in Firefox (latest update but earlier versions as well).
In Internet Explorer or Chrome I don't have any problems.

I already tried updating scp.js & redactor.min.js with the informations provided by JediKev - but sadly I didn't help.
Is there any mandatory information about this issue regarding Firefox?
(The customer that uses osTicket is not able to install other browser so only FF or IE able).


Thank you very much!

**Comment by Aka4Code** [comment] 2018-12-05 09:12
@osTicketRocks this issue also exists in Chrome

**Comment by Aka4Code** [comment] 2019-02-22 09:52
@JediKev please remember about this bug, maybe next release it will be possible? 1.11 is great work!

**Comment by mlipok** [comment] 2019-02-22 12:58
btw.
I found that when I paste specyfic screenshot to ThunderBird email, and then copy them from ThunderBird then I have always no problem with pasting to osTicket.

**Comment by JediKev** [comment] 2019-02-22 14:43
@Aka4Code 

I still cannot reproduce this error. I tried with Mac, Linux, and Windows and I'm able to paste every time I did notice that you cannot paste a screenshot from a localhost site as it's not a publicly accessible image nor an image from the computer itself.

Cheers.

**Comment by CashDesk** [comment] 2019-02-22 15:00
We are using windows and Chrome browser. We have it inhere always. Never works. Myabe this info helps?

**Comment by Aka4Code** [comment] 2019-02-22 15:35
Our osTicket is not localhost - it's in publicly accessible hosting.

Image is pasted from clipboard - for example copied by Windows Snipping Tool 
or from some graphic editor like Windows Paint.Net.

**Comment by Aka4Code** [comment] 2019-02-22 15:37
Tested with Chrome and Windows 10 1809.
Same behavior with 1.10 and 1.11.

**Comment by JediKev** [comment] 2019-02-22 15:46
@CashDesk 

Unfortunately that does not help as I tested using the same and I'm able to paste.

@Aka4Code 

I just tested using Windows Server 2016, Chrome (latest), and Snipping Tool and it works just fine:
<img width="1247" alt="screen shot 2019-02-22 at 09 45 05" src="https://user-images.githubusercontent.com/11823401/53253381-b6172b00-3686-11e9-8a77-2cc5eadcc54c.png">

Cheers.

**Comment by Aka4Code** [comment] 2019-02-22 15:58
![image](https://user-images.githubusercontent.com/11789024/53254091-f8f6f400-36c2-11e9-8b01-a312e0f2d7dc.png)

This config helps anything? Can I deliver to you some other logs?

**Comment by JediKev** [comment] 2019-02-22 16:04
@Aka4Code 

Thank you for that but it doesn't really help as I tested using osTicket hosted with NGINX, osTicket hosted with Apache, and osTicket hosted with IIS all let me paste images from Snipping Tool just fine. I'm not sure where the issue lies for you guys as it's working for me and the "errors" you guys post are not detailed errors, rather, error codes.

The only thing that will be helpful at this point is detailed error logs and an example image.

Cheers.

**Comment by Aka4Code** [comment] 2019-02-22 20:31
How can I help? From what source you want this logs? Image I can deliver. Logs also, but I need to know from where you want me to get them. Apache logs/php logs/mysql logs/osticket logs or something different?

**Comment by JediKev** [comment] 2019-02-22 20:35
@Aka4Code

Any errors that are related. Just make sure they have details and not just an error code.

Cheers.

**Comment by thctlo** [comment] 2019-05-08 08:45
still errors in 0.12 ( but it works if you past 2x )

**Comment by ebonweaver** [comment] 2019-08-31 16:06
Happens if you reply to a ticket email.  Brand new install/setup.  Actually don't think it's the same issue but a ticket with this issue was closed as a duplicate so...

[INSERT INTO `ost_attachment` SET `type` = 'H', `object_id` = 11, `file_id` = 1, `inline` = 1]

Duplicate entry '1-11' for key 'file_object'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(199): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3455): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(658): MySqlExecutor->execute()<br />
#3 (root)/include/class.thread.php(1189): VerySimpleModel->save()<br />
#4 (root)/include/class.thread.php(1197): ThreadEntry->createAttachment(Array, 'powered-by-osti...')<br />
#5 (root)/include/class.thread.php(1665): ThreadEntry->createAttachments(Array)<br />
#6 (root)/include/class.thread.php(1677): ThreadEntry::create(Array)<br />
#7 (root)/include/class.thread.php(2748): ThreadEntry::add(Array)<br />
#8 (root)/include/class.thread.php(2963): MessageThreadEntry::add(Array, Array)<br />
#9 (root)/include/class.ticket.php(2692): ObjectThread->addMessage(Array, Array)<br />
#10 (root)/include/class.ticket.php(3099): Ticket->postMessage(Array, 'Email')<br />
#11 (root)/include/class.thread.php(571): Ticket->postThreadEntry('M', Array)<br />
#12 (root)/include/class.thread.php(839): Thread->postEmail(Array, Object(ThreadEntry))<br />
#13 (root)/include/class.mailfetch.php(845): ThreadEntry->postEmail(Array)<br />
#14 (root)/include/class.mailfetch.php(917): MailFetcher->createTicket(1)<br />
#15 (root)/include/class.mailfetch.php(997): MailFetcher->fetchEmails()<br />
#16 (root)/include/class.cron.php(25): MailFetcher::run()<br />
#17 (root)/include/class.cron.php(110): Cron::MailFetcher()<br />
#18 (root)/include/api.cron.php(19): Cron::run()<br />
#19 (root)/include/api.cron.php(40): CronApiController->run()<br />
#20 (root)/api/cron.php(23): LocalCronApiController::call()<br />
#21 {main}

**Comment by sjxiong** [comment] 2019-09-30 11:50
I have the same problem,  when I tried to paste a picture in email reply, I got this error:
![image](https://user-images.githubusercontent.com/15185770/65876277-2ad2e600-e389-11e9-9bc1-9365724f7029.png)

**Comment by JediKev** [comment] 2019-09-30 14:46
@mlipok @vieckzand @Aka4Code @davidegiunchidiennea @osTicketRocks @CashDesk @thctlo @ebonweaver @sjxiong

The new/improved editor is released with v1.14-rc1 available here:
- https://osTicket.com/download

It is an RC so we do not recommend running in production. You may install a new instance to test copy/paste with the new editor. If you find any issues, please do a recursive search in this repo first to see if there is an issue created for it already and if not create you’re own issue report. Make sure to fill out the entire Issue Template for the best possible assistance.

Cheers.

**Comment by mlipok** [comment] 2020-03-26 16:56
For now I can confirm that this problem is not occuring any more from time when we install v1.14.x
I think if any other user (@vieckzand @Aka4Code @davidegiunchidiennea @osTicketRocks @CashDesk @thctlo @ebonweaver @sjxiong) confirm that this is fixed .... then this ticket can be closed.

**Comment by dbummy** [comment] 2020-03-26 17:04
When I upgraded to 1.14, it fixed this issue for me.

**Comment by CashDesk** [comment] 2020-03-27 08:17
Upgrading to 1.14 solved the problem!

**Closed** 2020-03-29 14:10 UTC
Labels: MCE/Redactor, bug

**Comment by thctlo** [comment] 2020-03-30 13:50
Running 14.1 now and yes.. solved.
