### ISSUE TITLE
"My Tickets" shows team ticket that agent is not apart of

### ISSUE THREAD

**Issue by jakobii** [osTicket/osTicket#3480] opened 2016-11-08 05:26 UTC
Not sure if this was intentional. The"My Tickets" page shows all tickets(that the agent has department view permissions for) not assigned to a specific agent yet, even if the tickets is assigned to a team. 

**Example:**
Here I have a ticket that is assigned to a team 'Central tech support' and a department 'central'. awesome.
![teamexample](https://cloud.githubusercontent.com/assets/19825478/20087574/8ae3fd50-a52e-11e6-975e-7ea02629a3ed.PNG)

however I also have an agent who is **not** a member of the 'Central tech support' team but is a member of the 'central' department. But because the ticket is not assigned to a specific user the ticket is treated as unassigned and show up in the agents 'My tickets' becuase the agent has viewing rights for the 'central department'
![myticketexample](https://cloud.githubusercontent.com/assets/19825478/20087668/7b7b321a-a52f-11e6-947f-d136278baf38.PNG)

This pretty much makes the 'My Tickets' and 'Teams' features useless in my operation. I'm not sure if there is an easy way to fix this. any help would be great!

osTicket Version: **v1.10-4-g11de92f (11de92f)** 
Web Server Software: **Apache/2.4.18 (Ubuntu)**
MySQL Version: **5.7.16**
PHP Version: **7.0.8-0ubuntu0.16.04.3**

**Comment by jakobii** [comment] 2016-11-08 19:29
I download the osticket from osticket.com v1.10 (901e5ea). the problem still exists.

**Comment by bhenie** [comment] 2016-11-17 07:40
I have same problems there...

**Comment by dpthakar** [comment] 2016-11-25 12:08
I have same problem after upgrading to latest ver, is there any quick fix for this?

**Comment by jakobii** [comment] 2016-11-26 08:26
@dpthakar 
I basically ditched the use of teams altogether. I could not find a good fix. If you assign a ticket to an individual agent the ticket will not appear in other agents 'my tickets'. It kinda sucks because the idea of teams is really cool. 

You can get creative with your ticket filters and make the teams feature work, kinda... But it's difficult to filter tickets generated by email and it always created more work then it was worth in my operation.

**Comment by ipAnything** [comment] 2016-12-19 09:26
To me this whole My Tickets tab that includes tickets assigned to the Team makes no sense.

My tickets should mean MY TICKETS not My Tickets and other tickets of the TEAM.

There should be:

"My Tickets" - Only tickets ASSIGNED to ME
"Team Tickets" - Tickets ASSIGNED to the TEAMS I belong too.
"Unassigned Team Tickets" - Tickets assigned to the TEAM but not assigned to an Agent.

The concept is simple. I have a Team of Techs. 

1. When a new email request (or via Topic) is received it is automatically assigned to the Tech Team.
2. A notification is sent to all Team members
3. If one of the Team members is going to answer the ticket he claims it (or automatically claimed on first reply.
4. This ticket now belongs to this Agent and is handled by this Agent, unless transferred to another Team or Agent.

**Comment by ntozier** [comment] 2016-12-19 15:01
@ipAnything The concept is much simpler than that.
My Tickets is literally tickets that you have access to.  If you have access to it .... it is yours.  Why?  Because you could work on them.  Whether or not someone else has claimed it is rather irrelevant since Tickets can be assigned to both an Agent and a Department/Team.

**Comment by ipAnything** [comment] 2016-12-20 08:51
@ntozier That all depends on the size of the organisation.

I have 200 open tickets in the Tech department all being handled by different Agents. It is not easy to sieve through these. The whole point of **My Tickets** is to easily access the tickets that I am handling as these require follow-up etc and take a while to get sorted. 

I can view my Team tickets in the Open to claim more if need be, although another section for **Unassigned Team Tickets** would also come in handy to see what other tickets require attention.

The Agent does not need to look at other tickets of his colleagues as these are being handled and therefore he does not require constant visibility of these. 

This issue would not exist, if on Claiming of a Ticket, the Team portion is removed. This would have the same effect. In this case in **My Tickets** only the Agents tickets and the **Unassigned Team Tickets** would be listed which would make more sense.

**Comment by ntozier** [comment] 2016-12-20 14:20
The intent and way on how it works does not depend on the size of the organization, but I get that you want it to work differently.  I get that because this is the second time that you have asked for this type of change.  see https://github.com/osTicket/osTicket/issues/3372

So please close this duplicate thread and continue your comments on the original. Thanks.

**Comment by rayfoss** [comment] 2016-12-20 14:44
dupe  #3372

**Closed by rayfoss** 2016-12-20 14:44 UTC
Labels: enhancement

**Comment by ipAnything** [comment] 2016-12-21 10:18
@ntozier @rayfoss This is not a duplicate of #3372 

#3480 (This ticket) is about What tickets get displayed in the "My Tickets" tab/queue
#3372 is about removing the Assigned Staff member when Transferring the Ticket to a different Team

**Comment by chucks26** [comment] 2016-12-21 23:16
v1.10 (901e5ea) here.

First of all sorry for my poor English...
I had similar problem...need to have only tickets assigned to me or tickets assigned to a team I belong but not assigned to other agents in "My tickets" queue.

I did some edits in "**/include/staff/tickets.inc.php**" file:
At row 103 (case=assigned) added:
```
$agentteams=array_filter($thisstaff->getTeams()); //assegno alla variabile $agentteams l'array di team a cui appartengo
if (empty($agentteams)){      //se non si appartiene a nessun team
  $agentteams= array('100','101');   //assegnamo dei team fittizzi (100 e 101) per non far mandare in errore la query
 }
```
Then modify row 109 (previous 105) from:
`        Q::all(array('staff_id' => 0, 'team_id__gt' => 0)),`
to
`        Q::all(array('staff_id' => 0, 'team_id__in' => $teamsAGENT)),`

And that did the trick for me...
Just to explain, the first part of code get the teams I belong, if none, assign a dummy 100 & 101 teams id (just to avoid errors in the next query). The second get only tickets assigned to teams I belong.

Give a try if you want...I've been useing it in production for a while with no issues.

Cheers,
Chuck26

**Comment by ipAnything** [comment] 2016-12-22 16:49
@chucks26 Cool. I will try this.

**Comment by MAPtheMOP** [comment] 2017-07-13 05:16
Works fine to me. Thank you a lot! :)

**Comment by aditgjiu** [comment] 2018-01-08 08:08
@chucks26 . Thanks man, works.

**Comment by chucks26** [comment] 2018-01-08 21:54
You welcome!

**Comment by Langthjem** [comment] 2018-04-03 12:32
@chucks26 You are the real MVP

**Comment by stefanclark** [comment] 2018-04-03 13:38
Slightly edited code from @chucks26 above (no need for dummy team ids)

Replace the following line(s):
```
$tickets->filter(Q::any(array(
    'staff_id'=>$thisstaff->getId(),
    Q::all(array('staff_id' => 0, 'team_id__gt' => 0)),
)));
```
with:
```
$filter = Q::any(array(
    'staff_id'=>$thisstaff->getId(),
));
if ($teams = array_filter($thisstaff->getTeams())) {
    $filter->add(array('team_id__in' => $teams));
}
$tickets->filter($filter);
```

**Comment by claures** [comment] 2018-05-09 07:03
Thanks to @chucks26  and @stefanclark

**Comment by plong0** [comment] 2019-02-14 00:13
Thank you @chucks26  and @stefanclark!  You have made many in our office happy :)

If you want the functionality from @chucks26's where tickets assigned to an individual are hidden from other members of the team, here is a slight modification on @stefanclark's code

```
$filter = Q::any(array(
    'staff_id'=>$thisstaff->getId(),
));
if ($teams = array_filter($thisstaff->getTeams())) {
    $filter->add(Q::all(array('staff_id' => 0, 'team_id__in' => $teams)));
}
$tickets->filter($filter);
```

**Comment by yashu1wwww** [comment] 2024-03-21 15:39
when mini agent close the ticket why super admin cant see the closed status
