### ISSUE TITLE
Increase Issue Summary length

### ISSUE THREAD

**Issue by yafp** [osTicket/osTicket#3978] opened 2017-09-28 07:35 UTC
### Description
The issue summary is currently limited to 50 characters.
That is kinda limiting ...at least for me ;)

### Versions
1.9.12

**Comment by ntozier** [comment] 2017-09-28 14:25
1.9.12 is really old.  This is also not a bug.

**Comment by yafp** [comment] 2017-09-28 18:55
> This is also not a bug.

True, it's a feature request

**Comment by fdellwing** [comment] 2017-09-29 06:41
You can change the limit in your formular settings (at least in 1.10), so please close this issue.

**Closed** 2017-10-05 12:15 UTC

**Comment by yafp** [comment] 2017-10-06 06:19
worked - thanks for the pointer
