### ISSUE TITLE
Add a column in the users page for the organization

### ISSUE THREAD

**Issue by ricardoorosa** [osTicket/osTicket#3185] opened 2016-06-08 12:36 UTC
add a column in the users page for the organization

**Comment by rbukovansky** [comment] 2016-06-09 10:01
Duplicate of #1981 and #3042.

PR My #3191 should resolve it.

**Comment by mlipok** [comment] 2016-06-09 16:55
I agree.

**Comment by rayfoss** [comment] 2016-12-06 20:55
Closing duplicate issue, please continue the conversation on the ne

**Closed** 2016-12-06 21:04 UTC
