### ISSUE TITLE
Email sending issues.

### ISSUE THREAD

**Issue by nickmacwiz** [osTicket/osTicket#2628] opened 2015-10-06 19:45 UTC
Unable to log in. Check SMTP settings.

Sending Email via SMTP  
authentication failure [SMTP: STARTTLS failed (code: 220, response: 2.0.0 Ready to start TLS)]

**Comment by ntozier** [comment] 2015-10-06 20:00
version of osTicket?
Your mail server is failing your credentials.

**Comment by nickmacwiz** [comment] 2015-10-06 20:13
1.9.12

I am using gmail and the fetching is working fine just a problem with the sending.  I moved osTicket from an old windows server to a new one and the issue is only on the new server.

**Comment by ntozier** [comment] 2015-10-06 20:25
I seem to recall someone else mentioning that there was a bug with php 5.6, what version are you running?

**Comment by nickmacwiz** [comment] 2015-10-06 20:27
5.6

Should i try removing 5.6 and installing 5.5

**Comment by ntozier** [comment] 2015-10-06 20:34
I'd try that first.

**Comment by nickmacwiz** [comment] 2015-10-06 20:46
It worked.  Thanks

**Comment by greezybacon** [comment] 2015-10-12 13:09
I think we should keep this open and work to address the issue on PHP 5.6. As it becomes more widely used, the issue is going to become a larger issue

**Comment by infectormp** [comment] 2015-10-12 13:43
I not have SMTP problem with PHP 5.6 @ linux host. Look like it's windows specific problem.

**Comment by nickmacwiz** [comment] 2015-10-12 14:32
just to keep in mind. I am using Windows Server 2008 R2 64bit. Currently I am running 3 different versions of PHP 5.4, 5.5 and  5.6 on this server and have different websites use different versions because some web apps have issues with things on one version of PHP over another. While this could be an application issue it is also possible that the issue is with PHP 5.6 for Windows.

**Comment by jdelhome3578** [comment] 2015-10-12 22:07
@greezybacon this sounds the same as #2604. I believe that I have narrowed down the problem to this http://php.net/manual/en/migration56.openssl.php

**Comment by greezybacon** [comment] 2015-10-20 14:45
Would anyone have the opportunity to test again with the tip of the `develop-next` branch? The SMTP library was upgraded and I'm wondering if the new version has any bearing on the issue.

**Comment by nickmacwiz** [comment] 2015-10-20 15:21
Not sure about everyone else but we use osticket in a live environment and also use the eticket app that requires us to use only compatible versions. 

Sincerely,


Nicholas Ruebel

**Comment by infectormp** [comment] 2015-10-20 16:34
I use upgraded SMTP library (Net_SMTP v1.7.1) and not hava any problem.

**Comment by nickmacwiz** [comment] 2015-10-20 16:39
Which version of php are you using?

Sincerely,


Nicholas Ruebel

**Comment by infectormp** [comment] 2015-10-20 17:16
i use 5.6.14 and openssl 1.02d

**Comment by greezybacon** [comment] 2015-10-20 18:15
@infectormp could you just verify that you're using Windows with PHP 5.6 and you had an issue before the upgrade to SMTP 1.7.1?

**Comment by infectormp** [comment] 2015-10-20 18:20
@greezybacon sorry, i see this is windows related bug. I not using Windows at my server enviroment and can't verify issue.

**Comment by nickmacwiz** [comment] 2015-10-20 18:24
We have maintainance scheduled for this weekend. I will try and boot a duplicate virtual server machine and test it. 

Sincerely,


Nicholas Ruebel

**Comment by jdelhome3578** [comment] 2015-10-20 18:30
@greezybacon I have a windows environment with php 5.6.14 I receive `authentication failure [SMTP: STARTTLS failed (code: 220, response: 2.0.0 SMTP server ready)]` as an error message. If I use php 5.5.28 it works fine.

**Comment by greezybacon** [comment] 2015-10-20 18:32
> I use upgraded SMTP library (Net_SMTP v1.7.1) and not hava any problem.

So this then has absolutely nothing to do with the issue at hand?

**Comment by jdelhome3578** [comment] 2015-10-20 18:34
@greezybacon As I stated earlier I think it has something to do with the changes made in the php code http://php.net/manual/en/migration56.openssl.php

**Comment by jdelhome3578** [comment] 2015-10-20 18:39
@greezybacon As I stated earlier I think it has something to do with the changes made in the php code http://php.net/manual/en/migration56.openssl.php

PHP now requires peer verification and I have tried a lot of thing but can not figure out how to get it setup on my Windows system.

**Comment by mfelber** [comment] 2015-10-29 16:15
This seems not to be only a windows problem. I had a similar problem with some of my osticket 1.9.12 instances when I switch to php 5.6. 

They are running on a hosted server with debian squeeze. The used SMTP Port is 587. First I didn't noticed that because osticket seems to have a workaround sending the emails in this case instead via the php mailer. 

In the system logs of osticket were a lots of this errrors:
SMTP: Invalid response code received from server (code: 550, response: relay not permitted)

When I tried to save the mail server credentials again I got this error in the gui:
authentication failure [SMTP: STARTTLS failed (code: 220, response: TLS go ahead)]

Switching back to php 5.5 solves this issue.

**Comment by mfelber** [comment] 2015-10-30 07:47
Disabling the peer verification seems also to solve the problem (using php 5.6):

https://github.com/pear/Net_SMTP/issues/14

**Comment by mfelber** [comment] 2015-10-30 08:19
This issue also occurs in osticket 1.10 (latest tip).

**Comment by Hannibal226** [comment] 2015-10-30 13:17
@mfelber 
Nope not for me.
So I recognized this Problem now, too. Quiet late, but anway.
We can recieve/fetch email fine and sending in domain, too. but out of that not.

I'm using also PHP 5.6 and STMP/587 with authentication.

Would be pleased to see a wordaround because none of them helped here.
I'm not sure if a downgrade makes so much sense as 1.10 is close, same as PHP7.

CHEERS!

**Comment by mfelber** [comment] 2015-10-30 13:28
@Hannibal226 In my case the workaround with replacing

$this->_socket_options =$socket_options;

to

$this->_socket_options = array('ssl' => array('verify_peer_name' => false));

in  /include/pear/Net/SMTP.php works fine.

But I heared from somebody else that this workaround doesn't help him too (like in your case).

Do you still get the same error? What OS do you use?

Why do you mention 1.10 and PHP7? 1.10 has the same problem yet and PHP 7 seems not be recommended soon..

**Comment by Hannibal226** [comment] 2015-10-30 14:18
@mfelber 
It's windows and afaik it's a windows+PHP 5.6 problem, so...

I mentioned because I don't know if maybe 1.10 will have an inbuild workaround, but more it's a one time maintance break, so installing PHP+new osticket, than once PHP and after some weeks 1.10 (just lazyness :P )

And PHP7 is not recommended, but I reading a lot of trying to make it compatible and I don't think it will prot the problem from 5.6, that why I thought about.

CHEERS!

**Comment by mfelber** [comment] 2015-10-30 14:43
@Hannibal226 
The person that I mentioned who also has problems with the workaround uses windows too.

I use for my production systems only hosted debian squeeze server.

So I were a little bit curious and tested the workaround in my windows xampp test environment (Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14): the workaround works fine there too.
Maybe it's a little bit more than only a windows thing...

**Comment by jdelhome3578** [comment] 2015-10-30 14:45
> Disabling the peer verification seems also to solve the problem (using php 5.6):
> 
> pear/Net_SMTP#14

@mfelber Thanks I was looking for a way to disable, this worked for me [IIS 8 and php5.6.14]

**Comment by mfelber** [comment] 2015-10-30 14:48
@jdelhome3578 I'm glad I could help.

**Comment by jdelhome3578** [comment] 2015-10-30 14:50
@mfelber I just hope there is a permanent solution

**Comment by mfelber** [comment] 2015-10-30 14:57
@jdelhome3578 I'm confident that this issue will be addressed by the developers sometime as Jared said:
> I think we should keep this open and work to address the issue on PHP 5.6. As it becomes more widely used, the issue is going to become a larger issue

**Comment by nickmacwiz** [comment] 2015-10-30 14:58
For Windows server users the easiest solution is to install php 5.5 as well and set php 5.5 as the active version for your osticket site.

**Comment by Hannibal226** [comment] 2015-11-04 12:41
Just to let u know guys, I made a think-misstake and there is a lot easier solution:

I just said IP of ticketsystem is trusted send relay for exchange. 
So I just can send mails to exchange without authentication.

But anyway I hadn't recognize the bug before, as we had PHP 5.5 aber after Update no one reported problems.

CHEERS!

**Comment by danielbald** [comment] 2015-12-01 13:19
Bug is present on Debian jessie PHP 5.6.14-0+deb8u1

Can confirm the temp fix from @mfelber works.

**Comment by robertskiba** [comment] 2015-12-01 14:20
Hi Guys,

I just found this thread because I had the same problem with my osticket-installation on big european hoster HOSTEUROPE. In the last week, I just changed my main php installation from php 5.5 to php5.6. At my hoster, it's just a klick to to this. I didn't recognize any changes because everything seemed to work fine: My Ticketing-Mails were received by pop from all my three accounts as it should be and the mails seemed to be received by my customers. 

BUT:

The only thing that was wrong was the Error 550 Relaying not permitted that was displayed in the log of OST.

I tried around with the smtp-settings and I found out, that OST didn't manage to connect to the configured smtp-server at another provider. (I'm using version v1.10-rc.2 (231f11e)) but instead it tried to send mails out via php-mail-function (even if I forbid this in the settings). My Webserver doesn't know the outgoing mail adress and warns by saing "relaying not permitted" (with which he is right!). 

When I changed back to PHP5.5 or PHP5.3, everything works perfect again without complains!


Is there a solution in progress? It's not urgent but in 2016, my provider will set 5.6 as standard-php and in late 2016 the ability to use 5.5 will end completely... 

What now?

**Comment by axwell** [comment] 2015-12-10 08:59
Hello,
OsTicket is using a local copy of pear and it is outdated.
Donwload 
https://pear.php.net/package/Net_SMTP/download
http://pear.php.net/package/Net_Socket/download

replace SMTP.php and Socket.php from "include/pear/Net/" with the ones from the downloaded archives.

Changelog for SMTP 
- Add TLSv1.1 and TLSv1.2 support for STARTTLS connections. (#22)

Once you do this, osticket should work.

**Comment by sebastianbinder** [comment] 2016-01-01 13:41
This does not work on debian jessie with php 5.6.14. Any ideas?

**Comment by infectormp** [comment] 2016-01-01 14:38
Any errors in log?
1 янв. 2016 г. 4:41 PM пользователь "Sebastian Binder" <
notifications@github.com> написал:

**Comment by sebastianbinder** [comment] 2016-01-01 14:40
```
Unable to email via SMTP:mail. consored-domain.com:587 [mail@consored-domain.com]
Failed to set sender: mail@consored-domain.com [SMTP: Invalid response code received from server (code: 530, response: 5.7.0 Must issue a STARTTLS command first)]
```

**Comment by andreas-kolf** [comment] 2016-01-20 10:08
I also have same Problem.

Clean install with:
Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) i686 (Jessie), Linux 3.16.0-4-686-pae,
Apache 2.4.10,
PHP 5.6.14-0+deb8u1,
MySQL 5.5.46,
osTicket v1.9.12 (19292ad),
external IMAP and SMTP with STARTTLS

When i enable IMAP on port 143 it seems to have no problem and fetches "new" Mails. Setting SMTP to enable, server-port to 587 and authentication to yes i get this error "authentication failure [SMTP: STARTTLS failed (code: 220, response: TLS go ahead)]"

Even while debug-level is "debug" there is no entry in OS-System-Log.

Anybody any idea to get it work?

Andreas

**Comment by johnhunt** [comment] 2016-02-17 14:00
This is also happening for me on CentOS 7.2 PHP 5.6.

I'm going to see if I can fix this and stick in a pull request.

**Comment by UkaLee** [comment] 2016-02-17 14:35
Hello,
OsTicket is using a local copy of pear and it is outdated.
Donwload
pear.php.net/package/Net_SMTP/download
pear.php.net/package/Net_Socket/download


replace SMTP.php and Socket.php from "include/pear/Net/" with the ones from the downloaded archives.


Changelog for SMTP


Add TLSv1.1 and TLSv1.2 support for STARTTLS connections. (#22)


Once you do this, osticket should work.


==============================================



/var/www/osticket/osticket/include/pear/Net

-rw-r--r-- 1 www-data --> SMTP.php
-rw-r--r-- 1 www-data --> Socket.php

**Comment by johnhunt** [comment] 2016-02-17 14:42
@UkaLee That didn't work for me, have a look at this diff to see what I did (in case anyone else has similar issues):

https://github.com/johnhunt/osTicket-1.8/commit/d48499b66e3ce9950bdccb7d9b8689a5acaa359f

**Comment by hubertbanas** [comment] 2016-02-26 18:16
Can we please bump up the priority on this bug? Seems like a serious issue to me especially if the support is unable to receive the email alerts. In some circumstance the tech support may not be even aware of undelivered emails.

**Comment by joelrb** [comment] 2016-02-29 08:21
This worked for me as suggested by @mfelber 

Change

$this->_socket_options =$socket_options;

to

$this->_socket_options = array('ssl' => array('verify_peer_name' => false));

**Comment by hubertbanas** [comment] 2016-02-29 12:36
@joelrb sure it works but the next osTicket update may replace the file and cause no emails until you tweak it again.

**Comment by ShaneOss** [comment] 2016-05-11 01:32
If it were PHPMailer could use the following..

        $mail->SMTPOptions = array(
			'ssl' => array(
				'verify_peer' => false,
				'verify_peer_name' => false,
				'allow_self_signed' => true
			)
		);

**Comment by Pooleyy** [comment] 2016-06-23 10:00
I was also getting
authentication failure [SMTP: STARTTLS failed (code: 220, response: 2.0.0 Ready to start TLS)]

I've updated my SMTP.php and Socket.php /include/pear/Net - to the latest versions.
pear.php.net/package/Net_SMTP/download
pear.php.net/package/Net_Socket/download

Now I'm getting another error
authentication failure [SMTP: Invalid response code received from server (code: 535, response: 5.7.3 Authentication unsuccessful)]

osTicket Core, v1.9.14
PHP Version 5.6.19

**Comment by mfelber** [comment] 2016-06-23 12:09
Try to use port 465 for SMTP and add "ssl://"  before the server entry:

![smtp](https://cloud.githubusercontent.com/assets/5539456/16302544/08c0e9bc-394c-11e6-85e3-9a79159e2b50.jpg)

**Comment by Pooleyy** [comment] 2016-06-23 12:13
I've tried a different email with Authentication Required: yes
this works fine. For some reason the other email doesn't authenticate and therefore fails.
Strange - but using an office 365 liscenced email works fine.

**Comment by ntozier** [comment] 2016-06-23 12:54
This:
authentication failure [SMTP: Invalid response code received from server (code: 535, response: 5.7.3 Authentication unsuccessful)]

usually indicates that authentication was unsuccessful. I would think that this would be at the remote end personally.

**Comment by robintoy** [comment] 2016-06-23 13:06
You have two ways of getting this to work from an administration point of view....

1. You use authentication
2. You remove authentication like we did and restrict access to your SMTP server via IP address and sending domain.
![smtp settings](https://cloud.githubusercontent.com/assets/8893903/16304063/af31fd78-394b-11e6-9fd2-7d0d6c95f28b.png)

**Comment by robintoy** [comment] 2016-06-23 13:07
As I was posting @Pooleyy I noticed you talk about Office 365.

You say a licensed mailbox works??
Are you trying to use a "Shared Mailbox" ??

**Comment by Pooleyy** [comment] 2016-06-23 13:12
Ahh Robin it could be Shared yes.
But... I have the same email address set up on an old osTickets and it works fine. With no Authentication like you have suggested above.

**Comment by robintoy** [comment] 2016-06-23 13:15
Hi @Pooleyy 
you will not be able to use Office 365 like our configuration as you do not have access to Microsoft's Exchange cluster directly to add the right rules as required.

With a shared mailbox MS did an update a while ago stopping authentication to it, the only way to auth against a shared mailbox is with one of the users that has access to the mail box

**Comment by Pooleyy** [comment] 2016-06-23 13:16
Hi @robintoy 
I see, thanks for your input - appreciated.
I've solved it by using another email now. It's just odd how it still works on my old osTickets.
Cheers! Sam

**Comment by Nordi-EU** [comment] 2016-08-13 04:23
I'm having the same problems with PHP 5.6 and v1.9.14.

This problem makes osTicket unusable for me. Almost every email provider is enforcing a STARTTLS connection and I already tried Inbox.lv and Zoho.com without any success.

Also changing $this->_socket_options =$socket_options; did not help. It only created a new error message:  authentication failure [SMTP: Invalid response code received from server (code: 535, response: Incorrect authentication data)] 

(but username and password are correct).

I can't understand how such problem can exist for almost a year and why its still not fixed.

**Comment by cosmospham** [comment] 2016-08-13 19:07
I use:

- this hack from d48499b66e3ce9950bdccb7d9b8689a5acaa359f
- change in `__construct` function:

```
$this->socket_options = array('ssl' => array(
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true
        ));
```

- set `ssl://` in config
- use port for ssl

It worked.

`PHP 5.6.24-0+deb8u1`

**Comment by vcongion** [comment] 2016-08-23 05:19
I currently have 30+ emails in our mail queue that are not sending out to Google because Google is rejecting emails. Does anyone have a stable fix for this?

**Comment by awjans-ae** [comment] 2016-09-27 19:53
I'm running debian and php5.6 and had the same problem. Instead of changing the code in the Net_SMTP constructor, I changed the two calls to instantiate the Net_SMTP class in include/pear/Mail/smtpmx.php and include/pear/Mail/smtp.php to pass in the socket options. I believe that is a better fix. And this is a PEAR issue, not an osTicket issue.

**Comment by blackyzero** [comment] 2016-11-05 06:06
i am getting same issue with latest release 1.10
unable to enable SMTP authentication, always getting STARTTLS issue.

also trying with all above suggestion, but not working :(

**Comment by indramgl** [comment] 2016-12-07 04:27
I agreed with @cosmospham using d48499b

His method worked on version 1.10 / 1.9.15.

If this can be pushed to the main branch, that will be great.

**Server Information**
osTicket Version	v1.9.15 (70898b3) —  Up to date
Web Server Software	Apache/2.4.23 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
MySQL Version	5.5.52
PHP Version	5.6.27

**Comment by jdelhome3578** [comment] 2016-12-08 12:41
@protich fixed this with 4f68aeb

**Closed** 2016-12-08 12:41 UTC
Labels: bug, [deprecated] Email

**Comment by milindras** [comment] 2017-02-26 01:02
Hi This is still not working for me. I use 1 and 1 UK hosting with TLS 587.

Any help?

**Comment by ntozier** [comment] 2017-02-27 15:01
I would recommend that you talk to 1and1 and ask them why its not working.

**Comment by cendolpuluit** [comment] 2017-06-29 07:58
need some urgent assistance ...

i cant save smtp (gmail) at my helpdesk osticket.. below is the attachment of my version.
is it related to php ver 5.6 also ? tq

![error1](https://user-images.githubusercontent.com/29770978/27677270-93a42b5a-5ce3-11e7-964e-6b392e9e5389.PNG)
![error2](https://user-images.githubusercontent.com/29770978/27677271-93a639e0-5ce3-11e7-8adc-fbca427a8cb9.PNG)

**Comment by cendolpuluit** [comment] 2017-06-29 08:01
one more question , im using in windows server 2008 r2 standard 64bit environment .. is there any configuration must do to smtp server  function (build in with windows) .. sorry im really newbie with this osticket configuration. seems im taking this from other klik ...
![error3](https://user-images.githubusercontent.com/29770978/27677426-3bf2354a-5ce4-11e7-9ec9-25f36bac112d.PNG)

**Comment by cendolpuluit** [comment] 2017-06-29 08:01
hope someone help me. thanks

**Comment by ntozier** [comment] 2017-06-29 13:32
"SMTP: Failed to connect: No connection could be made because the target machine actively refused it"
The remote server is refusing the connection.  


In SMTP Virtual Mail Server feature in windows the server generally needs permission to relay.  Go back to that screen that you posted.  Click on the Access tab.  Click Relay, and add the IP address of the webserver.  Also make sure that the firewall allows connection on the port that you are using.

**Comment by cendolpuluit** [comment] 2017-06-29 13:45
dear ntozier ,

seems im newbie.. sorry... i've once open the ip... i see ip somelike this 127.0.0.1 .. i don know where its come..

**Comment by cendolpuluit** [comment] 2017-06-29 13:50
like this right?

![error1](https://user-images.githubusercontent.com/29770978/27690822-f27a2234-5d14-11e7-8a1c-866895142565.PNG)

**Comment by ntozier** [comment] 2017-06-29 13:54
I do not know what your IP addresses are, so I can't really answer as to if it's correct.  I presume that your webserver is 172.21.9.40, and that you are running the SMTP Virtual Server on the same machine? Also check your firewall. :)

**Comment by cendolpuluit** [comment] 2017-06-29 13:58
yes , osticket all in this server .. yes smtp virtual server also same machine... oracle sun blade machine.. running windows server 2008 r2 standard 64bit... after i include the server(machine) ip  in relay and test save the smtp setting for ndccmalaysia@gmail.com also failed.. use 4 diff port , 465 , 443 , 25 , 587

**Comment by cendolpuluit** [comment] 2017-06-29 14:00
i can see SMTP tick in firewall windowss.. but this machine also installed  with kaspersky.  i don know whether firewall being control by kaspersky as well..

![error2](https://user-images.githubusercontent.com/29770978/27691310-3701471a-5d16-11e7-9971-0c9d2a425454.PNG)

**Comment by jgomez4000** [comment] 2018-04-13 21:27
I was having the same problem (STARTTLS error) connecting to smtp.gmail.com.
Host: Windows Server 2012 (IIS 8.5), PHP 7, MySQL (5.7).

Adding the option 'verify_peer' => false to 'ssl' socket options fixed it.
In the file include/pear/Net/SMTP.php, in the construct function change:
```
// Turn off peer name verification by default\n
if (!$socket_options)
    $socket_options = array(
        'ssl' => array('verify_peer_name' => false)
    );
```
for
```
// Turn off peer name verification by default\n
if (!$socket_options)
    $socket_options = array(
        'ssl' => array('verify_peer_name' => false, 'verify_peer' => false)
    );
```

**Comment by emlk530** [comment] 2018-10-25 07:09
Nothings works for me

 Sending Email via SMTP     
Failed to connect to smtp.gmail.com:465 [SMTP: Failed to connect socket: Connection timed out (code: -1, response: )]

**Comment by Mukesh753** [comment] 2020-12-07 05:51
Failed to connect to smtp.gmail.com:587 [SMTP: Failed to connect socket: Connection refused (code: -1, response: )]
--

Server Information
--
osTicket Version | v1.15 (d5ee0df) —  Up to date
Web Server Software | Apache
MySQL Version | 5.6.49
PHP Version | 7.3.23


Please help for resolving this issue
