### ISSUE TITLE
Attachments goes missing intermittently while creating a new ticket / editing ticket

### ISSUE THREAD

**Issue by vishnus** [osTicket/osTicket#4204] opened 2018-03-22 08:08 UTC
### Description
Hi all,

We have over 100 agents working on tickets every day with little over a million tickets on the system. Very frequently agents are facing attachment missing issue. We are also using this plugin "Attachments on Filesystem" from osticket. We are unable to reproduce it because it's intermittent and when we retry it works. There are no errors in JS or server level. But in less frequent we are seeing this error DB Error # 1062 which we guess is different from attachments going missing. I already checked:
#3481 
https://github.com/osTicket/osTicket-plugins/issues/101 
http://osticket.com/forum/discussion/90438/attachments-not-being-uploaded-for-tickets-from-staff-control-panel
etc..

### Steps to Reproduce

1. Unable to reproduce because its intermittent

**Expected behavior:** [What you expected to happen]
All attachments to be saved correctly every time in file system.

**Actual behavior:** [What actually happened]
Sometimes attachments go missing. It happens sometimes when you create a ticket or when you reply to a ticket. But text and other contents remains intact.

### Versions
1.10.1

Also, please include the OS and what version of the OS you're running. As well as your browser and browser version.
Ubuntu 16.04, Happens in both Chrome and Firefox latest versions.

**Comment by perryk** [comment] 2018-03-22 12:17
I think I've seen this a little, it is quite rare for us though. Perhaps with more tickets, you will have a better chance of reproducing this and trying to narrow down where the error might be.

Something I tried was to examine the database directly for any ticket that someone reports as having come in with an attachment missing.

There are ID numbers for the ticket, it's thread, each thread entry, and then the attachments etc which should all link up and you can then see if everything is making sense and perhaps if there are any missing entries or I'm guessing something like skipped ID numbers for attachments which attempted to save to the database however something prevented it or interrupted the process.

I understand these can happen (or do always?) for tickets logged via the web however you may also want to try increasing the time between cron jobs running for collecting and processing emails too. I'm fairly certain the process can take a little while and I don't think it would be ideal to have more than 1 of these active at any 1 time.

**Comment by vishnus** [comment] 2018-03-22 13:17
@perryk 
ah totally agree, when we reached a state where crons were overlapping because of volume of emails, we noticed duplicate tickets being created. So right now its 15min interval (we get around 100 emails in 10 minutes on a peak day which is scary). Some times few old emails gets never picked up unless the rate of incoming emails go down completely. Not sure why but thats a totally different issue.

Because of the volume, we're still unable to pin-point what could be the issue with attachments. Agents have to go back and check the ticket everytime they create to confirm that attachments are there. We had an older instance 1.8 version which never had this issue even with same volumes..

**Comment by JediKev** [comment] 2018-03-22 14:15
@perryk @vishnus 

This sounds like it might be related to an issue that we are in the process of fixing. Please stay tuned!

Cheers.

**Comment by vishnus** [comment] 2018-03-22 18:40
@JediKev thanks for the update, please ref the commit here once its fixed so that we can merge the same.

**Comment by mwhitneysdsu** [comment] 2018-03-22 21:38
I noticed this issue when we initially started testing our deployment. I can't be completely certain, due to the intermittent nature of the issue, but so far I haven't experienced the issue if I wait to attach my file(s) until just before I submit the ticket. I was going to start testing to see if the issue was related to tickets being saved as a draft after the attachments are added.

**Comment by JediKev** [comment] 2018-03-23 14:37
@mwhitneysdsu 

That's basically what we think the issue is. Attachments aren't being added to the draft and therefore aren't being sent out. We are working on a fix for this so please stay tuned.

Cheers.

**Comment by kler** [comment] 2018-10-17 13:42
Hi, what's the status of this feature?

**Comment by JediKev** [comment] 2018-10-17 13:52
@kler 

The feature I made (Save Attachments To Draft) is in limbo until we start `1.12.x`, I believe. We addressed the original issue of attachments dropping when sending replies in separate commits in both the `develop` and `develop-next` branches which is `1.10.x` and `1.11.x` respectively (as of now); so the feature is more of a nicety at this point to be added later.

Cheers.

**Comment by kler** [comment] 2018-10-18 08:41
I see, we're actually still on 1.10.1 and are experiencing the problem, so it was maybe fixed after that.

**Closed** 2020-01-06 20:02 UTC

**Comment by OgnjenVu** [comment] 2021-02-05 07:35
@JediKev 

Good day,

I work for as a contractor for a Ministry of Customs and Revenue of a country that uses OS Ticket themselves. This issues has occurred lately on a version 1.14.1, there are no plugins installed. Can you let us know how far are you from resolving this issue and is there a workaround so we can avoid this issue ever repeating?

Thank you upfront
