### ISSUE TITLE
%{message.files} is not working with agent templates on V1.9.14

### ISSUE THREAD

**Issue by ifrandika** [osTicket/osTicket#3318] opened 2016-08-24 06:51 UTC
I read many kbs but cannot figure out why %{message.files} agent template variable does not work with V1.9.14. I need to attach original email files with ticket assignment alerts but instead of attachments this variable gets printed in to the alert email.

Does anybody out there know the reason and any solution?

Cheers!

**Comment by ntozier** [comment] 2016-08-24 13:05
This appears to be a duplicate of:
https://github.com/osTicket/osTicket/issues/2992
and
https://github.com/osTicket/osTicket/issues/3047

**Comment by Dika1989** [comment] 2016-08-24 13:14
@ntozier Thanks for the response!

I think no! I read both of those threads before start this. They are not addressing this issue and solutions given does not work with my case.

**Closed** 2020-01-06 20:06 UTC
