### ISSUE TITLE
1.9.12: fields with long text will be truncated in the pdf export

### ISSUE THREAD

**Issue by mfelber** [osTicket/osTicket#2644] opened 2015-10-12 12:41 UTC
Here is a exampe pdf export:

![ticket export](https://cloud.githubusercontent.com/assets/5539456/10428058/117f555a-70ef-11e5-9e1f-5be4b8a71ea9.JPG)

I guess there should be a line break.

Is this a bug? Will it be fixed?

**Comment by greezybacon** [comment] 2015-10-12 12:45
This is addressed in v1.10. The PDF printing was changed to a pure HTML output and allows the PDF system (mPDF) to layout the page with word and line wrapping.

**Comment by mfelber** [comment] 2015-12-20 10:19
https://github.com/osTicket/osTicket-1.8/issues/2796#issuecomment-166101832

**Comment by mfelber** [comment] 2015-12-20 10:19
#2796

**Comment by greezybacon** [comment] 2015-12-21 17:27
@mfelber #2796 is a duplicate of this ticket. It does not concern v1.10

**Comment by mfelber** [comment] 2015-12-21 19:00
@greezybacon Yes, I know. That was the reason I referenced It to this issue. Was this wrong?

**Comment by greezybacon** [comment] 2015-12-21 21:06
I see. You were correct to reference it. Perhaps you should have written "Duplicate of #2796" or "#2796 is a duplicate of this issue"

**Comment by mfelber** [comment] 2015-12-22 04:49
Aha, I understand. Next time I will describe it as a duplicate issue..

**Closed** 2016-12-06 22:02 UTC
Labels: fix-available, pdf

**Comment by Alghaith87** [comment] 2017-07-18 08:41
Hello, i have the same issue . 
v1.9.12 (19292ad)
Thanks.
![osprint](https://user-images.githubusercontent.com/30255873/28308127-f6f9ac06-6bad-11e7-880a-9ca82472a3ff.png)
