### ISSUE TITLE
api 400 when creating ticket through api

### ISSUE THREAD

**Issue by fang-yu** [osTicket/osTicket#4138] opened 2018-01-17 13:31 UTC
### Prerequisites

* [x] Can you reproduce the problem in a fresh installation of the "develop" branch?
* [x] Do you have any errors in the PHP error log, or javascript console?
* [x] Did you check the [osTicket forums](http://osticket.com/forum/categories)?
* [x] Did you [perform a cursory search](https://github.com/osTicket/osTicket/issues) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/osTicket/osTicket/wiki/Github-Issues-Guidelines)

### Description

I am using external forming service like wufoo to create ticket in osticket with api, but get error of:
1.  api 400 and API Error (400): Unable to create new ticket: validation errors: user: Incomplete client information
2. API Unexpected Data phone: Unexpected data received in API request 

#### [First Step]: set up webhook in external forming service.

there is the sercive description:
> Send the data to a third party in JSON format
When selected, gold data will send JSON formatted data to the corresponding HTTP address POST upon receipt of the data. The server needs to return 2XX (200, 201, etc.) in 2 seconds as a reply. If something goes wrong, the gold data will be retried up to six times.

[Field comparison table and JSON examples](javascript:void(0))

| Field Name             | type of data     | API Code       |
| ---------------------- | ---------------- | -------------- |
| Serial number          | Float            | serial_number  |
| Ticket type            | String           | field_55       |
| Ticket title           | String           | field_52       |
| emergency level        | String           | field_54       |
| student ID             | BSON :: ObjectId | field_63       |
| Emergency reasons      | String           | field_61       |
| Work order description | String           | field_50       |
| Own course             | String           | field_57       |
| Add screenshots        | Array            | field_62       |
| project files          | Array            | field_60       |
| Name                   | String           | field_53       |
| mailbox                | String           | field_64       |
| Submitter              | String           | creator_name   |
| Submit time            | DateTime         | created_at     |
| Change the time        | DateTime         | updated_at     |
| IP                     | String           | info_remote_ip |

```
{
   " Form " : " VsfHLJ " ,
   " FORM_NAME " : " half-left school ticket service system " ,
   " entry " : {
     " serial_number " : 123 ,
     " field_55 " : " option. 1 " ,
     " field_52 " : " This is One line of text " ,
     " field_54 " : "Option 1 " ,
     "field_63 " : " associated data " ,
     " field_61 " : " This is a line of text " ,
     " field_50 " : " This is a paragraph of text " ,
     " field_57 " : " Option 1 " ,
     " field_62 " : [
       " https: // example .jinshuju.net / en / key1? token = token & download " ,
       " https://example.jinshuju.net/en/key2?token=token&download "
    ], " field_60 "
    : [
       " https://example.jinshuju.net/en/key1?token=token&download " ,
       " https://example.jinshuju.net/en/key2?token=token&download " 
    ], " field_53 " : " Zhang San " ,
     " field_64 " : " support@jinshuju.net " ,
     " CREATOR_NAME " : " Wang " ,
     " created_at " : " 2018-01-17 13:22:39 UTC " ,
    " Updated_at "
    : " 2018-01-17 13:22:39 UTC " ,
     " info_remote_ip " : " 127.0.0.1 " 
  } 
}
```
the HTTP POST address: ***help.mydomain.com/tool/apiticket.php***。

#### [Second Step]: set up api in osticket

add following code to tool/apiticket.php in my osticket folder.

```
#!/usr/bin/php -q
<?php
#
# Configuration: Enter the url and key. That is it.
#  url => URL to api/task/cron e.g #  http://yourdomain.com/support/api/tickets.json
#  key => API's Key (see admin panel on how to generate a key)
#  $data add custom required fields to the array.
#
#  Originally authored by jared@osTicket.com
#  Modified by ntozier@osTicket / tmib.net

// If 1, display things to debug.
$debug="0";

// You must configure the url and key in the array below.

$config = array(
        'url'=>'http://help.mydomain.com/api/http.php/tickets.json',
        'key'=>'xxxx'
);
# NOTE: some people have reported having to use "http://your.domain.tld/api/http.php/tickets.json" instead.

echo $_SERVER['REMOTE_ADDR'];
echo $config['url'];
echo $config['key'];

if($config['url'] === 'http://your.domain.tld/api/tickets.json') {
  echo "<p style=\"color:red;\"><b>Error: No URL</b><br>You have not configured this script with your URL!</p>";
  echo "Please edit this file ".__FILE__." and add your URL at line 18.</p>";
  die();  
}       
if(IsNullOrEmptyString($config['key']) || ($config['key'] === 'PUTyourAPIkeyHERE'))  {
  echo "<p style=\"color:red;\"><b>Error: No API Key</b><br>You have not configured this script with an API Key!</p>";
  echo "<p>Please log into osticket as an admin and navigate to: Admin panel -> Manage -> Api Keys then add a new API Key.<br>";
  echo "Once you have your key edit this file ".__FILE__." and add the key at line 19.</p>";
  die();
}
        
# Fill in the data for the new ticket, this will likely come from $_POST.
# NOTE: your variable names in osT are case sensiTive. 
# So when adding custom lists or fields make sure you use the same case
# For examples on how to do that see Agency and Site below.
$data = array(
    'name'      =>      "field_53",  // from name aka User/Client Name
    'email'     =>      'field_64',  // from email aka User/Client Email
  'phone'   =>    '1234567890',  // phone number aka User/Client Phone Number
    'subject'   =>      'field_52',  // test subject, aka Issue Summary
    'message'   =>      'This is a test of the osTicket API',  // test ticket body, aka Issue Details.
    'ip'        =>      $_SERVER['REMOTE_ADDR'], // Should be IP address of the machine thats trying to open the ticket.
  'topicId'   =>      '1', // the help Topic that you want to use for the ticket 
  //'Agency'  =>    '58', //this is an example of a custom list entry. This should be the number of the entry.
  //'Site'  =>    'Bermuda'; // this is an example of a custom text field.  You can push anything into here you want. 
    'attachments' => array()
);

# more fields are available and are documented at:
# https://github.com/osTicket/osTicket-1.8/blob/develop/setup/doc/api/tickets.md

if($debug=='1') {
  print_r($data);
  die();
}

# Add in attachments here if necessary
# Note: there is something with this wrong with the file attachment here it does not work.
$data['attachments'][] =
array('file.txt' =>
        'data:text/plain;base64;'
            .base64_encode(file_get_contents('/file.txt')));  // replace ./file.txt with /path/to/your/test/filename.txt
 

#pre-checks
function_exists('curl_version') or die('CURL support required');
function_exists('json_encode') or die('JSON support required');

#set timeout
set_time_limit(30);

#curl post
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $config['url']);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
curl_setopt($ch, CURLOPT_USERAGENT, 'osTicket API Client v1.8');
curl_setopt($ch, CURLOPT_HEADER, FALSE);
curl_setopt($ch, CURLOPT_HTTPHEADER, array( 'Expect:', 'X-API-Key: '.$config['key']));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, FALSE);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
$result=curl_exec($ch);
$code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

if ($code != 201)
    die('Unable to create ticket: '.$result);

$ticket_id = (int) $result;

# Continue onward here if necessary. $ticket_id has the ID number of the
# newly-created ticket

function IsNullOrEmptyString($question){
    return (!isset($question) || trim($question)==='');
}
?>
```

**Expected behavior:** create ticket through webhook

**Actual behavior:** api 400

### Versions

osTicket Version | v1.10.1 (9ae093d) —  Up to date
Web Server Software | Apache
MySQL Version | 5.5.57
PHP Version | 7.0.19

**Comment by ntozier** [comment] 2018-01-17 15:12
Your JSON data set that you posted... does not have a phone number.

{
   " Form " : " VsfHLJ " ,
   " FORM_NAME " : " half-left school ticket service system " ,
   " entry " : {
     " serial_number " : 123 ,
     " field_55 " : " option. 1 " ,
     " field_52 " : " This is One line of text " ,
     " field_54 " : "Option 1 " ,
     "field_63 " : " associated data " ,
     " field_61 " : " This is a line of text " ,
     " field_50 " : " This is a paragraph of text " ,
     " field_57 " : " Option 1 " ,
     " field_62 " : [
       " https: // example .jinshuju.net / en / key1? token = token & download " ,
       " https://example.jinshuju.net/en/key2?token=token&download "
    ], " field_60 "
    : [
       " https://example.jinshuju.net/en/key1?token=token&download " ,
       " https://example.jinshuju.net/en/key2?token=token&download " 
    ], " field_53 " : " Zhang San " ,
     " field_64 " : " support@jinshuju.net " ,
     " CREATOR_NAME " : " Wang " ,
     " created_at " : " 2018-01-17 13:22:39 UTC " ,
    " Updated_at "
    : " 2018-01-17 13:22:39 UTC " ,
     " info_remote_ip " : " 127.0.0.1 " 
  } 
}

I see that you are hard coding th ephone number to 1234567890 in the PHP.  So it's not phone. However 
your PHP script is not using variables... its using hard coded values:

$data = array(
    'name'      =>      "field_53",  // from name aka User/Client Name
    'email'     =>      'field_64',  // from email aka User/Client Email
  'phone'   =>    '1234567890',  // phone number aka User/Client Phone Number
    'subject'   =>      'field_52',  // test subject, aka Issue Summary
    'message'   =>      'This is a test of the osTicket API',  // test ticket body, aka Issue Details.
    'ip'        =>      $_SERVER['REMOTE_ADDR'], // Should be IP address of the machine thats trying to open the ticket.
  'topicId'   =>      '1', // the help Topic that you want to use for the ticket 
  //'Agency'  =>    '58', //this is an example of a custom list entry. This should be the number of the entry.
  //'Site'  =>    'Bermuda'; // this is an example of a custom text field.  You can push anything into here you want. 
    'attachments' => array()
);

This would try to create an account for 
Name: field_53
Email: field_64

field_64 is not a valid email address.  This would likely result in the error of "validation errors: user: Incomplete client information"

**Comment by fang-yu** [comment] 2018-01-18 05:53
@ntozier thanks for your reply. field_53 and field_64 are from wehhook jason which is: 

```

{
" Form " : " VsfHLJ " ,
" FORM_NAME " : " half-left school ticket service system " ,
" entry " : {
" field_53 " : " Zhang San " ,
" field_64 " : " support@jinshuju.net " ,
}
}
```

So do you mean that I should change the script to sth like:
```
$data = array(
    'name'      =>      " Zhang San ",  // from name aka User/Client Name
    'email'     =>      " support@jinshuju.net ",  // from email aka User/Client Email
);

```

I am not quite sure how to use the jason, and integrate with api..

**Comment by fang-yu** [comment] 2018-01-18 06:10
I do some research，and change to code to：

```
$data = array(
    'name'      =>      $field_53,  // from name aka User/Client Name
    'email'     =>      $field_64,  // from email aka User/Client Email
    'phone'     =>      $field_65,  // phone number aka User/Client Phone Number
    'subject'   =>      $field_52,  // test subject, aka Issue Summary
    'message'   =>      $field_50,  // test ticket body, aka Issue Details.
    'ip'        =>      $_SERVER['REMOTE_ADDR'], // Should be IP address of the machine thats trying to open the ticket.
  //'topicId'   =>      'serial_number', // the help Topic that you want to use for the ticket 
  //'Agency'  =>    '58', //this is an example of a custom list entry. This should be the number of the entry.
  //'Site'  =>    'Bermuda'; // this is an example of a custom text field.  You can push anything into here you want. 
    //'attachments' => array()
);
```

It look like something get better, but I still get `Unable to create new ticket: validation errors: user: Incomplete client information 20: subject is a required field *` Error, and I am sure that in the webhook data, $field_52 do have data.

**Comment by ntozier** [comment] 2018-01-19 16:24
Since this is not a bug report please close this and continue the conversation on the forums.
http://osticket.com/forum/discussion/91728/api-400-when-creating-ticket-through-api

**Comment by mixrat** [comment] 2018-01-27 18:52
You are missing a quotation mark after the serial number 123...
     " serial_number " : 123 ,
     " field_55 " : " option. 1 " ,
     " field_52 " : " This is One line of text " ,

**Closed** 2020-01-06 20:02 UTC
