### ISSUE TITLE
Advanced search DateTime regression

### ISSUE THREAD

**Issue by jamesangi** [osTicket/osTicket#4146] opened 2018-01-31 22:19 UTC
I think a bug may have been introduced in commit 69b85f0.  If you try to do an advanced search with the criteria of Due Date ON x/y/z it fails and gives a browser message of:

Fatal error: __clone method called on non-object in /var/www/html/osTicket/include/class.forms.php on line 2008 (line number for commit 69b85f0)

The error does not happen if I rollback to commit 90210e2.  The same thing happens from the head of develop, albeit with a different line number.

**Comment by seiddegu** [comment] 2018-09-07 16:35
i do face this problem on version 1.10.1 , i used the commit 9021e2 and the problem is fixed.

Thank you @jamesangi  for ur findings.

**Comment by JediKev** [comment] 2018-09-07 16:37
@seiddegu

This has been addressed in `1.11.0rc-1`.

Cheers.

**Comment by seiddegu** [comment] 2018-09-07 16:49
Thank You Bro, i will check that..

**Comment by osTicketRocks** [comment] 2018-11-01 15:30
I recently updated osTicket to the latest stable release and I also face the same issue when users try to use the advanced search.

This is the fatal error message I get.
> Fatal error: Uncaught Error: __clone method called on non-object in /is/htdocs/XXX/include/class.forms.php:2035 Stack trace: #0 /is/htdocs/XXX/include/class.search.php(952): DatetimeField->getSearchQ('equal', '2018-10-26 00:0...', 'est_duedate') #1 /is/htdocs/XXX/scp/tickets.php(422): SavedSearch->mangleQuerySet(Object(QuerySet), Object(AdvancedSearchForm)) #2 {main} thrown in /is/htdocs/XXX/include/class.forms.php on line 2035

Is there any way to fix this problem?


Thanks a lot. :-)

**Closed** 2020-01-06 20:02 UTC
